<?php
/**
 * Master Assessment Definitions
 *
 * This is the single source of truth for all assessments. Each question contains
 * its own display logic, options, and complete scoring rules.
 * This unified structure eliminates the need for complex mappers and ensures data integrity.
 */
return array(
	'welcome_assessment'      => array(
		'welcome_q1' => array(
			'id'         => 'welcome_q1',
			'title'      => 'What is your gender?',
			'type'       => 'radio',
			'options'    => array(
				'male'   => 'Male',
				'female' => 'Female',
			),
			'required'   => true,
			'global_key' => 'gender',
			'scoring'    => array(
				'category' => 'Demographics',
				'weight'   => 0,
				'answers'  => array(
					'male'   => 0,
					'female' => 0,
				),
			),
		),
		'welcome_q2' => array(
			'id'         => 'welcome_q2',
			'title'      => 'What is your date of birth?',
			'type'       => 'dob_dropdowns',
			'required'   => true,
			'global_key' => 'user_dob_combined',
		),
		'welcome_q3' => array(
			'id'          => 'welcome_q3',
			'title'       => 'What are your main health goals?',
			'description' => 'Select all that apply.',
			'type'        => 'multiselect',
			'options'     => array(
				'live_longer'      => 'Live longer',
				'boost_energy'     => 'Boost energy',
				'improve_sleep'    => 'Improve sleep',
				'lose_weight'      => 'Lose weight',
				'build_muscle'     => 'Build muscle',
				'sharpen_focus'    => 'Sharpen focus & memory',
				'balance_hormones' => 'Balance hormones',
				'improve_mood'     => 'Improve mood',
				'boost_libido'     => 'Boost libido & performance',
				'support_heart'    => 'Support heart health',
				'manage_menopause' => 'Manage menopause',
				'increase_test'    => 'Increase testosterone',
			),
			'required'    => true,
			'global_key'  => 'health_goals',
			'scoring'     => array(
				'category' => 'Goals',
				'weight'   => 0,
				'answers'  => array(),
			),
		),
		'welcome_q4' => array(
			'id'         => 'welcome_q4',
			'title'      => "What's your full name?",
			'type'       => 'first_last_name',
			'required'   => true,
			'global_key' => 'first_last_name',
		),
		'welcome_q5' => array(
			'id'         => 'welcome_q5',
			'title'      => 'What is your contact information?',
			'type'       => 'email_phone',
			'required'   => true,
			'global_key' => 'email_phone',
		),
	),
	'hair_assessment'         => array(
		'hair_q1'  => array(
			'id'         => 'hair_q1',
			'title'      => 'What is your date of birth?',
			'type'       => 'dob_dropdowns',
			'required'   => true,
			'global_key' => 'user_dob_combined',
			'scoring'    => array(
				'category' => 'Demographics',
				'weight'   => 0,
				'answers'  => array(),
			),
		),
		'hair_q2'  => array(
			'id'         => 'hair_q2',
			'title'      => 'What is your gender?',
			'type'       => 'radio',
			'options'    => array(
				'male'   => 'Male',
				'female' => 'Female',
			),
			'required'   => true,
			'global_key' => 'gender',
			'scoring'    => array(
				'category' => 'Demographics',
				'weight'   => 0.5,
				'answers'  => array(
					'male'   => 5,
					'female' => 5,
				),
			),
		),
		'hair_q3'  => array(
			'id'       => 'hair_q3',
			'title'    => 'What are your main hair concerns?',
			'type'     => 'multiselect',
			'options'  => array(
				'thinning'     => 'Thinning Hair',
				'receding'     => 'Receding Hairline',
				'bald_spots'   => 'Bald Spots',
				'overall_loss' => 'Overall Hair Loss',
			),
			'required' => true,
			'scoring'  => array(
				'category' => 'Hair Health Status',
				'weight'   => 3,
				'answers'  => array(
					'thinning'     => 4,
					'receding'     => 3,
					'bald_spots'   => 2,
					'overall_loss' => 1,
				),
			),
		),
		'hair_q4'  => array(
			'id'       => 'hair_q4',
			'title'    => 'How long have you been experiencing hair loss?',
			'type'     => 'radio',
			'options'  => array(
				'recent'    => 'Less than 6 months',
				'moderate'  => '6 months - 2 years',
				'long'      => '2-5 years',
				'very_long' => 'More than 5 years',
			),
			'required' => true,
			'scoring'  => array(
				'category' => 'Progression Timeline',
				'weight'   => 2,
				'answers'  => array(
					'recent'    => 8,
					'moderate'  => 6,
					'long'      => 4,
					'very_long' => 2,
				),
			),
		),
		'hair_q5'  => array(
			'id'       => 'hair_q5',
			'title'    => 'How would you describe the speed of your hair loss?',
			'type'     => 'radio',
			'options'  => array(
				'slow'      => 'Very Slow',
				'moderate'  => 'Moderate',
				'fast'      => 'Fast',
				'very_fast' => 'Very Fast',
			),
			'required' => true,
			'scoring'  => array(
				'category' => 'Progression Rate',
				'weight'   => 2.5,
				'answers'  => array(
					'slow'      => 8,
					'moderate'  => 6,
					'fast'      => 3,
					'very_fast' => 1,
				),
			),
		),
		'hair_q6'  => array(
			'id'       => 'hair_q6',
			'title'    => 'Is there a history of hair loss in your family?',
			'type'     => 'radio',
			'options'  => array(
				'none'   => 'No Family History',
				'mother' => "Mother's Side",
				'father' => "Father's Side",
				'both'   => 'Both Sides',
			),
			'required' => true,
			'scoring'  => array(
				'category' => 'Genetic Factors',
				'weight'   => 2,
				'answers'  => array(
					'none'   => 9,
					'mother' => 6,
					'father' => 5,
					'both'   => 3,
				),
			),
		),
		'hair_q7'  => array(
			'id'       => 'hair_q7',
			'title'    => 'What is your current stress level?',
			'type'     => 'radio',
			'options'  => array(
				'low'       => 'Low Stress',
				'moderate'  => 'Moderate Stress',
				'high'      => 'High Stress',
				'very_high' => 'Very High Stress',
			),
			'required' => true,
			'scoring'  => array(
				'category' => 'Lifestyle Factors',
				'weight'   => 1.5,
				'answers'  => array(
					'low'       => 9,
					'moderate'  => 7,
					'high'      => 4,
					'very_high' => 2,
				),
			),
		),
		'hair_q8'  => array(
			'id'       => 'hair_q8',
			'title'    => 'How would you rate your current diet quality?',
			'type'     => 'radio',
			'options'  => array(
				'excellent' => 'Excellent',
				'good'      => 'Good',
				'fair'      => 'Fair',
				'poor'      => 'Poor',
			),
			'required' => true,
			'scoring'  => array(
				'category' => 'Nutritional Support',
				'weight'   => 1.5,
				'answers'  => array(
					'excellent' => 9,
					'good'      => 7,
					'fair'      => 5,
					'poor'      => 2,
				),
			),
		),
		'hair_q9'  => array(
			'id'       => 'hair_q9',
			'title'    => 'Have you tried any hair loss treatments before?',
			'type'     => 'radio',
			'options'  => array(
				'none'         => 'No Treatments',
				'otc'          => 'Over-the-Counter',
				'prescription' => 'Prescription Meds',
				'procedures'   => 'Medical Procedures',
			),
			'required' => true,
			'scoring'  => array(
				'category' => 'Treatment History',
				'weight'   => 1,
				'answers'  => array(
					'none'         => 7,
					'otc'          => 6,
					'prescription' => 5,
					'procedures'   => 4,
				),
			),
		),
		'hair_q10' => array(
			'id'       => 'hair_q10',
			'title'    => 'What are your hair goals?',
			'type'     => 'multiselect',
			'options'  => array(
				'stop_loss' => 'Stop Hair Loss',
				'regrow'    => 'Regrow Hair',
				'thicken'   => 'Thicken Hair',
				'improve'   => 'Overall Improvement',
			),
			'required' => true,
			'scoring'  => array(
				'category' => 'Treatment Expectations',
				'weight'   => 1,
				'answers'  => array(
					'stop_loss' => 8,
					'regrow'    => 6,
					'thicken'   => 7,
					'improve'   => 8,
				),
			),
		),
		'hair_q11' => array(
			'id'         => 'hair_q11',
			'title'      => 'Let\'s get your contact information.',
			'type'       => 'contact_info',
			'required'   => true,
			'global_key' => 'contact_info',
		),
	),
	'ed_treatment_assessment' => array(
		'gender_filter'    => 'male',
		'title'            => 'ED Treatment Assessment',
		'ed_treatment_q1'  => array(
			'id'         => 'ed_treatment_q1',
			'title'      => 'What is your date of birth?',
			'type'       => 'dob_dropdowns',
			'required'   => true,
			'global_key' => 'user_dob_combined',
			'scoring'    => array(
				'category' => 'Demographics',
				'weight'   => 0,
				'answers'  => array(),
			),
		),
		'ed_treatment_q2'  => array(
			'id'       => 'ed_treatment_q2',
			'title'    => 'What is your relationship status?',
			'type'     => 'radio',
			'options'  => array(
				'single'   => 'Single',
				'dating'   => 'Dating',
				'married'  => 'Married/Partnered',
				'divorced' => 'Divorced/Separated',
			),
			'required' => true,
			'scoring'  => array(
				'category' => 'Psychosocial Factors',
				'weight'   => 1,
				'answers'  => array(
					'single'   => 6,
					'dating'   => 7,
					'married'  => 8,
					'divorced' => 5,
				),
			),
		),
		'ed_treatment_q3'  => array(
			'id'       => 'ed_treatment_q3',
			'title'    => 'How would you describe the severity of your ED?',
			'type'     => 'radio',
			'options'  => array(
				'mild'     => 'Mild',
				'moderate' => 'Moderate',
				'severe'   => 'Severe',
				'complete' => 'Complete',
			),
			'required' => true,
			'scoring'  => array(
				'category' => 'Condition Severity',
				'weight'   => 3,
				'answers'  => array(
					'mild'     => 8,
					'moderate' => 6,
					'severe'   => 3,
					'complete' => 1,
				),
			),
		),
		'ed_treatment_q4'  => array(
			'id'       => 'ed_treatment_q4',
			'title'    => 'How long have you been experiencing symptoms of ED?',
			'type'     => 'radio',
			'options'  => array(
				'recent'    => 'Less than 6 months',
				'moderate'  => '6 months - 2 years',
				'long'      => '2-5 years',
				'very_long' => 'More than 5 years',
			),
			'required' => true,
			'scoring'  => array(
				'category' => 'Timeline',
				'weight'   => 2,
				'answers'  => array(
					'recent'    => 8,
					'moderate'  => 6,
					'long'      => 4,
					'very_long' => 2,
				),
			),
		),
		'ed_treatment_q5'  => array(
			'id'       => 'ed_treatment_q5',
			'title'    => 'Do you have any of the following health conditions?',
			'type'     => 'multiselect',
			'options'  => array(
				'none'         => 'None of these',
				'diabetes'     => 'Diabetes',
				'heart'        => 'Heart Disease',
				'hypertension' => 'High Blood Pressure',
			),
			'required' => true,
			'scoring'  => array(
				'category' => 'Medical Factors',
				'weight'   => 2.5,
				'answers'  => array(
					'none'         => 9,
					'diabetes'     => 4,
					'heart'        => 3,
					'hypertension' => 4,
				),
			),
		),
		'ed_treatment_q6'  => array(
			'id'       => 'ed_treatment_q6',
			'title'    => 'Have you tried any ED treatments before?',
			'type'     => 'radio',
			'options'  => array(
				'none'       => 'No previous treatments',
				'oral'       => 'Oral medications',
				'injections' => 'Injections',
				'devices'    => 'Vacuum devices',
			),
			'required' => true,
			'scoring'  => array(
				'category' => 'Treatment History',
				'weight'   => 1,
				'answers'  => array(
					'none'       => 7,
					'oral'       => 6,
					'injections' => 5,
					'devices'    => 5,
				),
			),
		),
		'ed_treatment_q7'  => array(
			'id'       => 'ed_treatment_q7',
			'title'    => 'Do you smoke or use tobacco products?',
			'type'     => 'radio',
			'options'  => array(
				'no'           => 'No',
				'yes_socially' => 'Yes, socially',
				'yes_daily'    => 'Yes, daily',
				'former'       => 'I am a former smoker',
			),
			'required' => true,
			'scoring'  => array(
				'category' => 'Medical Factors',
				'weight'   => 1.5,
				'answers'  => array(
					'no'           => 9,
					'yes_socially' => 4,
					'yes_daily'    => 2,
					'former'       => 6,
				),
			),
		),
		'ed_treatment_q8'  => array(
			'id'       => 'ed_treatment_q8',
			'title'    => 'How often do you exercise?',
			'type'     => 'radio',
			'options'  => array(
				'never'     => 'Never',
				'rarely'    => 'Rarely',
				'regularly' => 'Regularly',
				'daily'     => 'Daily',
			),
			'required' => true,
			'scoring'  => array(
				'category' => 'Physical Health',
				'weight'   => 1.5,
				'answers'  => array(
					'never'     => 3,
					'rarely'    => 5,
					'regularly' => 8,
					'daily'     => 9,
				),
			),
		),
		'ed_treatment_q9'  => array(
			'id'       => 'ed_treatment_q9',
			'title'    => 'How would you describe your current stress level?',
			'type'     => 'radio',
			'options'  => array(
				'low'       => 'Low',
				'moderate'  => 'Moderate',
				'high'      => 'High',
				'very_high' => 'Very High',
			),
			'required' => true,
			'scoring'  => array(
				'category' => 'Psychological Factors',
				'weight'   => 2,
				'answers'  => array(
					'low'       => 9,
					'moderate'  => 7,
					'high'      => 4,
					'very_high' => 2,
				),
			),
		),
		'ed_treatment_q10' => array(
			'id'       => 'ed_treatment_q10',
			'title'    => 'What are your primary goals for seeking treatment?',
			'type'     => 'multiselect',
			'options'  => array(
				'restore'      => 'Restore function',
				'confidence'   => 'Boost confidence',
				'performance'  => 'Improve performance',
				'relationship' => 'Improve relationship',
			),
			'required' => true,
			'scoring'  => array(
				'category' => 'Treatment Motivation',
				'weight'   => 1,
				'answers'  => array(
					'restore'      => 8,
					'confidence'   => 7,
					'performance'  => 6,
					'relationship' => 8,
				),
			),
		),
		'ed_treatment_q11' => array(
			'id'       => 'ed_treatment_q11',
			'title'    => 'Are you currently taking any of the following types of medications?',
			'type'     => 'multiselect',
			'options'  => array(
				'none'            => 'No medications',
				'blood_pressure'  => 'Blood pressure meds',
				'antidepressants' => 'Antidepressants',
				'other'           => 'Other medications',
			),
			'required' => true,
			'scoring'  => array(
				'category' => 'Drug Interactions',
				'weight'   => 1.5,
				'answers'  => array(
					'none'            => 8,
					'blood_pressure'  => 5,
					'antidepressants' => 4,
					'other'           => 6,
				),
			),
		),
		'ed_treatment_q12' => array(
			'id'         => 'ed_treatment_q12',
			'title'      => 'Let\'s get your contact information.',
			'type'       => 'contact_info',
			'required'   => true,
			'global_key' => 'contact_info',
		),
	),
	'weight_loss_assessment'  => array(
		'weight_loss_q1'  => array(
			'id'         => 'weight_loss_q1',
			'title'      => 'What is your date of birth?',
			'type'       => 'dob_dropdowns',
			'required'   => true,
			'global_key' => 'user_dob_combined',
			'scoring'    => array(
				'category' => 'Demographics',
				'weight'   => 0,
				'answers'  => array(),
			),
		),
		'weight_loss_q2'  => array(
			'id'         => 'weight_loss_q2',
			'title'      => 'What is your gender?',
			'type'       => 'radio',
			'options'    => array(
				'male'   => 'Male',
				'female' => 'Female',
			),
			'required'   => true,
			'global_key' => 'gender',
			'scoring'    => array(
				'category' => 'Demographics',
				'weight'   => 0.5,
				'answers'  => array(
					'male'   => 5,
					'female' => 5,
				),
			),
		),
		'weight_loss_q3'  => array(
			'id'         => 'weight_loss_q3',
			'title'      => 'What is your primary weight loss goal?',
			'type'       => 'multiselect',
			'options'    => array(
				'lose_10'  => 'Lose 10-20 lbs',
				'lose_30'  => 'Lose 20-50 lbs',
				'lose_50'  => 'Lose 50+ lbs',
				'maintain' => 'Maintain current weight',
			),
			'required'   => true,
			'global_key' => 'health_goals',
			'scoring'    => array(
				'category' => 'Motivation & Goals',
				'weight'   => 2,
				'answers'  => array(
					'lose_10'  => 8,
					'lose_30'  => 7,
					'lose_50'  => 6,
					'maintain' => 9,
				),
			),
		),
		'weight_loss_q4'  => array(
			'id'         => 'weight_loss_q4',
			'title'      => 'What is your height and weight?',
			'type'       => 'height_weight',
			'required'   => true,
			'global_key' => 'height_weight',
			'scoring'    => array(
				'category' => 'Current Status',
				'weight'   => 0,
				'answers'  => array(),
			),
		),
		'weight_loss_q5'  => array(
			'id'       => 'weight_loss_q5',
			'title'    => 'How often do you exercise?',
			'type'     => 'radio',
			'options'  => array(
				'never'  => 'Never',
				'rarely' => '1-2 times/week',
				'often'  => '3-4 times/week',
				'daily'  => '5+ times/week',
			),
			'required' => true,
			'scoring'  => array(
				'category' => 'Physical Activity',
				'weight'   => 2.5,
				'answers'  => array(
					'never'  => 1,
					'rarely' => 3,
					'often'  => 8,
					'daily'  => 9,
				),
			),
		),
		'weight_loss_q6'  => array(
			'id'       => 'weight_loss_q6',
			'title'    => 'How would you describe your typical diet?',
			'type'     => 'radio',
			'options'  => array(
				'unhealthy' => 'Mostly Unhealthy',
				'balanced'  => 'Generally Balanced',
				'healthy'   => 'Very Healthy',
				'strict'    => 'Strict Diet',
			),
			'required' => true,
			'scoring'  => array(
				'category' => 'Nutrition',
				'weight'   => 3,
				'answers'  => array(
					'unhealthy' => 2,
					'balanced'  => 6,
					'healthy'   => 8,
					'strict'    => 7,
				),
			),
		),
		'weight_loss_q7'  => array(
			'id'       => 'weight_loss_q7',
			'title'    => 'How many hours of sleep do you get per night?',
			'type'     => 'radio',
			'options'  => array(
				'less_5' => 'Less than 5 hours',
				'5_6'    => '5-6 hours',
				'7_8'    => '7-8 hours',
				'more_8' => 'More than 8 hours',
			),
			'required' => true,
			'scoring'  => array(
				'category' => 'Lifestyle Factors',
				'weight'   => 1.5,
				'answers'  => array(
					'less_5' => 3,
					'5_6'    => 5,
					'7_8'    => 9,
					'more_8' => 8,
				),
			),
		),
		'weight_loss_q8'  => array(
			'id'       => 'weight_loss_q8',
			'title'    => 'How would you rate your daily stress levels?',
			'type'     => 'radio',
			'options'  => array(
				'low'       => 'Low',
				'moderate'  => 'Moderate',
				'high'      => 'High',
				'very_high' => 'Very High',
			),
			'required' => true,
			'scoring'  => array(
				'category' => 'Psychological Factors',
				'weight'   => 1.5,
				'answers'  => array(
					'low'       => 9,
					'moderate'  => 7,
					'high'      => 4,
					'very_high' => 2,
				),
			),
		),
		'weight_loss_q9'  => array(
			'id'       => 'weight_loss_q9',
			'title'    => 'What has been your experience with weight loss in the past?',
			'type'     => 'radio',
			'options'  => array(
				'no_success'   => 'Never had lasting success',
				'some_success' => 'Some success, but gained it back',
				'good_success' => 'Good success, maintained for a while',
				'first_time'   => 'This is my first serious attempt',
			),
			'required' => true,
			'scoring'  => array(
				'category' => 'Weight Loss History',
				'weight'   => 1,
				'answers'  => array(
					'no_success'   => 3,
					'some_success' => 4,
					'good_success' => 6,
					'first_time'   => 7,
				),
			),
		),
		'weight_loss_q10' => array(
			'id'       => 'weight_loss_q10',
			'title'    => 'Do you have any of these eating habits?',
			'type'     => 'multiselect',
			'options'  => array(
				'emotional_eating' => 'Emotional eating',
				'late_night'       => 'Late-night snacking',
				'binge_eating'     => 'Binge eating',
				'sugary_drinks'    => 'Sugary drinks',
			),
			'required' => true,
			'scoring'  => array(
				'category' => 'Behavioral Patterns',
				'weight'   => 1,
				'answers'  => array(
					'emotional_eating' => 3,
					'late_night'       => 4,
					'binge_eating'     => 2,
					'sugary_drinks'    => 3,
				),
			),
		),
		'weight_loss_q11' => array(
			'id'       => 'weight_loss_q11',
			'title'    => 'How motivated are you to make a change?',
			'type'     => 'radio',
			'options'  => array(
				'not_motivated'  => 'Not very motivated',
				'somewhat'       => 'Somewhat motivated',
				'very_motivated' => 'Very motivated',
				'committed'      => 'Committed and ready',
			),
			'required' => true,
			'scoring'  => array(
				'category' => 'Motivation & Goals',
				'weight'   => 1,
				'answers'  => array(
					'not_motivated'  => 2,
					'somewhat'       => 4,
					'very_motivated' => 7,
					'committed'      => 9,
				),
			),
		),
		'weight_loss_q12' => array(
			'id'       => 'weight_loss_q12',
			'title'    => 'What kind of support system do you have?',
			'type'     => 'radio',
			'options'  => array(
				'none'         => "I'm on my own",
				'partner'      => 'Partner/Spouse',
				'family'       => 'Family and Friends',
				'professional' => 'Professional (coach, etc.)',
			),
			'required' => true,
			'scoring'  => array(
				'category' => 'Social Support',
				'weight'   => 1,
				'answers'  => array(
					'none'         => 3,
					'partner'      => 7,
					'family'       => 8,
					'professional' => 9,
				),
			),
		),
		'weight_loss_q13' => array(
			'id'         => 'weight_loss_q13',
			'title'      => 'Let\'s get your contact information.',
			'type'       => 'contact_info',
			'required'   => true,
			'global_key' => 'contact_info',
		),
	),
	'health_assessment'       => array(
		'health_q1' => array(
			'id'         => 'health_q1',
			'title'      => 'What is your date of birth?',
			'type'       => 'dob_dropdowns',
			'required'   => true,
			'global_key' => 'user_dob_combined',
			'scoring'    => array(
				'category' => 'Demographics',
				'weight'   => 0,
				'answers'  => array(),
			),
		),
		'health_q2' => array(
			'id'         => 'health_q2',
			'title'      => 'What is your gender?',
			'type'       => 'radio',
			'options'    => array(
				'male'   => 'Male',
				'female' => 'Female',
			),
			'required'   => true,
			'global_key' => 'gender',
			'scoring'    => array(
				'category' => 'Demographics',
				'weight'   => 0.5,
				'answers'  => array(
					'male'   => 5,
					'female' => 5,
				),
			),
		),
		'health_q3' => array(
			'id'       => 'health_q3',
			'title'    => 'How would you rate your overall health?',
			'type'     => 'radio',
			'options'  => array(
				'poor'      => 'Poor',
				'fair'      => 'Fair',
				'good'      => 'Good',
				'excellent' => 'Excellent',
			),
			'required' => true,
			'scoring'  => array(
				'category' => 'Current Health Status',
				'weight'   => 3,
				'answers'  => array(
					'poor'      => 2,
					'fair'      => 5,
					'good'      => 7,
					'excellent' => 9,
				),
			),
		),
		'health_q4'  => array(
			'id'       => 'health_q4',
			'title'    => 'What is your height and weight?',
			'type'     => 'height_weight',
			'required' => true,
			'global_key' => 'height_weight',
		),
		'health_q5'  => array(
			'id'       => 'health_q5',
			'title'    => 'How often do you engage in moderate to intense physical activity?',
			'type'     => 'radio',
			'options'  => array(
				'rarely'    => 'Rarely or Never',
				'sometimes' => '1-2 times a week',
				'often'     => '3-5 times a week',
				'daily'     => 'Almost every day',
			),
			'required' => true,
			'scoring'  => array(
				'category' => 'Physical Activity',
				'weight'   => 2.5,
				'answers'  => array(
					'rarely'    => 1,
					'sometimes' => 5,
					'often'     => 8,
					'daily'     => 9,
				),
			),
		),
		'health_q6'  => array(
			'id'       => 'health_q6',
			'title'    => 'How would you describe your typical diet?',
			'type'     => 'radio',
			'options'  => array(
				'processed'    => 'High in processed foods',
				'average'      => 'A typical Western diet',
				'healthy'      => 'Mostly whole foods',
				'very_healthy' => 'Very clean, whole foods diet',
			),
			'required' => true,
			'scoring'  => array(
				'category' => 'Nutrition',
				'weight'   => 2.5,
				'answers'  => array(
					'processed'    => 2,
					'average'      => 5,
					'healthy'      => 7,
					'very_healthy' => 9,
				),
			),
		),
		'health_q7'  => array(
			'id'       => 'health_q7',
			'title'    => 'How would you rate your sleep quality?',
			'type'     => 'radio',
			'options'  => array(
				'poor'      => 'Poor, I wake up tired',
				'fair'      => 'Fair, could be better',
				'good'      => 'Good, usually restful',
				'excellent' => 'Excellent, I wake up refreshed',
			),
			'required' => true,
			'scoring'  => array(
				'category' => 'Sleep & Recovery',
				'weight'   => 2,
				'answers'  => array(
					'poor'      => 3,
					'fair'      => 5,
					'good'      => 7,
					'excellent' => 9,
				),
			),
		),
		'health_q8'  => array(
			'id'       => 'health_q8',
			'title'    => 'How well do you manage stress?',
			'type'     => 'radio',
			'options'  => array(
				'poorly'      => "I don't manage it well",
				'somewhat'    => 'I have some coping methods',
				'well'        => 'I manage it well',
				'proactively' => 'I have a proactive routine',
			),
			'required' => true,
			'scoring'  => array(
				'category' => 'Stress & Mental Health',
				'weight'   => 2,
				'answers'  => array(
					'poorly'      => 3,
					'somewhat'    => 5,
					'well'        => 7,
					'proactively' => 9,
				),
			),
		),
		'health_q9'  => array(
			'id'       => 'health_q9',
			'title'    => 'Do you get regular preventive care (e.g., check-ups)?',
			'type'     => 'radio',
			'options'  => array(
				'never'     => 'Never or rarely',
				'sometimes' => 'Only when I have a problem',
				'regularly' => 'I have regular annual check-ups',
			),
			'required' => true,
			'scoring'  => array(
				'category' => 'Preventive Health',
				'weight'   => 1.5,
				'answers'  => array(
					'never'     => 2,
					'sometimes' => 6,
					'regularly' => 9,
				),
			),
		),
		'health_q10' => array(
			'id'          => 'health_q10',
			'title'       => 'What are your main health goals?',
			'description' => 'Select all that apply.',
			'type'        => 'multiselect',
			'options'     => array(
				'live_longer'      => 'Live longer',
				'boost_energy'     => 'Boost energy',
				'improve_sleep'    => 'Improve sleep',
				'lose_weight'      => 'Lose weight',
				'build_muscle'     => 'Build muscle',
				'sharpen_focus'    => 'Sharpen focus & memory',
				'balance_hormones' => 'Balance hormones',
				'improve_mood'     => 'Improve mood',
				'boost_libido'     => 'Boost libido & performance',
				'support_heart'    => 'Support heart health',
				'manage_menopause' => 'Manage menopause',
				'increase_test'    => 'Increase testosterone',
			),
			'required'    => true,
			'global_key'  => 'health_goals',
			'scoring'     => array(
				'category' => 'Health Motivation',
				'weight'   => 1,
				'answers'  => array(
					'live_longer'      => 9,
					'boost_energy'     => 8,
					'improve_sleep'    => 8,
					'lose_weight'      => 7,
					'build_muscle'     => 7,
					'sharpen_focus'    => 8,
					'balance_hormones' => 9,
					'improve_mood'     => 7,
					'boost_libido'     => 8,
					'support_heart'    => 9,
					'manage_menopause' => 8,
					'increase_test'    => 8,
				),
			),
		),
		'health_q11' => array(
			'id'         => 'health_q11',
			'title'      => 'Let\'s get your contact information.',
			'type'       => 'contact_info',
			'required'   => true,
			'global_key' => 'contact_info',
		),
	),
	'skin_assessment'         => array(
		'skin_q1' => array(
			'id'         => 'skin_q1',
			'title'      => 'What is your date of birth?',
			'type'       => 'dob_dropdowns',
			'required'   => true,
			'global_key' => 'user_dob_combined',
			'scoring'    => array(
				'category' => 'Demographics',
				'weight'   => 0,
				'answers'  => array(),
			),
		),
		'skin_q2' => array(
			'id'         => 'skin_q2',
			'title'      => 'What is your gender?',
			'type'       => 'radio',
			'options'    => array(
				'male'   => 'Male',
				'female' => 'Female',
			),
			'required'   => true,
			'global_key' => 'gender',
			'scoring'    => array(
				'category' => 'Demographics',
				'weight'   => 0.5,
				'answers'  => array(
					'male'   => 5,
					'female' => 5,
				),
			),
		),
		'skin_q3' => array(
			'id'       => 'skin_q3',
			'title'    => 'What is your skin type?',
			'type'     => 'radio',
			'options'  => array(
				'normal'      => 'Normal',
				'dry'         => 'Dry',
				'oily'        => 'Oily',
				'combination' => 'Combination',
				'sensitive'   => 'Sensitive',
			),
			'required' => true,
			'scoring'  => array(
				'category' => 'Skin Characteristics',
				'weight'   => 2,
				'answers'  => array(
					'normal'      => 8,
					'dry'         => 6,
					'oily'        => 6,
					'combination' => 7,
					'sensitive'   => 5,
				),
			),
		),
		'skin_q4' => array(
			'id'       => 'skin_q4',
			'title'    => 'What is your primary skin concern?',
			'type'     => 'multiselect',
			'options'  => array(
				'acne'         => 'Acne & Blemishes',
				'aging'        => 'Fine Lines & Wrinkles',
				'pigmentation' => 'Dark Spots & Hyperpigmentation',
				'redness'      => 'Redness & Rosacea',
				'dullness'     => 'Dryness & Dehydration',
			),
			'required' => true,
			'scoring'  => array(
				'category' => 'Primary Skin Issue',
				'weight'   => 3,
				'answers'  => array(
					'acne'         => 3,
					'aging'        => 4,
					'pigmentation' => 5,
					'redness'      => 4,
					'dullness'     => 6,
				),
			),
		),
		'skin_q5' => array(
			'id'       => 'skin_q5',
			'title'    => 'How much sun exposure do you get?',
			'type'     => 'radio',
			'options'  => array(
				'minimal'  => "Rarely, I'm mostly indoors",
				'moderate' => 'Sometimes, on weekends',
				'high'     => 'Daily, but I use sunscreen',
			),
			'required' => true,
			'scoring'  => array(
				'category' => 'Environmental Factors',
				'weight'   => 2.5,
				'answers'  => array(
					'minimal'  => 9,
					'moderate' => 6,
					'high'     => 3,
				),
			),
		),
		'skin_q6' => array(
			'id'       => 'skin_q6',
			'title'    => 'How much water do you typically drink per day?',
			'type'     => 'radio',
			'options'  => array(
				'low'    => 'Less than 4 glasses',
				'medium' => '4-7 glasses',
				'high'   => '8 or more glasses',
			),
			'required' => true,
			'scoring'  => array(
				'category' => 'Hydration',
				'weight'   => 1.5,
				'answers'  => array(
					'low'    => 3,
					'medium' => 7,
					'high'   => 9,
				),
			),
		),
		'skin_q7' => array(
			'id'       => 'skin_q7',
			'title'    => 'What is your current skincare routine?',
			'type'     => 'radio',
			'options'  => array(
				'none'     => 'None',
				'basic'    => 'Basic (cleanse, moisturize, SPF)',
				'advanced' => 'Advanced (serums, exfoliants, etc.)',
			),
			'required' => true,
			'scoring'  => array(
				'category' => 'Current Regimen',
				'weight'   => 1,
				'answers'  => array(
					'none'     => 2,
					'basic'    => 6,
					'advanced' => 8,
				),
			),
		),
		'skin_q8' => array(
			'id'       => 'skin_q8',
			'title'    => 'Does your routine include active ingredients like retinoids or antioxidants?',
			'type'     => 'radio',
			'options'  => array(
				'no'       => 'No',
				'yes'      => 'Yes',
				'not_sure' => "I'm not sure",
			),
			'required' => true,
			'scoring'  => array(
				'category' => 'Advanced Care',
				'weight'   => 1.5,
				'answers'  => array(
					'no'       => 5,
					'yes'      => 9,
					'not_sure' => 4,
				),
			),
		),
		'skin_q9' => array(
			'id'       => 'skin_q9',
			'title'    => 'How does your skin typically react to new products?',
			'type'     => 'multiselect',
			'options'  => array(
				'none'      => 'No reaction',
				'redness'   => 'Becomes red or flushed',
				'breakouts' => 'I get breakouts',
				'itchiness' => 'It feels itchy or irritated',
				'dryness'   => 'Becomes dry and tight',
			),
			'required' => true,
			'scoring'  => array(
				'category' => 'Skin Reactivity',
				'weight'   => 1.5,
				'answers'  => array(
					'none'      => 9,
					'redness'   => 4,
					'breakouts' => 4,
					'itchiness' => 3,
					'dryness'   => 5,
				),
			),
		),
		'skin_q10' => array(
			'id'       => 'skin_q10',
			'title'    => 'Which of these lifestyle factors apply to you?',
			'type'     => 'multiselect',
			'options'  => array(
				'smoker'          => 'I smoke',
				'high_stress'     => 'I have high stress levels',
				'poor_sleep'      => 'I have poor sleep quality',
				'high_sugar_diet' => 'My diet is high in sugar/processed foods',
			),
			'required' => true,
			'scoring'  => array(
				'category' => 'Lifestyle & Diet',
				'weight'   => 2,
				'answers'  => array(
					'smoker'          => 3,
					'high_stress'     => 4,
					'poor_sleep'      => 4,
					'high_sugar_diet' => 3,
				),
			),
		),
		'skin_q11' => array(
			'id'         => 'skin_q11',
			'title'      => 'Let\'s get your contact information.',
			'type'       => 'contact_info',
			'required'   => true,
			'global_key' => 'contact_info',
		),
	),
	'sleep_assessment'        => array(
		'sleep_q1' => array(
			'id'       => 'sleep_q1',
			'title'    => 'On average, how many hours of sleep do you get per night?',
			'type'     => 'radio',
			'options'  => array(
				'less_than_5' => 'Less than 5 hours',
				'5_to_6'      => '5-6 hours',
				'7_to_8'      => '7-8 hours (Recommended)',
				'more_than_9' => '9 or more hours',
			),
			'required' => true,
			'scoring'  => array(
				'category' => 'Sleep Duration',
				'weight'   => 2.5,
				'answers'  => array(
					'less_than_5' => 2,
					'5_to_6'      => 4,
					'7_to_8'      => 9,
					'more_than_9' => 7,
				),
			),
		),
		'sleep_q2' => array(
			'id'       => 'sleep_q2',
			'title'    => 'How would you rate the quality of your sleep?',
			'type'     => 'radio',
			'options'  => array(
				'very_poor' => 'Very Poor',
				'poor'      => 'Poor',
				'fair'      => 'Fair',
				'good'      => 'Good',
			),
			'required' => true,
			'scoring'  => array(
				'category' => 'Sleep Quality',
				'weight'   => 3,
				'answers'  => array(
					'very_poor' => 1,
					'poor'      => 3,
					'fair'      => 5,
					'good'      => 8,
				),
			),
		),
		'sleep_q3' => array(
			'id'       => 'sleep_q3',
			'title'    => 'How often do you wake up during the night?',
			'type'     => 'radio',
			'options'  => array(
				'frequently' => 'Frequently (3+ times)',
				'sometimes'  => 'Sometimes (1-2 times)',
				'rarely'     => 'Rarely',
				'never'      => 'Never',
			),
			'required' => true,
			'scoring'  => array(
				'category' => 'Sleep Continuity',
				'weight'   => 2,
				'answers'  => array(
					'frequently' => 2,
					'sometimes'  => 5,
					'rarely'     => 8,
					'never'      => 9,
				),
			),
		),
		'sleep_q4' => array(
			'id'       => 'sleep_q4',
			'title'    => 'Once in bed, how long does it take you to fall asleep?',
			'type'     => 'radio',
			'options'  => array(
				'long'       => '> 45 minutes',
				'moderate'   => '30-45 minutes',
				'short'      => '15-30 minutes',
				'very_short' => '< 15 minutes',
			),
			'required' => true,
			'scoring'  => array(
				'category' => 'Sleep Latency',
				'weight'   => 2,
				'answers'  => array(
					'long'       => 2,
					'moderate'   => 5,
					'short'      => 8,
					'very_short' => 9,
				),
			),
		),
		'sleep_q5' => array(
			'id'       => 'sleep_q5',
			'title'    => 'How often do you feel drowsy or have the urge to nap during the day?',
			'type'     => 'radio',
			'options'  => array(
				'often'  => 'Often',
				'sometimes' => 'Sometimes',
				'rarely' => 'Rarely or Never',
			),
			'required' => true,
			'scoring'  => array(
				'category' => 'Daytime Function',
				'weight'   => 2.5,
				'answers'  => array(
					'often'  => 2,
					'sometimes' => 5,
					'rarely' => 9,
				),
			),
		),
		'sleep_q6' => array(
			'id'          => 'sleep_q6',
			'title'       => 'Which do you do within an hour of your intended bedtime?',
			'description' => 'Select all that apply.',
			'type'        => 'multiselect',
			'options'     => array(
				'screen_time' => 'Use phone/TV/computer',
				'caffeine'    => 'Consume caffeine',
				'large_meal'  => 'Eat a large meal',
				'exercise'    => 'Engage in vigorous exercise',
			),
			'required'    => true,
			'scoring'     => array(
				'category' => 'Sleep Hygiene',
				'weight'   => 1.5,
				'answers'  => array(
					'screen_time' => 3,
					'caffeine'    => 2,
					'large_meal'  => 4,
					'exercise'    => 4,
				),
			),
		),
		'sleep_q7' => array(
			'id'          => 'sleep_q7',
			'title'       => 'Which of the following do you use to help you sleep?',
			'description' => 'Select all that apply.',
			'type'        => 'multiselect',
			'options'     => array(
				'none'               => 'None',
				'melatonin'          => 'Melatonin',
				'herbal_supplements' => 'Herbal supplements (e.g., Valerian)',
				'otc_sleep_aids'     => 'Over-the-counter sleep aids',
				'prescription_meds'  => 'Prescription sleep medication',
			),
			'required'    => true,
			'scoring'     => array(
				'category' => 'Sleep Dependency',
				'weight'   => 1.5,
				'answers'  => array(
					'none'               => 9,
					'melatonin'          => 6,
					'herbal_supplements' => 5,
					'otc_sleep_aids'     => 4,
					'prescription_meds'  => 2,
				),
			),
		),
		'sleep_q8' => array(
			'id'         => 'sleep_q8',
			'title'      => 'Let\'s get your contact information.',
			'type'       => 'contact_info',
			'required'   => true,
			'global_key' => 'contact_info',
		),
	),
	'hormone_assessment'      => array(
		'hormone_q1' => array(
			'id'          => 'hormone_q1',
			'title'       => 'Which of these symptoms have you been experiencing?',
			'description' => 'Select all that apply.',
			'type'        => 'multiselect',
			'options'     => array(
				'fatigue_energy'      => 'Fatigue or lack of energy',
				'weight_fluctuations' => 'Unexplained weight gain or difficulty losing weight',
				'mood_swings'         => 'Mood swings, irritability, or anxiety',
				'libido_changes'      => 'Decreased sex drive',
				'sleep_issues'        => 'Difficulty sleeping',
				'skin_hair_changes'   => 'Changes in skin or hair (e.g., acne, thinning)',
				'none'                => 'None of the above',
			),
			'required'    => true,
			'scoring'     => array(
				'category' => 'Symptom Severity',
				'weight'   => 3,
				'answers'  => array(
					'fatigue_energy'      => 2,
					'weight_fluctuations' => 2,
					'mood_swings'         => 2,
					'libido_changes'      => 2,
					'sleep_issues'        => 2,
					'skin_hair_changes'   => 2,
					'none'                => 9,
				),
			),
		),
		'hormone_q2' => array(
			'id'          => 'hormone_q2',
			'title'       => 'In the last month, have you frequently experienced:',
			'description' => 'Select all that apply.',
			'type'        => 'multiselect',
			'options'     => array(
				'irritability' => 'Irritability',
				'anxiety'      => 'Anxiety',
				'low_mood'     => 'Low Mood',
				'brain_fog'    => 'Brain Fog',
			),
			'required'    => true,
			'scoring'     => array(
				'category' => 'Mood & Cognition',
				'weight'   => 2.5,
				'answers'  => array(
					'irritability' => 4,
					'anxiety'      => 4,
					'low_mood'     => 3,
					'brain_fog'    => 3,
				),
			),
		),
		'hormone_q3' => array(
			'id'       => 'hormone_q3',
			'title'    => 'How would you describe your energy levels?',
			'type'     => 'radio',
			'options'  => array(
				'consistently_low' => 'Consistently low',
				'afternoon_crash'  => 'I crash in the afternoon',
				'stable'           => 'Generally stable',
				'high_energy'      => 'High and consistent',
			),
			'required' => true,
			'scoring'  => array(
				'category' => 'Vitality',
				'weight'   => 2,
				'answers'  => array(
					'consistently_low' => 2,
					'afternoon_crash'  => 4,
					'stable'           => 7,
					'high_energy'      => 9,
				),
			),
		),
		'hormone_q4' => array(
			'id'       => 'hormone_q4',
			'title'    => 'How would you describe your ability to focus on complex tasks?',
			'type'     => 'radio',
			'options'  => array(
				'difficult' => 'Very difficult',
				'somewhat'  => 'Somewhat difficult',
				'no_issues' => 'No issues with focus',
			),
			'required' => true,
			'scoring'  => array(
				'category' => 'Mental Acuity',
				'weight'   => 2,
				'answers'  => array(
					'difficult' => 3,
					'somewhat'  => 5,
					'no_issues' => 9,
				),
			),
		),
		'hormone_q5' => array(
			'id'          => 'hormone_q5',
			'title'       => 'How many servings of cruciferous vegetables do you eat per week?',
			'description' => '(e.g., broccoli, cauliflower, cabbage)',
			'type'        => 'radio',
			'options'     => array(
				'zero_one'  => '0-1 servings',
				'two_three' => '2-3 servings',
				'four_plus' => '4+ servings',
			),
			'required'    => true,
			'scoring'     => array(
				'category' => 'Diet & Lifestyle',
				'weight'   => 1.5,
				'answers'  => array(
					'zero_one'  => 3,
					'two_three' => 6,
					'four_plus' => 9,
				),
			),
		),
		'hormone_q6' => array(
			'id'         => 'hormone_q6',
			'title'      => 'Let\'s get your contact information.',
			'type'       => 'contact_info',
			'required'   => true,
			'global_key' => 'contact_info',
		),
	),
	'menopause_assessment'    => array(
		'gender_filter' => 'female',
		'title'         => 'Menopause Assessment',
		'menopause_q1' => array(
			'id'            => 'menopause_q1',
			'title'         => 'Which of the following best describes your current stage?',
			'type'          => 'radio',
			'options'       => array(
				'not_started'    => 'I have not yet started menopause',
				'perimenopause'  => 'Perimenopause',
				'menopause'      => 'Menopause',
				'post_menopause' => 'Post-menopause',
			),
			'required'      => true,
			'gender_filter' => 'female',
			'scoring'       => array(
				'category' => 'Menopause Stage',
				'weight'   => 1,
				'answers'  => array(
					'not_started'    => 9,
					'perimenopause'  => 5,
					'menopause'      => 3,
					'post_menopause' => 4,
				),
			),
		),
		'menopause_q2' => array(
			'id'            => 'menopause_q2',
			'title'         => 'Which of these symptoms are you experiencing?',
			'description'   => 'Select all that apply.',
			'type'          => 'multiselect',
			'options'       => array(
				'hot_flashes'        => 'Hot flashes',
				'night_sweats'       => 'Night sweats',
				'sleep_disturbances' => 'Sleep disturbances',
				'mood_changes'       => 'Mood changes or irritability',
				'vaginal_dryness'    => 'Vaginal dryness',
				'none'               => 'None of the above',
			),
			'required'      => true,
			'gender_filter' => 'female',
			'scoring'       => array(
				'category' => 'Symptom Severity',
				'weight'   => 3,
				'answers'  => array(
					'hot_flashes'        => 2,
					'night_sweats'       => 2,
					'sleep_disturbances' => 2,
					'mood_changes'       => 2,
					'vaginal_dryness'    => 2,
					'none'               => 9,
				),
			),
		),
		'menopause_q3' => array(
			'id'            => 'menopause_q3',
			'title'         => 'In the last month, have you frequently experienced:',
			'description'   => 'Select all that apply.',
			'type'          => 'multiselect',
			'options'       => array(
				'mood_issues' => 'Irritability or Anxiety',
				'low_mood'    => 'Low Mood or Depression',
				'brain_fog'   => 'Brain Fog or Memory Lapses',
			),
			'required'      => true,
			'gender_filter' => 'female',
			'scoring'       => array(
				'category' => 'Mood & Cognition',
				'weight'   => 2.5,
				'answers'  => array(
					'mood_issues' => 3,
					'low_mood'    => 3,
					'brain_fog'   => 2,
				),
			),
		),
		'menopause_q4' => array(
			'id'            => 'menopause_q4',
			'title'         => 'How would you describe your ability to recover from exercise?',
			'type'          => 'radio',
			'options'       => array(
				'slower'  => 'Slower than it used to be',
				'same'    => 'About the same',
				'quickly' => 'I recover quickly',
			),
			'required'      => true,
			'gender_filter' => 'female',
			'scoring'       => array(
				'category' => 'Physical Performance',
				'weight'   => 2,
				'answers'  => array(
					'slower'  => 4,
					'same'    => 7,
					'quickly' => 9,
				),
			),
		),
		'menopause_q5' => array(
			'id'            => 'menopause_q5',
			'title'         => 'Have you noticed changes in how your body stores fat?',
			'type'          => 'radio',
			'options'       => array(
				'no_change'   => 'No change',
				'minor'       => 'Minor increase, especially abdomen',
				'significant' => 'Significant increase',
			),
			'required'      => true,
			'gender_filter' => 'female',
			'scoring'       => array(
				'category' => 'Body Composition',
				'weight'   => 2,
				'answers'  => array(
					'no_change'   => 8,
					'minor'       => 5,
					'significant' => 2,
				),
			),
		),
		'menopause_q6' => array(
			'id'            => 'menopause_q6',
			'title'         => 'Are you currently using or have you previously used HRT?',
			'type'          => 'radio',
			'options'       => array(
				'never'      => 'Never',
				'currently'  => 'Currently using',
				'previously' => 'Used in the past',
			),
			'required'      => true,
			'gender_filter' => 'female',
			'scoring'       => array(
				'category' => 'Treatment History',
				'weight'   => 1.5,
				'answers'  => array(
					'never'      => 7,
					'currently'  => 5,
					'previously' => 6,
				),
			),
		),
		'menopause_q7' => array(
			'id'         => 'menopause_q7',
			'title'      => 'Let\'s get your contact information.',
			'type'       => 'contact_info',
			'required'   => true,
			'global_key' => 'contact_info',
		),
	),
	'testosterone_assessment' => array(
		'gender_filter'   => 'male',
		'title'           => 'Testosterone Assessment',
		'testosterone_q1' => array(
			'id'            => 'testosterone_q1',
			'title'         => 'Which of the following symptoms...apply to you?',
			'description'   => 'Select all that apply.',
			'type'          => 'multiselect',
			'options'       => array(
				'low_libido'           => 'Low sex drive (libido)',
				'fatigue'              => 'Lack of energy or fatigue',
				'reduced_muscle'       => 'Reduced muscle mass...',
				'increased_fat'        => 'Increase in body fat',
				'erectile_dysfunction' => 'Difficulty with erections',
				'none'                 => 'None of the above',
			),
			'required'      => true,
			'gender_filter' => 'male',
			'scoring'       => array(
				'category' => 'Symptom Severity',
				'weight'   => 3,
				'answers'  => array(
					'low_libido'           => 2,
					'fatigue'              => 2,
					'reduced_muscle'       => 2,
					'increased_fat'        => 2,
					'erectile_dysfunction' => 2,
					'none'                 => 9,
				),
			),
		),
		'testosterone_q2' => array(
			'id'            => 'testosterone_q2',
			'title'         => 'In the last month, have you frequently experienced:',
			'description'   => 'Select all that apply.',
			'type'          => 'multiselect',
			'options'       => array(
				'irritability'     => 'Irritability',
				'low_motivation'   => 'Lack of Motivation',
				'brain_fog'        => '"Brain Fog"',
			),
			'required'      => true,
			'gender_filter' => 'male',
			'scoring'       => array(
				'category' => 'Mood & Cognition',
				'weight'   => 2.5,
				'answers'  => array(
					'irritability'   => 4,
					'low_motivation' => 3,
					'brain_fog'      => 3,
				),
			),
		),
		'testosterone_q3' => array(
			'id'            => 'testosterone_q3',
			'title'         => 'How would you describe your physical endurance or stamina?',
			'type'          => 'radio',
			'options'       => array(
				'decreased'   => 'Decreased significantly',
				'somewhat'    => 'Somewhat decreased',
				'no_change'   => 'Has not changed',
			),
			'required'      => true,
			'gender_filter' => 'male',
			'scoring'       => array(
				'category' => 'Physical Performance',
				'weight'   => 2,
				'answers'  => array(
					'decreased'   => 3,
					'somewhat'    => 5,
					'no_change'   => 8,
				),
			),
		),
		'testosterone_q4' => array(
			'id'            => 'testosterone_q4',
			'title'         => 'How would you describe your ability to build...muscle?',
			'type'          => 'radio',
			'options'       => array(
				'very_difficult'     => 'Very difficult',
				'somewhat_difficult' => 'Somewhat difficult',
				'moderate'           => 'Moderate',
				'easy'               => 'Relatively easy',
			),
			'required'      => true,
			'gender_filter' => 'male',
			'scoring'       => array(
				'category' => 'Anabolic Response',
				'weight'   => 2,
				'answers'  => array(
					'very_difficult'     => 2,
					'somewhat_difficult' => 4,
					'moderate'           => 6,
					'easy'               => 8,
				),
			),
		),
		'testosterone_q5' => array(
			'id'            => 'testosterone_q5',
			'title'         => 'How would you describe your energy levels and motivation?',
			'type'          => 'radio',
			'options'       => array(
				'very_low'         => 'Very low',
				'lower_than_usual' => 'Lower than usual',
				'normal'           => 'Normal',
				'high'             => 'High',
			),
			'required'      => true,
			'gender_filter' => 'male',
			'scoring'       => array(
				'category' => 'Vitality & Drive',
				'weight'   => 2,
				'answers'  => array(
					'very_low'         => 2,
					'lower_than_usual' => 4,
					'normal'           => 7,
					'high'             => 9,
				),
			),
		),
		'testosterone_q6' => array(
			'id'         => 'testosterone_q6',
			'title'      => 'Let\'s get your contact information.',
			'type'       => 'contact_info',
			'required'   => true,
			'global_key' => 'contact_info',
		),
	),

	//
	// Health Optimization (Symptom) Assessment
	//
	'health_optimization_assessment' => array(
		'assessment_engine' => 'qualitative',
		'title' => 'Health Optimization Symptom Checker',
		'questions' => array(
			'symptom_q1' => array( 'title' => 'How have your overall energy levels been feeling lately?', 'type' => 'multiselect', 'options' => array('fatigue' => 'Fatigue', 'chronic_fatigue' => 'Chronic Fatigue'), 'qualifiers' => array( 'fatigue' => array( 'severity' => array('id' => 'fatigue_severity', 'title' => 'Rate your Fatigue', 'type' => 'radio', 'options' => array('Mild' => 'Mild', 'Moderate' => 'Moderate', 'Severe' => 'Severe')), 'frequency' => array('id' => 'fatigue_frequency', 'title' => 'How often?', 'type' => 'radio', 'options' => array('Occasionally' => 'Occasionally', 'Weekly' => 'A few times a week', 'Daily' => 'Daily'))), 'chronic_fatigue' => array( 'severity' => array('id' => 'chronic_fatigue_severity', 'title' => 'Rate your Chronic Fatigue', 'type' => 'radio', 'options' => array('Mild' => 'Mild', 'Moderate' => 'Moderate', 'Severe' => 'Severe')), 'frequency' => array('id' => 'chronic_fatigue_frequency', 'title' => 'How often?', 'type' => 'radio', 'options' => array('Occasionally' => 'Occasionally', 'Weekly' => 'A few times a week', 'Daily' => 'Daily'))), ) ),
			'symptom_q2' => array( 'title' => 'Have you noticed any lack of drive or motivation?', 'type' => 'multiselect', 'options' => array('lack_of_motivation' => 'Lack of Motivation', 'procrastination' => 'Procrastination', 'apathy' => 'Apathy or Indifference'), 'qualifiers' => array( 'lack_of_motivation' => array( 'severity' => array('id' => 'lack_of_motivation_severity', 'title' => 'Rate your Lack of Motivation', 'type' => 'radio', 'options' => array('Mild' => 'Mild', 'Moderate' => 'Moderate', 'Severe' => 'Severe')), 'frequency' => array('id' => 'lack_of_motivation_frequency', 'title' => 'How often?', 'type' => 'radio', 'options' => array('Occasionally' => 'Occasionally', 'Weekly' => 'A few times a week', 'Daily' => 'Daily'))), 'procrastination' => array( 'severity' => array('id' => 'procrastination_severity', 'title' => 'Rate your Procrastination', 'type' => 'radio', 'options' => array('Mild' => 'Mild', 'Moderate' => 'Moderate', 'Severe' => 'Severe')), 'frequency' => array('id' => 'procrastination_frequency', 'title' => 'How often?', 'type' => 'radio', 'options' => array('Occasionally' => 'Occasionally', 'Weekly' => 'A few times a week', 'Daily' => 'Daily'))), 'apathy' => array( 'severity' => array('id' => 'apathy_severity', 'title' => 'Rate your Apathy', 'type' => 'radio', 'options' => array('Mild' => 'Mild', 'Moderate' => 'Moderate', 'Severe' => 'Severe')), 'frequency' => array('id' => 'apathy_frequency', 'title' => 'How often?', 'type' => 'radio', 'options' => array('Occasionally' => 'Occasionally', 'Weekly' => 'A few times a week', 'Daily' => 'Daily'))), ) ),
			'symptom_q3' => array( 'title' => 'Are you finding it harder to stay active or perform physically?', 'type' => 'multiselect', 'options' => array('reduced_performance' => 'Reduced Physical Performance', 'decreased_activity' => 'Decreased Physical Activity'), 'qualifiers' => array( 'reduced_performance' => array( 'severity' => array('id' => 'reduced_performance_severity', 'title' => 'Rate your Reduced Performance', 'type' => 'radio', 'options' => array('Mild' => 'Mild', 'Moderate' => 'Moderate', 'Severe' => 'Severe')), 'frequency' => array('id' => 'reduced_performance_frequency', 'title' => 'How often?', 'type' => 'radio', 'options' => array('Occasionally' => 'Occasionally', 'Weekly' => 'A few times a week', 'Daily' => 'Daily'))), 'decreased_activity' => array( 'severity' => array('id' => 'decreased_activity_severity', 'title' => 'Rate your Decreased Activity', 'type' => 'radio', 'options' => array('Mild' => 'Mild', 'Moderate' => 'Moderate', 'Severe' => 'Severe')), 'frequency' => array('id' => 'decreased_activity_frequency', 'title' => 'How often?', 'type' => 'radio', 'options' => array('Occasionally' => 'Occasionally', 'Weekly' => 'A few times a week', 'Daily' => 'Daily'))), ) ),
			'symptom_q4' => array('title' => 'How\'s your sleep been?', 'type' => 'multiselect', 'options' => array('poor_sleep' => 'Poor Sleep', 'sleep_problems' => 'Sleep Problems', 'sleep_disturbance' => 'Sleep Disturbance')),
			'symptom_q5' => array( 'title' => 'Have you been dealing with any night-time discomforts?', 'type' => 'multiselect', 'options' => array('night_sweats' => 'Night Sweats', 'overheated' => 'Feeling Overheated', 'excessive_sweating' => 'Excessive Sweating'), 'qualifiers' => array( 'night_sweats' => array( 'severity' => array('id' => 'night_sweats_severity', 'title' => 'Rate your Night Sweats', 'type' => 'radio', 'options' => array('Mild' => 'Mild', 'Moderate' => 'Moderate', 'Severe' => 'Severe')), 'frequency' => array('id' => 'night_sweats_frequency', 'title' => 'How often?', 'type' => 'radio', 'options' => array('Occasionally' => 'Occasionally', 'Weekly' => 'A few times a week', 'Daily' => 'Daily'))), 'overheated' => array( 'severity' => array('id' => 'overheated_severity', 'title' => 'Rate your Overheating', 'type' => 'radio', 'options' => array('Mild' => 'Mild', 'Moderate' => 'Moderate', 'Severe' => 'Severe')), 'frequency' => array('id' => 'overheated_frequency', 'title' => 'How often?', 'type' => 'radio', 'options' => array('Occasionally' => 'Occasionally', 'Weekly' => 'A few times a week', 'Daily' => 'Daily'))), 'excessive_sweating' => array( 'severity' => array('id' => 'excessive_sweating_severity', 'title' => 'Rate your Excessive Sweating', 'type' => 'radio', 'options' => array('Mild' => 'Mild', 'Moderate' => 'Moderate', 'Severe' => 'Severe')), 'frequency' => array('id' => 'excessive_sweating_frequency', 'title' => 'How often?', 'type' => 'radio', 'options' => array('Occasionally' => 'Occasionally', 'Weekly' => 'A few times a week', 'Daily' => 'Daily'))), ) ),
			'symptom_q6' => array('title' => 'What about your mood—any ups and downs or changes lately?', 'type' => 'multiselect', 'options' => array('mood_swings' => 'Mood Swings', 'mood_changes' => 'Mood Changes', 'personality_change' => 'Change in Personality')),
			'symptom_q7' => array('title' => 'Are you feeling more anxious, depressed, or irritable?', 'type' => 'multiselect', 'options' => array('anxiety' => 'Anxiety', 'depression' => 'Depression', 'irritability' => 'Irritability')),
			'symptom_q8' => array( 'title' => 'How\'s your self-confidence or esteem been holding up?', 'type' => 'multiselect', 'options' => array('low_self_esteem' => 'Low Self-Esteem', 'negative_self_talk' => 'Negative Self-Talk', 'worthlessness' => 'Feeling of Worthlessness'), 'qualifiers' => array( 'low_self_esteem' => array( 'severity' => array('id' => 'low_self_esteem_severity', 'title' => 'Rate your Low Self-Esteem', 'type' => 'radio', 'options' => array('Mild' => 'Mild', 'Moderate' => 'Moderate', 'Severe' => 'Severe')), 'frequency' => array('id' => 'low_self_esteem_frequency', 'title' => 'How often?', 'type' => 'radio', 'options' => array('Occasionally' => 'Occasionally', 'Weekly' => 'A few times a week', 'Daily' => 'Daily'))), 'negative_self_talk' => array( 'severity' => array('id' => 'negative_self_talk_severity', 'title' => 'Rate your Negative Self-Talk', 'type' => 'radio', 'options' => array('Mild' => 'Mild', 'Moderate' => 'Moderate', 'Severe' => 'Severe')), 'frequency' => array('id' => 'negative_self_talk_frequency', 'title' => 'How often?', 'type' => 'radio', 'options' => array('Occasionally' => 'Occasionally', 'Weekly' => 'A few times a week', 'Daily' => 'Daily'))), 'worthlessness' => array( 'severity' => array('id' => 'worthlessness_severity', 'title' => 'Rate your Feeling of Worthlessness', 'type' => 'radio', 'options' => array('Mild' => 'Mild', 'Moderate' => 'Moderate', 'Severe' => 'Severe')), 'frequency' => array('id' => 'worthlessness_frequency', 'title' => 'How often?', 'type' => 'radio', 'options' => array('Occasionally' => 'Occasionally', 'Weekly' => 'A few times a week', 'Daily' => 'Daily'))), ) ),
			'symptom_q9' => array('title' => 'Have you experienced any fog or confusion in your thinking?', 'type' => 'multiselect', 'options' => array('brain_fog' => 'Brain Fog', 'confusion' => 'Confusion', 'cognitive_decline' => 'Cognitive Decline')),
			'symptom_q10' => array('title' => 'Any trouble with memory or concentration?', 'type' => 'multiselect', 'options' => array('memory_loss' => 'Memory Loss', 'poor_concentration' => 'Poor Concentration')),
			'symptom_q11' => array('title' => 'Have you noticed issues with language or coordination?', 'type' => 'multiselect', 'options' => array('language_problems' => 'Language Problems', 'poor_coordination' => 'Poor Coordination')),
			'symptom_q12' => array( 'title' => 'What about your libido or sexual health—any changes there?', 'type' => 'multiselect', 'options' => array('low_libido' => 'Low Sex Drive', 'decreased_arousal' => 'Decreased Arousal', 'difficulty_orgasm' => 'Difficulty Reaching Orgasm'), 'qualifiers' => array( 'low_libido' => array( 'severity' => array('id' => 'low_libido_severity', 'title' => 'Rate your Low Libido', 'type' => 'radio', 'options' => array('Mild' => 'Mild', 'Moderate' => 'Moderate', 'Severe' => 'Severe')), 'frequency' => array('id' => 'low_libido_frequency', 'title' => 'How often?', 'type' => 'radio', 'options' => array('Occasionally' => 'Occasionally', 'Weekly' => 'A few times a week', 'Daily' => 'Daily'))), 'decreased_arousal' => array( 'severity' => array('id' => 'decreased_arousal_severity', 'title' => 'Rate your Decreased Arousal', 'type' => 'radio', 'options' => array('Mild' => 'Mild', 'Moderate' => 'Moderate', 'Severe' => 'Severe')), 'frequency' => array('id' => 'decreased_arousal_frequency', 'title' => 'How often?', 'type' => 'radio', 'options' => array('Occasionally' => 'Occasionally', 'Weekly' => 'A few times a week', 'Daily' => 'Daily'))), 'difficulty_orgasm' => array( 'severity' => array('id' => 'difficulty_orgasm_severity', 'title' => 'Rate your Difficulty Reaching Orgasm', 'type' => 'radio', 'options' => array('Mild' => 'Mild', 'Moderate' => 'Moderate', 'Severe' => 'Severe')), 'frequency' => array('id' => 'difficulty_orgasm_frequency', 'title' => 'How often?', 'type' => 'radio', 'options' => array('Occasionally' => 'Occasionally', 'Weekly' => 'A few times a week', 'Daily' => 'Daily'))), ) ),
			'symptom_q13' => array('title' => 'Are you experiencing any sexual function difficulties?', 'type' => 'multiselect', 'options' => array('erectile_dysfunction' => 'Erectile Dysfunction', 'vaginal_dryness' => 'Vaginal Dryness', 'infertility' => 'Infertility')),
			'symptom_q14' => array( 'title' => 'Have you had any hot flashes or similar sensations?', 'type' => 'multiselect', 'options' => array('hot_flashes' => 'Hot Flashes', 'sudden_chills' => 'Sudden Chills', 'facial_flushing' => 'Facial Flushing'), 'qualifiers' => array( 'hot_flashes' => array( 'severity' => array('id' => 'hot_flashes_severity', 'title' => 'Rate your Hot Flashes', 'type' => 'radio', 'options' => array('Mild' => 'Mild', 'Moderate' => 'Moderate', 'Severe' => 'Severe')), 'frequency' => array('id' => 'hot_flashes_frequency', 'title' => 'How often?', 'type' => 'radio', 'options' => array('Occasionally' => 'Occasionally', 'Weekly' => 'A few times a week', 'Daily' => 'Daily'))), 'sudden_chills' => array( 'severity' => array('id' => 'sudden_chills_severity', 'title' => 'Rate your Sudden Chills', 'type' => 'radio', 'options' => array('Mild' => 'Mild', 'Moderate' => 'Moderate', 'Severe' => 'Severe')), 'frequency' => array('id' => 'sudden_chills_frequency', 'title' => 'How often?', 'type' => 'radio', 'options' => array('Occasionally' => 'Occasionally', 'Weekly' => 'A few times a week', 'Daily' => 'Daily'))), 'facial_flushing' => array( 'severity' => array('id' => 'facial_flushing_severity', 'title' => 'Rate your Facial Flushing', 'type' => 'radio', 'options' => array('Mild' => 'Mild', 'Moderate' => 'Moderate', 'Severe' => 'Severe')), 'frequency' => array('id' => 'facial_flushing_frequency', 'title' => 'How often?', 'type' => 'radio', 'options' => array('Occasionally' => 'Occasionally', 'Weekly' => 'A few times a week', 'Daily' => 'Daily'))), ) ),
			'symptom_q15' => array('title' => 'Let\'s talk about physical strength—any weakness or loss of muscle?', 'type' => 'multiselect', 'options' => array('muscle_weakness' => 'Muscle Weakness', 'weakness' => 'Weakness', 'muscle_loss' => 'Muscle Loss', 'muscle_mass_loss' => 'Muscle Mass Loss')),
			'symptom_q16' => array('title' => 'How\'s your mobility and balance been?', 'type' => 'multiselect', 'options' => array('decreased_mobility' => 'Decreased Mobility', 'poor_balance' => 'Poor Balance')),
			'symptom_q17' => array('title' => 'After activity, do you find recovery taking longer?', 'type' => 'multiselect', 'options' => array('slow_recovery' => 'Slow Recovery', 'prolonged_soreness' => 'Prolonged Soreness')),
			'symptom_q18' => array( 'title' => 'Any joint pain or related discomforts?', 'type' => 'multiselect', 'options' => array('joint_pain' => 'Joint Pain', 'joint_stiffness' => 'Joint Stiffness', 'muscle_aches' => 'Muscle Aches'), 'qualifiers' => array( 'joint_pain' => array( 'severity' => array('id' => 'joint_pain_severity', 'title' => 'Rate your Joint Pain', 'type' => 'radio', 'options' => array('Mild' => 'Mild', 'Moderate' => 'Moderate', 'Severe' => 'Severe')), 'frequency' => array('id' => 'joint_pain_frequency', 'title' => 'How often?', 'type' => 'radio', 'options' => array('Occasionally' => 'Occasionally', 'Weekly' => 'A few times a week', 'Daily' => 'Daily'))), 'joint_stiffness' => array( 'severity' => array('id' => 'joint_stiffness_severity', 'title' => 'Rate your Joint Stiffness', 'type' => 'radio', 'options' => array('Mild' => 'Mild', 'Moderate' => 'Moderate', 'Severe' => 'Severe')), 'frequency' => array('id' => 'joint_stiffness_frequency', 'title' => 'How often?', 'type' => 'radio', 'options' => array('Occasionally' => 'Occasionally', 'Weekly' => 'A few times a week', 'Daily' => 'Daily'))), 'muscle_aches' => array( 'severity' => array('id' => 'muscle_aches_severity', 'title' => 'Rate your Muscle Aches', 'type' => 'radio', 'options' => array('Mild' => 'Mild', 'Moderate' => 'Moderate', 'Severe' => 'Severe')), 'frequency' => array('id' => 'muscle_aches_frequency', 'title' => 'How often?', 'type' => 'radio', 'options' => array('Occasionally' => 'Occasionally', 'Weekly' => 'A few times a week', 'Daily' => 'Daily'))), ) ),
			'symptom_q19' => array('title' => 'On the heart side, have you felt any chest pain or shortness of breath?', 'type' => 'multiselect', 'options' => array('chest_pain' => 'Chest Pain', 'shortness_of_breath' => 'Shortness of Breath')),
			'symptom_q20' => array('title' => 'What about palpitations, lightheadedness, or swelling?', 'type' => 'multiselect', 'options' => array('palpitations' => 'Palpitations', 'lightheadedness' => 'Lightheadedness', 'swelling' => 'Swelling')),
			'symptom_q21' => array( 'title' => 'How\'s your exercise tolerance—any issues pushing yourself?', 'type' => 'multiselect', 'options' => array('poor_exercise_tolerance' => 'Poor Exercise Tolerance', 'out_of_breath_easily' => 'Out of Breath Easily', 'fatigue_after_exertion' => 'Fatigue After Minimal Exertion'), 'qualifiers' => array( 'poor_exercise_tolerance' => array( 'severity' => array('id' => 'poor_exercise_tolerance_severity', 'title' => 'Rate your Exercise Tolerance', 'type' => 'radio', 'options' => array('Mild' => 'Mild', 'Moderate' => 'Moderate', 'Severe' => 'Severe')), 'frequency' => array('id' => 'poor_exercise_tolerance_frequency', 'title' => 'How often?', 'type' => 'radio', 'options' => array('Occasionally' => 'Occasionally', 'Weekly' => 'A few times a week', 'Daily' => 'Daily'))), 'out_of_breath_easily' => array( 'severity' => array('id' => 'out_of_breath_easily_severity', 'title' => 'Rate your Breathlessness', 'type' => 'radio', 'options' => array('Mild' => 'Mild', 'Moderate' => 'Moderate', 'Severe' => 'Severe')), 'frequency' => array('id' => 'out_of_breath_easily_frequency', 'title' => 'How often?', 'type' => 'radio', 'options' => array('Occasionally' => 'Occasionally', 'Weekly' => 'A few times a week', 'Daily' => 'Daily'))), 'fatigue_after_exertion' => array( 'severity' => array('id' => 'fatigue_after_exertion_severity', 'title' => 'Rate your Post-Exertion Fatigue', 'type' => 'radio', 'options' => array('Mild' => 'Mild', 'Moderate' => 'Moderate', 'Severe' => 'Severe')), 'frequency' => array('id' => 'fatigue_after_exertion_frequency', 'title' => 'How often?', 'type' => 'radio', 'options' => array('Occasionally' => 'Occasionally', 'Weekly' => 'A few times a week', 'Daily' => 'Daily'))), ) ),
			'symptom_q22' => array( 'title' => 'Have you noticed changes in your blood pressure?', 'type' => 'multiselect', 'options' => array('known_high_bp' => 'Known High Blood Pressure', 'dizziness' => 'Dizziness', 'frequent_headaches' => 'Frequent Headaches'), 'qualifiers' => array( 'dizziness' => array( 'severity' => array('id' => 'dizziness_severity', 'title' => 'Rate your Dizziness', 'type' => 'radio', 'options' => array('Mild' => 'Mild', 'Moderate' => 'Moderate', 'Severe' => 'Severe')), 'frequency' => array('id' => 'dizziness_frequency', 'title' => 'How often?', 'type' => 'radio', 'options' => array('Occasionally' => 'Occasionally', 'Weekly' => 'A few times a week', 'Daily' => 'Daily'))), 'frequent_headaches' => array( 'severity' => array('id' => 'frequent_headaches_severity', 'title' => 'Rate your Headaches', 'type' => 'radio', 'options' => array('Mild' => 'Mild', 'Moderate' => 'Moderate', 'Severe' => 'Severe')), 'frequency' => array('id' => 'frequent_headaches_frequency', 'title' => 'How often?', 'type' => 'radio', 'options' => array('Occasionally' => 'Occasionally', 'Weekly' => 'A few times a week', 'Daily' => 'Daily'))), ) ),
			'symptom_q23' => array('title' => 'Let\'s check on body composition—any increases in fat?', 'type' => 'multiselect', 'options' => array('increased_body_fat' => 'Increased Body Fat', 'abdominal_fat_gain' => 'Abdominal Fat Gain', 'weight_changes' => 'Weight Changes')),
			'symptom_q24' => array('title' => 'Is your metabolism feeling slower, or any blood sugar irregularities?', 'type' => 'multiselect', 'options' => array('slow_metabolism' => 'Slow Metabolism', 'blood_glucose_dysregulation' => 'Blood Glucose Dysregulation')),
			'symptom_q25' => array('title' => 'Finally, have you been getting sick more often, or noticing skin issues?', 'type' => 'multiselect', 'options' => array('frequent_illness' => 'Frequent Illness', 'itchy_skin' => 'Itchy Skin', 'slow_healing_wounds' => 'Slow Healing Wounds')),
			'symptom_q26' => array( 'id' => 'symptom_q26', 'title' => 'Let\'s get your contact information.', 'type' => 'contact_info', 'required' => true, 'global_key' => 'contact_info' ),
		),
	),

);
