<?php
/**
 * Assessment Definition: Health Optimization Assessment
 * Enhanced by Dr. Victor Pulse (Cardiology Master)
 * Evidence-based cardiology implementation
 *
 * @package ENNU_Life
 * @version 62.11.0
 */

return array(
	'title'             => 'Health Optimization Assessment',
	'assessment_engine' => 'qualitative',
	'questions'         => array(
		'health_q_gender'      => array(
			'title'      => 'What is your gender?',
			'type'       => 'radio',
			'options'    => array(
				'female' => 'FEMALE',
				'male'   => 'MALE',
			),
			'required'   => true,
			'global_key' => 'gender',
		),
		'health_opt_q_dob'    => array(
			'title'      => 'What is your date of birth?',
			'type'       => 'dob_dropdowns',
			'required'   => true,
			'global_key' => 'date_of_birth',
			'scoring'    => array(
				'category' => 'Age Factors',
				'weight'   => 1.5,
				'calculation' => 'age_from_dob',
				'age_scores' => array(
					'18-25' => 8,
					'26-35' => 7,
					'36-45' => 6,
					'46-55' => 4,
					'56-65' => 3,
					'66-75' => 2,
					'76+'   => 1,
				),
			),
		),
		'health_opt_q_height_weight' => array(
			'title'      => 'What is your height and weight?',
			'type'       => 'height_weight',
			'required'   => true,
			'global_key' => 'height_weight',
		),
'symptom_q1'           => array(
			'title'    => 'Please select any symptoms you are experiencing related to Heart Health.',
			'type'     => 'multiselect',
			'options'  => array(
				'chest_pain'              => 'Chest Pain or Discomfort',
				'shortness_breath'        => 'Shortness of Breath',
				'palpitations'            => 'Heart Palpitations or Irregular Heartbeat',
				'lightheadedness'         => 'Lightheadedness or Dizziness',
				'swelling'                => 'Swelling in Legs, Ankles, or Feet',
				'poor_exercise_tolerance' => 'Poor Exercise Tolerance',
				'fatigue'                 => 'Unexplained Fatigue',
				'nausea'                  => 'Nausea or Indigestion',
				'sweating'                => 'Cold Sweats',
				'none'                    => 'None of the above',
			),
			'scoring'  => array(
				'category' => 'Cardiovascular Symptoms',
				'weight'   => 3,
				'answers'  => array(
					'chest_pain'              => 2,
					'shortness_breath'        => 2,
					'palpitations'            => 3,
					'lightheadedness'         => 3,
					'swelling'                => 2,
					'poor_exercise_tolerance' => 3,
					'fatigue'                 => 4,
					'nausea'                  => 3,
					'sweating'                => 2,
					'none'                    => 8,
				),
			),
			'required' => false,
		),
		'symptom_q1_severity'  => array(
			'title'    => 'How severe are your Heart Health symptoms?',
			'type'     => 'radio',
			'options'  => array(
				'none'     => 'None',
				'mild'     => 'Mild - Noticeable but not interfering with daily activities',
				'moderate' => 'Moderate - Some interference with daily activities',
				'severe'   => 'Severe - Significant interference with daily activities',
			),
			'scoring'  => array(
				'category' => 'Symptom Severity',
				'weight'   => 2.5,
				'answers'  => array(
					'none'     => 8,
					'mild'     => 6,
					'moderate' => 4,
					'severe'   => 2,
				),
			),
			'required' => false,
		),
		'symptom_q1_frequency' => array(
			'title'    => 'How often do you experience these symptoms?',
			'type'     => 'radio',
			'options'  => array(
				'never'   => 'Never',
				'rarely'  => 'Rarely (few times per year)',
				'monthly' => 'Monthly',
				'weekly'  => 'Weekly',
				'daily'   => 'Daily',
			),
			'scoring'  => array(
				'category' => 'Symptom Frequency',
				'weight'   => 2,
				'answers'  => array(
					'never'   => 8,
					'rarely'  => 7,
					'monthly' => 5,
					'weekly'  => 3,
					'daily'   => 2,
				),
			),
			'required' => false,
		),
		'symptom_q2'           => array(
			'title'    => 'Please select any symptoms you are experiencing related to Cognitive Health.',
			'type'     => 'multiselect',
			'options'  => array(
				'brain_fog'          => 'Brain Fog or Mental Clarity Issues',
				'memory_loss'        => 'Memory Loss or Forgetfulness',
				'poor_concentration' => 'Poor Concentration or Focus',
				'mental_fatigue'     => 'Mental Fatigue',
				'mood_changes'       => 'Mood Changes or Irritability',
				'sleep_issues'       => 'Sleep Issues',
				'none'               => 'None of the above',
			),
			'scoring'  => array(
				'category' => 'Cognitive Symptoms',
				'weight'   => 2.5,
				'answers'  => array(
					'brain_fog'          => 3,
					'memory_loss'        => 2,
					'poor_concentration' => 3,
					'mental_fatigue'     => 4,
					'mood_changes'       => 4,
					'sleep_issues'       => 4,
					'none'               => 8,
				),
			),
			'required' => false,
		),
		'symptom_q2_severity'  => array(
			'title'    => 'How severe are your Cognitive Health symptoms?',
			'type'     => 'radio',
			'options'  => array(
				'none'     => 'None',
				'mild'     => 'Mild - Noticeable but not interfering with daily activities',
				'moderate' => 'Moderate - Some interference with daily activities',
				'severe'   => 'Severe - Significant interference with daily activities',
			),
			'scoring'  => array(
				'category' => 'Symptom Severity',
				'weight'   => 2,
				'answers'  => array(
					'none'     => 8,
					'mild'     => 6,
					'moderate' => 4,
					'severe'   => 2,
				),
			),
			'required' => false,
		),
		'symptom_q2_frequency' => array(
			'title'    => 'How often do you experience these symptoms?',
			'type'     => 'radio',
			'options'  => array(
				'never'   => 'Never',
				'rarely'  => 'Rarely (few times per year)',
				'monthly' => 'Monthly',
				'weekly'  => 'Weekly',
				'daily'   => 'Daily',
			),
			'scoring'  => array(
				'category' => 'Symptom Frequency',
				'weight'   => 1.5,
				'answers'  => array(
					'never'   => 8,
					'rarely'  => 7,
					'monthly' => 5,
					'weekly'  => 3,
					'daily'   => 2,
				),
			),
			'required' => false,
		),
		'symptom_q3'           => array(
			'title'    => 'Please select any symptoms you are experiencing related to Metabolic Health.',
			'type'     => 'multiselect',
			'options'  => array(
				'weight_gain'    => 'Unexplained Weight Gain',
				'fatigue'        => 'Chronic Fatigue',
				'thirst'         => 'Increased Thirst or Frequent Urination',
				'slow_healing'   => 'Slow Wound Healing',
				'blurred_vision' => 'Blurred Vision',
				'numbness'       => 'Numbness or Tingling in Extremities',
				'none'           => 'None of the above',
			),
			'scoring'  => array(
				'category' => 'Metabolic Symptoms',
				'weight'   => 2.5,
				'answers'  => array(
					'weight_gain'    => 3,
					'fatigue'        => 4,
					'thirst'         => 2,
					'slow_healing'   => 3,
					'blurred_vision' => 2,
					'numbness'       => 2,
					'none'           => 8,
				),
			),
			'required' => false,
		),
		'symptom_q3_severity'  => array(
			'title'    => 'How severe are your Metabolic Health symptoms?',
			'type'     => 'radio',
			'options'  => array(
				'none'     => 'None',
				'mild'     => 'Mild - Noticeable but not interfering with daily activities',
				'moderate' => 'Moderate - Some interference with daily activities',
				'severe'   => 'Severe - Significant interference with daily activities',
			),
			'scoring'  => array(
				'category' => 'Symptom Severity',
				'weight'   => 2,
				'answers'  => array(
					'none'     => 8,
					'mild'     => 6,
					'moderate' => 4,
					'severe'   => 2,
				),
			),
			'required' => false,
		),
		'symptom_q3_frequency' => array(
			'title'    => 'How often do you experience these symptoms?',
			'type'     => 'radio',
			'options'  => array(
				'never'   => 'Never',
				'rarely'  => 'Rarely (few times per year)',
				'monthly' => 'Monthly',
				'weekly'  => 'Weekly',
				'daily'   => 'Daily',
			),
			'scoring'  => array(
				'category' => 'Symptom Frequency',
				'weight'   => 1.5,
				'answers'  => array(
					'never'   => 8,
					'rarely'  => 7,
					'monthly' => 5,
					'weekly'  => 3,
					'daily'   => 2,
				),
			),
			'required' => false,
		),
		'symptom_q4'           => array(
			'title'    => 'Please select any symptoms you are experiencing related to Immune Health.',
			'type'     => 'multiselect',
			'options'  => array(
				'frequent_illness' => 'Frequent Illness or Infections',
				'slow_recovery'    => 'Slow Recovery from Illness',
				'allergies'        => 'Allergies or Sensitivities',
				'inflammation'     => 'Chronic Inflammation or Pain',
				'autoimmune'       => 'Autoimmune Symptoms',
				'none'             => 'None of the above',
			),
			'scoring'  => array(
				'category' => 'Immune Symptoms',
				'weight'   => 2,
				'answers'  => array(
					'frequent_illness' => 2,
					'slow_recovery'    => 3,
					'allergies'        => 4,
					'inflammation'     => 3,
					'autoimmune'       => 2,
					'none'             => 8,
				),
			),
			'required' => false,
		),
		'symptom_q4_severity'  => array(
			'title'    => 'How severe are your Immune Health symptoms?',
			'type'     => 'radio',
			'options'  => array(
				'none'     => 'None',
				'mild'     => 'Mild - Noticeable but not interfering with daily activities',
				'moderate' => 'Moderate - Some interference with daily activities',
				'severe'   => 'Severe - Significant interference with daily activities',
			),
			'scoring'  => array(
				'category' => 'Symptom Severity',
				'weight'   => 1.5,
				'answers'  => array(
					'none'     => 8,
					'mild'     => 6,
					'moderate' => 4,
					'severe'   => 2,
				),
			),
			'required' => false,
		),
		'symptom_q4_frequency' => array(
			'title'    => 'How often do you experience these symptoms?',
			'type'     => 'radio',
			'options'  => array(
				'never'   => 'Never',
				'rarely'  => 'Rarely (few times per year)',
				'monthly' => 'Monthly',
				'weekly'  => 'Weekly',
				'daily'   => 'Daily',
			),
			'scoring'  => array(
				'category' => 'Symptom Frequency',
				'weight'   => 1.5,
				'answers'  => array(
					'never'   => 8,
					'rarely'  => 7,
					'monthly' => 5,
					'weekly'  => 3,
					'daily'   => 2,
				),
			),
			'required' => false,
		),
		'medical_history_q1' => array(
			'title' => 'Do you have any of the following medical conditions?',
			'type' => 'multiselect',
			'options' => array(
				'diabetes' => 'Diabetes (Type 1 or Type 2)',
				'hypertension' => 'High Blood Pressure',
				'heart_disease' => 'Heart Disease',
				'thyroid_disorder' => 'Thyroid Disorder',
				'autoimmune' => 'Autoimmune Disease',
				'cancer' => 'Cancer (current or history)',
				'depression' => 'Depression or Anxiety',
				'sleep_apnea' => 'Sleep Apnea',
				'kidney_disease' => 'Kidney Disease',
				'liver_disease' => 'Liver Disease',
				'none' => 'None of the above'
			),
			'scoring' => array(
				'category' => 'Medical Risk Factors',
				'weight' => 4,
				'answers' => array(
					'diabetes' => 2,
					'hypertension' => 2,
					'heart_disease' => 1,
					'thyroid_disorder' => 3,
					'autoimmune' => 2,
					'cancer' => 1,
					'depression' => 3,
					'sleep_apnea' => 2,
					'kidney_disease' => 1,
					'liver_disease' => 1,
					'none' => 8,
				),
			),
			'medical_alerts' => array(
				'diabetes' => 'Requires careful blood sugar monitoring',
				'hypertension' => 'Blood pressure monitoring recommended',
				'heart_disease' => 'Cardiac clearance may be required',
				'cancer' => 'Oncologist consultation recommended',
			),
			'required' => false,
		),
		'medication_q1' => array(
			'title' => 'Are you currently taking any medications?',
			'type' => 'multiselect',
			'options' => array(
				'blood_pressure_meds' => 'Blood Pressure Medications',
				'diabetes_meds' => 'Diabetes Medications',
				'thyroid_meds' => 'Thyroid Medications',
				'antidepressants' => 'Antidepressants',
				'hormone_therapy' => 'Hormone Therapy',
				'blood_thinners' => 'Blood Thinners (Warfarin, etc.)',
				'statins' => 'Cholesterol Medications (Statins)',
				'pain_meds' => 'Pain Medications',
				'sleep_meds' => 'Sleep Medications',
				'none' => 'No medications'
			),
			'interaction_warnings' => array(
				'blood_pressure_meds' => array(
					'message' => 'May interact with certain supplements',
					'severity' => 'moderate',
					'recommendations' => array('Monitor blood pressure closely', 'Consult healthcare provider')
				),
				'diabetes_meds' => array(
					'message' => 'Requires careful monitoring with weight loss',
					'severity' => 'high',
					'recommendations' => array('Monitor blood sugar frequently', 'Adjust medication as needed')
				),
				'thyroid_meds' => array(
					'message' => 'May affect hormone optimization',
					'severity' => 'moderate',
					'recommendations' => array('Monitor thyroid function', 'Adjust timing of supplements')
				),
				'blood_thinners' => array(
					'message' => 'High risk of interactions',
					'severity' => 'critical',
					'recommendations' => array('Consult healthcare provider before any changes', 'Monitor INR levels')
				),
			),
			'scoring' => array(
				'category' => 'Medication Risk Factors',
				'weight' => 3.5,
				'answers' => array(
					'blood_pressure_meds' => 3,
					'diabetes_meds' => 2,
					'thyroid_meds' => 4,
					'antidepressants' => 3,
					'hormone_therapy' => 4,
					'blood_thinners' => 1,
					'statins' => 3,
					'pain_meds' => 3,
					'sleep_meds' => 3,
					'none' => 8,
				),
			),
			'required' => false,
		),
		'lifestyle_q1' => array(
			'title' => 'Which of the following lifestyle factors apply to you?',
			'type' => 'multiselect',
			'options' => array(
				'sedentary_job' => 'Sedentary job (sitting most of the day)',
				'high_stress' => 'High stress levels',
				'poor_sleep' => 'Consistently poor sleep quality',
				'smoking' => 'Current or former smoker',
				'excessive_alcohol' => 'Excessive alcohol consumption',
				'poor_diet' => 'Poor dietary habits',
				'irregular_exercise' => 'Irregular exercise routine',
				'shift_work' => 'Shift work or irregular schedule',
				'travel_frequent' => 'Frequent travel',
				'environmental_toxins' => 'Exposure to environmental toxins',
				'none' => 'None of the above'
			),
			'scoring' => array(
				'category' => 'Lifestyle Risk Factors',
				'weight' => 2,
				'answers' => array(
					'sedentary_job' => 4,
					'high_stress' => 3,
					'poor_sleep' => 3,
					'smoking' => 2,
					'excessive_alcohol' => 2,
					'poor_diet' => 3,
					'irregular_exercise' => 3,
					'shift_work' => 2,
					'travel_frequent' => 2,
					'environmental_toxins' => 2,
					'none' => 8,
				),
			),
			'lifestyle_recommendations' => array(
				'sedentary_job' => array('Standing desk', 'Regular movement breaks', 'Exercise routine'),
				'high_stress' => array('Stress management techniques', 'Mindfulness practices', 'Work-life balance'),
				'poor_sleep' => array('Sleep hygiene', 'Bedtime routine', 'Sleep environment optimization'),
				'smoking' => array('Smoking cessation support', 'Nicotine replacement', 'Behavioral therapy'),
				'excessive_alcohol' => array('Alcohol reduction strategies', 'Alternative social activities', 'Support groups'),
			),
			'required' => false,
		),
	),
);
