<?php
/**
 * Assessment Definition: Hormone Assessment
 * Enhanced by Dr. Elena Harmonix (Endocrinology Master)
 * Evidence-based endocrinology implementation
 *
 * @package ENNU_Life
 * @version 62.3.1
 */

return array(
    'title' => 'Hormone Assessment',
    'assessment_engine' => 'quantitative',
    'questions' => array(
        'hormone_q_gender' => array(
            'title' => 'What is your gender?',
            'type' => 'radio',
            'options' => array(
                'male' => 'Male',
                'female' => 'Female',
                'other' => 'Other / Prefer not to say',
            ),
            'required' => true,
            'global_key' => 'gender'
        ),
        'hormone_q_age' => array(
            'title' => 'What is your age?',
            'type' => 'radio',
            'options' => array(
                'under_25' => 'Under 25',
                '25_35' => '25-35',
                '36_45' => '36-45',
                '46_55' => '46-55',
                'over_55' => 'Over 55',
            ),
            'scoring' => array(
                'category' => 'Age Factors',
                'weight' => 1.5,
                'answers' => array(
                    'under_25' => 5,
                    '25_35' => 4,
                    '36_45' => 3,
                    '46_55' => 2,
                    'over_55' => 1,
                ),
            ),
            'required' => true,
        ),
        'hormone_q1' => array(
            'title' => 'Which of the following symptoms of hormonal imbalance are you experiencing?',
            'type' => 'multiselect',
            'options' => array(
                'fatigue' => 'Unexplained fatigue or energy loss',
                'mood_swings' => 'Mood swings, irritability, or anxiety',
                'weight_gain' => 'Unexplained weight gain, especially abdominal',
                'low_libido' => 'Low libido or sexual dysfunction',
                'sleep_issues' => 'Difficulty sleeping or night sweats',
                'brain_fog' => 'Brain fog or difficulty concentrating',
                'hot_flashes' => 'Hot flashes or temperature sensitivity',
                'hair_loss' => 'Hair loss or thinning',
                'skin_changes' => 'Skin changes (dryness, acne, aging)',
                'heart_palpitations' => 'Heart palpitations or irregular heartbeat',
                'digestive_issues' => 'Digestive issues or bloating',
                'joint_pain' => 'Joint pain or muscle weakness',
                'memory_problems' => 'Memory problems or forgetfulness',
                'depression' => 'Depression or low mood',
                'none' => 'None of the above',
            ),
            'scoring' => array(
                'category' => 'Symptom Severity',
                'weight' => 3,
                'answers' => array(
                    'fatigue' => 2,
                    'mood_swings' => 2,
                    'weight_gain' => 1,
                    'low_libido' => 2,
                    'sleep_issues' => 2,
                    'brain_fog' => 2,
                    'hot_flashes' => 1,
                    'hair_loss' => 1,
                    'skin_changes' => 2,
                    'heart_palpitations' => 1,
                    'digestive_issues' => 2,
                    'joint_pain' => 1,
                    'memory_problems' => 2,
                    'depression' => 1,
                    'none' => 5,
                ),
            ),
            'required' => true,
        ),
        'hormone_q2' => array(
            'title' => 'How would you rate your daily stress levels?',
            'type' => 'radio',
            'options' => array(
                'low' => 'Low - I rarely feel stressed',
                'moderate' => 'Moderate - I experience some stress but manage it well',
                'high' => 'High - I frequently feel stressed and overwhelmed',
                'very_high' => 'Very High - I feel constantly stressed and struggle to cope',
            ),
            'scoring' => array(
                'category' => 'Stress & Cortisol',
                'weight' => 2.5,
                'answers' => array(
                    'low' => 9,
                    'moderate' => 7,
                    'high' => 4,
                    'very_high' => 2,
                ),
            ),
            'required' => true,
        ),
        'hormone_q3' => array(
            'title' => 'How would you describe your energy levels throughout the day?',
            'type' => 'radio',
            'options' => array(
                'high_consistent' => 'High and consistent throughout the day',
                'moderate_consistent' => 'Moderate and consistent',
                'morning_high' => 'High in morning, lower in afternoon',
                'afternoon_crash' => 'Good in morning, crash in afternoon',
                'consistently_low' => 'Consistently low throughout the day',
            ),
            'scoring' => array(
                'category' => 'Energy Patterns',
                'weight' => 2,
                'answers' => array(
                    'high_consistent' => 9,
                    'moderate_consistent' => 7,
                    'morning_high' => 5,
                    'afternoon_crash' => 3,
                    'consistently_low' => 2,
                ),
            ),
            'required' => true,
        ),
        'hormone_q4' => array(
            'title' => 'How would you describe your ability to focus and concentrate?',
            'type' => 'radio',
            'options' => array(
                'excellent' => 'Excellent - No issues with focus',
                'good' => 'Good - Minor focus issues',
                'moderate' => 'Moderate - Some difficulty concentrating',
                'poor' => 'Poor - Significant focus problems',
                'very_poor' => 'Very Poor - Severe concentration issues',
            ),
            'scoring' => array(
                'category' => 'Cognitive Function',
                'weight' => 2,
                'answers' => array(
                    'excellent' => 9,
                    'good' => 7,
                    'moderate' => 5,
                    'poor' => 3,
                    'very_poor' => 2,
                ),
            ),
            'required' => true,
        ),
        'hormone_q5' => array(
            'title' => 'How many servings of cruciferous vegetables do you eat per week?',
            'type' => 'radio',
            'options' => array(
                '0_1' => '0-1 servings',
                '2_3' => '2-3 servings',
                '4_6' => '4-6 servings',
                '7_10' => '7-10 servings',
                'more_than_10' => 'More than 10 servings',
            ),
            'scoring' => array(
                'category' => 'Diet & Nutrition',
                'weight' => 1.5,
                'answers' => array(
                    '0_1' => 3,
                    '2_3' => 5,
                    '4_6' => 7,
                    '7_10' => 8,
                    'more_than_10' => 9,
                ),
            ),
            'required' => true,
        ),
        'hormone_q6' => array(
            'title' => 'Are you currently taking any medications that could affect hormones?',
            'type' => 'multiselect',
            'options' => array(
                'none' => 'None',
                'birth_control' => 'Birth control pills or hormonal contraceptives',
                'thyroid_meds' => 'Thyroid medications',
                'diabetes_meds' => 'Diabetes medications',
                'steroids' => 'Corticosteroids or steroids',
                'antidepressants' => 'Antidepressants',
                'hrt' => 'Hormone replacement therapy (HRT)',
                'testosterone' => 'Testosterone therapy',
                'other' => 'Other medications',
            ),
            'scoring' => array(
                'category' => 'Medication Impact',
                'weight' => 2,
                'answers' => array(
                    'none' => 9,
                    'birth_control' => 6,
                    'thyroid_meds' => 5,
                    'diabetes_meds' => 4,
                    'steroids' => 3,
                    'antidepressants' => 6,
                    'hrt' => 5,
                    'testosterone' => 5,
                    'other' => 4,
                ),
            ),
            'required' => true,
        ),
        'hormone_q7' => array(
            'title' => 'Do you have a family history of hormonal disorders?',
            'type' => 'multiselect',
            'options' => array(
                'none' => 'None known',
                'diabetes' => 'Diabetes (Type 1 or Type 2)',
                'thyroid' => 'Thyroid disorders (hypothyroidism, hyperthyroidism)',
                'pcos' => 'Polycystic Ovary Syndrome (PCOS)',
                'menopause_early' => 'Early menopause',
                'infertility' => 'Infertility issues',
                'adrenal' => 'Adrenal disorders',
                'pituitary' => 'Pituitary disorders',
                'other' => 'Other hormonal disorders',
            ),
            'scoring' => array(
                'category' => 'Family History',
                'weight' => 1.5,
                'answers' => array(
                    'none' => 9,
                    'diabetes' => 4,
                    'thyroid' => 5,
                    'pcos' => 4,
                    'menopause_early' => 5,
                    'infertility' => 6,
                    'adrenal' => 3,
                    'pituitary' => 3,
                    'other' => 4,
                ),
            ),
            'required' => true,
        ),
        'hormone_q8' => array(
            'title' => 'Have you had any recent blood tests for hormone levels?',
            'type' => 'radio',
            'options' => array(
                'none' => 'No recent tests',
                'basic' => 'Basic hormone panel',
                'comprehensive' => 'Comprehensive hormone panel',
                'specific' => 'Specific hormone tests (thyroid, testosterone, etc.)',
                'regular' => 'Regular monitoring',
            ),
            'scoring' => array(
                'category' => 'Biomarker Monitoring',
                'weight' => 1.5,
                'answers' => array(
                    'none' => 5,
                    'basic' => 6,
                    'comprehensive' => 8,
                    'specific' => 7,
                    'regular' => 9,
                ),
            ),
            'required' => true,
        ),
        'hormone_q9' => array(
            'title' => 'Which of the following lifestyle factors apply to you?',
            'type' => 'multiselect',
            'options' => array(
                'regular_exercise' => 'Regular exercise (3+ times per week)',
                'adequate_sleep' => 'Adequate sleep (7-9 hours per night)',
                'stress_management' => 'Stress management practices',
                'healthy_diet' => 'Healthy, balanced diet',
                'smoking' => 'Smoking or tobacco use',
                'excessive_alcohol' => 'Excessive alcohol consumption',
                'sedentary' => 'Sedentary lifestyle',
                'poor_sleep' => 'Poor sleep habits',
                'high_stress' => 'High stress lifestyle',
                'none' => 'None of the above',
            ),
            'scoring' => array(
                'category' => 'Lifestyle Factors',
                'weight' => 2,
                'answers' => array(
                    'regular_exercise' => 8,
                    'adequate_sleep' => 8,
                    'stress_management' => 7,
                    'healthy_diet' => 8,
                    'smoking' => 2,
                    'excessive_alcohol' => 3,
                    'sedentary' => 3,
                    'poor_sleep' => 3,
                    'high_stress' => 3,
                    'none' => 5,
                ),
            ),
            'required' => true,
        ),
        'hormone_q10' => array(
            'title' => 'How would you rate your overall hormonal health?',
            'type' => 'radio',
            'options' => array(
                'excellent' => 'Excellent - No hormonal issues',
                'good' => 'Good - Minor hormonal fluctuations',
                'moderate' => 'Moderate - Some hormonal symptoms',
                'poor' => 'Poor - Significant hormonal issues',
                'very_poor' => 'Very Poor - Severe hormonal problems',
            ),
            'scoring' => array(
                'category' => 'Self-Assessment',
                'weight' => 1.5,
                'answers' => array(
                    'excellent' => 9,
                    'good' => 7,
                    'moderate' => 5,
                    'poor' => 3,
                    'very_poor' => 2,
                ),
            ),
            'required' => true,
        ),
    ),
); 