<?php
/**
 * Assessment Definition: Skin Assessment
 * Enhanced by Dr. Silas Apex (Sports Medicine & Aesthetic Medicine)
 * Evidence-based dermatology implementation
 *
 * @package ENNU_Life
 * @version 62.3.1
 */

return array(
	'title'             => 'Skin Assessment',
	'assessment_engine' => 'quantitative',
	'questions'         => array(
		'skin_q_gender' => array(
			'title'      => 'What is your gender?',
			'type'       => 'radio',
			'options'    => array(
				'male'   => 'Male',
				'female' => 'Female',
				'other'  => 'Other / Prefer not to say',
			),
			'required'   => true,
			'global_key' => 'gender',
		),
		'skin_q_age'    => array(
			'title'    => 'What is your age?',
			'type'     => 'radio',
			'options'  => array(
				'under_25' => 'Under 25',
				'25_35'    => '25-35',
				'36_45'    => '36-45',
				'46_55'    => '46-55',
				'over_55'  => 'Over 55',
			),
			'scoring'  => array(
				'category' => 'Age Factors',
				'weight'   => 1.5,
				'answers'  => array(
					'under_25' => 8,
					'25_35'    => 7,
					'36_45'    => 6,
					'46_55'    => 5,
					'over_55'  => 4,
				),
			),
			'required' => true,
		),
		'skin_q1'       => array(
			'title'    => 'What is your skin type?',
			'type'     => 'radio',
			'options'  => array(
				'oily'        => 'Oily - Shiny, prone to breakouts',
				'dry'         => 'Dry - Flaky, tight feeling',
				'combination' => 'Combination - Oily T-zone, dry elsewhere',
				'normal'      => 'Normal - Balanced, not too oily or dry',
				'sensitive'   => 'Sensitive - Easily irritated, reactive',
			),
			'scoring'  => array(
				'category' => 'Skin Characteristics',
				'weight'   => 2,
				'answers'  => array(
					'oily'        => 4,
					'dry'         => 4,
					'combination' => 5,
					'normal'      => 7,
					'sensitive'   => 3,
				),
			),
			'required' => true,
		),
		'skin_q2'       => array(
			'title'    => 'What are your primary skin concerns?',
			'type'     => 'multiselect',
			'options'  => array(
				'acne'           => 'Acne and breakouts',
				'aging'          => 'Fine lines and wrinkles',
				'pigmentation'   => 'Dark spots and hyperpigmentation',
				'redness'        => 'Redness and rosacea',
				'dullness'       => 'Dullness and lack of radiance',
				'uneven_texture' => 'Uneven skin texture',
				'large_pores'    => 'Large pores',
				'dark_circles'   => 'Dark circles under eyes',
				'none'           => 'None of the above',
			),
			'scoring'  => array(
				'category' => 'Skin Issues',
				'weight'   => 2.5,
				'answers'  => array(
					'acne'           => 3,
					'aging'          => 4,
					'pigmentation'   => 4,
					'redness'        => 3,
					'dullness'       => 5,
					'uneven_texture' => 4,
					'large_pores'    => 4,
					'dark_circles'   => 5,
					'none'           => 8,
				),
			),
			'required' => true,
		),
		'skin_q3'       => array(
			'title'    => 'How much time do you spend in the sun on an average day?',
			'type'     => 'radio',
			'options'  => array(
				'none'     => 'Hardly any',
				'minimal'  => 'Less than 30 minutes',
				'moderate' => 'Between 30 minutes and 2 hours',
				'high'     => 'More than 2 hours',
			),
			'scoring'  => array(
				'category' => 'Environmental Factors',
				'weight'   => 2,
				'answers'  => array(
					'none'     => 7,
					'minimal'  => 6,
					'moderate' => 4,
					'high'     => 2,
				),
			),
			'required' => true,
		),
		'skin_q4'       => array(
			'title'    => 'How would you describe your daily skincare routine?',
			'type'     => 'radio',
			'options'  => array(
				'none'          => 'None (I don\'t have a regular routine)',
				'basic'         => 'Basic (e.g., cleanser, moisturizer)',
				'moderate'      => 'Moderate (includes sunscreen, treatment products)',
				'comprehensive' => 'Comprehensive (multiple steps, targeted treatments)',
				'professional'  => 'Professional-grade products and treatments',
			),
			'scoring'  => array(
				'category' => 'Skincare Routine',
				'weight'   => 2,
				'answers'  => array(
					'none'          => 2,
					'basic'         => 4,
					'moderate'      => 6,
					'comprehensive' => 8,
					'professional'  => 9,
				),
			),
			'required' => true,
		),
		'skin_q5'       => array(
			'title'    => 'Do you use sunscreen regularly?',
			'type'     => 'radio',
			'options'  => array(
				'never'     => 'Never',
				'rarely'    => 'Rarely',
				'sometimes' => 'Sometimes',
				'often'     => 'Often',
				'always'    => 'Always (daily, year-round)',
			),
			'scoring'  => array(
				'category' => 'Sun Protection',
				'weight'   => 2.5,
				'answers'  => array(
					'never'     => 1,
					'rarely'    => 3,
					'sometimes' => 5,
					'often'     => 7,
					'always'    => 9,
				),
			),
			'required' => true,
		),
		'skin_q6'       => array(
			'title'    => 'Have you ever had a severe sunburn?',
			'type'     => 'radio',
			'options'  => array(
				'never'      => 'Never',
				'once'       => 'Once',
				'few_times'  => 'A few times',
				'many_times' => 'Many times',
				'regularly'  => 'Regularly as a child/teen',
			),
			'scoring'  => array(
				'category' => 'Sun Damage History',
				'weight'   => 2,
				'answers'  => array(
					'never'      => 9,
					'once'       => 7,
					'few_times'  => 5,
					'many_times' => 3,
					'regularly'  => 2,
				),
			),
			'required' => true,
		),
		'skin_q7'       => array(
			'title'    => 'Do you have a family history of skin cancer?',
			'type'     => 'radio',
			'options'  => array(
				'none'     => 'None known',
				'distant'  => 'Distant relative',
				'close'    => 'Close relative (parent, sibling)',
				'multiple' => 'Multiple family members',
				'personal' => 'Personal history of skin cancer',
			),
			'scoring'  => array(
				'category' => 'Skin Cancer Risk',
				'weight'   => 2.5,
				'answers'  => array(
					'none'     => 8,
					'distant'  => 6,
					'close'    => 4,
					'multiple' => 2,
					'personal' => 1,
				),
			),
			'required' => true,
		),
		'skin_q8'       => array(
			'title'    => 'How would you describe your skin tone and sun sensitivity?',
			'type'     => 'radio',
			'options'  => array(
				'very_fair' => 'Very fair - Always burns, never tans',
				'fair'      => 'Fair - Usually burns, tans minimally',
				'medium'    => 'Medium - Sometimes burns, tans gradually',
				'olive'     => 'Olive - Rarely burns, tans easily',
				'dark'      => 'Dark - Very rarely burns, tans very easily',
			),
			'scoring'  => array(
				'category' => 'Skin Tone & Sensitivity',
				'weight'   => 2,
				'answers'  => array(
					'very_fair' => 3,
					'fair'      => 4,
					'medium'    => 6,
					'olive'     => 7,
					'dark'      => 8,
				),
			),
			'required' => true,
		),
		'skin_q9'       => array(
			'title'    => 'Have you noticed any new or changing moles or skin lesions?',
			'type'     => 'radio',
			'options'  => array(
				'none'         => 'None',
				'stable'       => 'Stable moles, no changes',
				'some_changes' => 'Some changes in existing moles',
				'new_moles'    => 'New moles appearing',
				'concerning'   => 'Concerning changes (irregular, growing)',
			),
			'scoring'  => array(
				'category' => 'Mole Monitoring',
				'weight'   => 2.5,
				'answers'  => array(
					'none'         => 8,
					'stable'       => 7,
					'some_changes' => 5,
					'new_moles'    => 4,
					'concerning'   => 2,
				),
			),
			'required' => true,
		),
		'skin_q10'      => array(
			'title'    => 'Do you have any skin conditions or allergies?',
			'type'     => 'multiselect',
			'options'  => array(
				'none'       => 'None',
				'eczema'     => 'Eczema or atopic dermatitis',
				'psoriasis'  => 'Psoriasis',
				'rosacea'    => 'Rosacea',
				'allergies'  => 'Skin allergies or sensitivities',
				'acne_scars' => 'Acne scars',
				'vitiligo'   => 'Vitiligo',
				'other'      => 'Other skin conditions',
			),
			'scoring'  => array(
				'category' => 'Skin Conditions',
				'weight'   => 2,
				'answers'  => array(
					'none'       => 8,
					'eczema'     => 4,
					'psoriasis'  => 4,
					'rosacea'    => 5,
					'allergies'  => 4,
					'acne_scars' => 5,
					'vitiligo'   => 6,
					'other'      => 4,
				),
			),
			'required' => true,
		),
		'skin_q11'      => array(
			'title'    => 'How would you rate your skin hydration and moisture levels?',
			'type'     => 'radio',
			'options'  => array(
				'excellent' => 'Excellent - Well hydrated, supple',
				'good'      => 'Good - Generally well hydrated',
				'moderate'  => 'Moderate - Sometimes dry',
				'poor'      => 'Poor - Often dry, tight feeling',
				'very_poor' => 'Very Poor - Constantly dry, flaky',
			),
			'scoring'  => array(
				'category' => 'Skin Hydration',
				'weight'   => 2,
				'answers'  => array(
					'excellent' => 9,
					'good'      => 7,
					'moderate'  => 5,
					'poor'      => 3,
					'very_poor' => 2,
				),
			),
			'required' => true,
		),
		'skin_q12'      => array(
			'title'    => 'How often do you exfoliate your skin?',
			'type'     => 'radio',
			'options'  => array(
				'never'      => 'Never',
				'rarely'     => 'Rarely',
				'weekly'     => 'Weekly',
				'twice_week' => '2-3 times per week',
				'daily'      => 'Daily',
			),
			'scoring'  => array(
				'category' => 'Exfoliation',
				'weight'   => 1.5,
				'answers'  => array(
					'never'      => 3,
					'rarely'     => 4,
					'weekly'     => 6,
					'twice_week' => 7,
					'daily'      => 5,
				),
			),
			'required' => true,
		),
		'skin_q13'      => array(
			'title'    => 'Have you had any professional skin treatments?',
			'type'     => 'multiselect',
			'options'  => array(
				'none'              => 'None',
				'facials'           => 'Regular facials',
				'chemical_peels'    => 'Chemical peels',
				'microdermabrasion' => 'Microdermabrasion',
				'laser_treatments'  => 'Laser treatments',
				'injectables'       => 'Botox or fillers',
				'other'             => 'Other treatments',
			),
			'scoring'  => array(
				'category' => 'Professional Treatments',
				'weight'   => 1.5,
				'answers'  => array(
					'none'              => 5,
					'facials'           => 6,
					'chemical_peels'    => 7,
					'microdermabrasion' => 6,
					'laser_treatments'  => 7,
					'injectables'       => 6,
					'other'             => 5,
				),
			),
			'required' => true,
		),
		'skin_q14'      => array(
			'title'    => 'How would you rate your overall skin health and appearance?',
			'type'     => 'radio',
			'options'  => array(
				'excellent' => 'Excellent - Healthy, glowing skin',
				'good'      => 'Good - Generally healthy appearance',
				'moderate'  => 'Moderate - Some concerns but manageable',
				'poor'      => 'Poor - Multiple concerns affecting appearance',
				'very_poor' => 'Very Poor - Significant skin health issues',
			),
			'scoring'  => array(
				'category' => 'Overall Assessment',
				'weight'   => 2,
				'answers'  => array(
					'excellent' => 9,
					'good'      => 7,
					'moderate'  => 5,
					'poor'      => 3,
					'very_poor' => 2,
				),
			),
			'required' => true,
		),
	),
);
