<?php
/**
 * Assessment Definition: Sleep Assessment
 * Enhanced by Dr. Nora Cognita (Neurology Master)
 * Evidence-based sleep medicine implementation
 *
 * @package ENNU_Life
 * @version 62.11.0
 */

return array(
	'title'             => 'Sleep Assessment',
	'assessment_engine' => 'quantitative',
	'questions'         => array(
		'sleep_q_gender' => array(
			'title'      => 'What is your gender?',
			'type'       => 'radio',
			'options'    => array(
				'female' => 'FEMALE',
				'male'   => 'MALE',
			),
			'required'   => true,
			'global_key' => 'gender',
		),
		'sleep_q_dob'    => array(
			'title'      => 'What is your date of birth?',
			'type'       => 'dob_dropdowns',
			'required'   => true,
			'global_key' => 'date_of_birth',
			'scoring'    => array(
				'category' => 'Age Factors',
				'weight'   => 1.5,
				'calculation' => 'age_from_dob',
				'age_scores' => array(
					'18-25' => 8,
					'26-35' => 7,
					'36-45' => 6,
					'46-55' => 4,
					'56-65' => 3,
					'66-75' => 2,
					'76+'   => 1,
				),
			),
		),
		'sleep_q_height_weight' => array(
			'title'      => 'What is your height and weight?',
			'type'       => 'height_weight',
			'required'   => true,
			'global_key' => 'height_weight',
		),
		'sleep_q1'       => array(
			'title'    => 'On average, how many hours of sleep do you get per night?',
			'type'     => 'radio',
			'options'  => array(
				'less_than_5' => 'Less than 5 hours',
				'5_6'         => '5-6 hours',
				'7_8'         => '7-8 hours (Recommended)',
				'8_9'         => '8-9 hours',
				'more_than_9' => 'More than 9 hours',
			),
			'scoring'  => array(
				'category' => 'Sleep Duration',
				'weight'   => 2.5,
				'answers'  => array(
					'less_than_5' => 2,
					'5_6'         => 4,
					'7_8'         => 9,
					'8_9'         => 7,
					'more_than_9' => 5,
				),
			),
			'required' => true,
		),
		'sleep_q2'       => array(
			'title'    => 'How would you rate the quality of your sleep?',
			'type'     => 'radio',
			'options'  => array(
				'excellent' => 'Excellent - Deep, restorative sleep',
				'very_good' => 'Very Good - Generally restful',
				'good'      => 'Good - Mostly restful',
				'fair'      => 'Fair - Somewhat restful',
				'poor'      => 'Poor - Rarely feel rested',
			),
			'scoring'  => array(
				'category' => 'Sleep Quality',
				'weight'   => 3,
				'answers'  => array(
					'excellent' => 9,
					'very_good' => 7,
					'good'      => 5,
					'fair'      => 3,
					'poor'      => 1,
				),
			),
			'required' => true,
		),
		'sleep_q3'       => array(
			'title'    => 'How often do you wake up during the night?',
			'type'     => 'radio',
			'options'  => array(
				'never'       => 'Never - Sleep through the night',
				'rarely'      => 'Rarely (1-2 times per week)',
				'sometimes'   => 'Sometimes (1-2 times per night)',
				'often'       => 'Often (3+ times per night)',
				'every_night' => 'Almost every night (multiple times)',
			),
			'scoring'  => array(
				'category' => 'Sleep Continuity',
				'weight'   => 2.5,
				'answers'  => array(
					'never'       => 9,
					'rarely'      => 7,
					'sometimes'   => 5,
					'often'       => 3,
					'every_night' => 1,
				),
			),
			'required' => true,
		),
		'sleep_q4'       => array(
			'title'    => 'How long does it typically take you to fall asleep?',
			'type'     => 'radio',
			'options'  => array(
				'under_15' => 'Under 15 minutes',
				'15_30'    => '15-30 minutes',
				'30_60'    => '30-60 minutes',
				'over_60'  => 'Over 60 minutes',
			),
			'scoring'  => array(
				'category' => 'Sleep Latency',
				'weight'   => 2,
				'answers'  => array(
					'under_15' => 9,
					'15_30'    => 7,
					'30_60'    => 4,
					'over_60'  => 2,
				),
			),
			'required' => true,
		),
		'sleep_q5'       => array(
			'title'    => 'How do you feel when you wake up in the morning?',
			'type'     => 'radio',
			'options'  => array(
				'refreshed' => 'Refreshed and energetic',
				'okay'      => 'Okay, but could be better',
				'groggy'    => 'Groggy and unrested',
				'exhausted' => 'Exhausted',
			),
			'scoring'  => array(
				'category' => 'Daytime Function',
				'weight'   => 2.5,
				'answers'  => array(
					'refreshed' => 9,
					'okay'      => 6,
					'groggy'    => 3,
					'exhausted' => 1,
				),
			),
			'required' => true,
		),
		'sleep_q6'       => array(
			'title'    => 'How often do you feel drowsy or have the urge to nap during the day?',
			'type'     => 'radio',
			'options'  => array(
				'never'     => 'Never',
				'rarely'    => 'Rarely',
				'sometimes' => 'Sometimes',
				'often'     => 'Often',
				'daily'     => 'Daily',
			),
			'scoring'  => array(
				'category' => 'Daytime Sleepiness',
				'weight'   => 2,
				'answers'  => array(
					'never'     => 9,
					'rarely'    => 7,
					'sometimes' => 5,
					'often'     => 3,
					'daily'     => 1,
				),
			),
			'required' => true,
		),
		'sleep_q7'       => array(
			'title'    => 'Do you snore loudly or have been told you snore?',
			'type'     => 'radio',
			'options'  => array(
				'never'       => 'Never',
				'rarely'      => 'Rarely',
				'sometimes'   => 'Sometimes',
				'often'       => 'Often',
				'every_night' => 'Every night',
			),
			'scoring'  => array(
				'category' => 'Sleep Apnea Risk',
				'weight'   => 2.5,
				'answers'  => array(
					'never'       => 9,
					'rarely'      => 7,
					'sometimes'   => 5,
					'often'       => 3,
					'every_night' => 1,
				),
			),
			'required' => true,
		),
		'sleep_q8'       => array(
			'title'    => 'Have you been told you stop breathing or gasp for air during sleep?',
			'type'     => 'radio',
			'options'  => array(
				'never'       => 'Never',
				'rarely'      => 'Rarely',
				'sometimes'   => 'Sometimes',
				'often'       => 'Often',
				'every_night' => 'Every night',
			),
			'scoring'  => array(
				'category' => 'Sleep Apnea Risk',
				'weight'   => 3,
				'answers'  => array(
					'never'       => 9,
					'rarely'      => 6,
					'sometimes'   => 4,
					'often'       => 2,
					'every_night' => 1,
				),
			),
			'required' => true,
		),
		'sleep_q9'       => array(
			'title'    => 'Do you experience restless legs or an urge to move your legs at night?',
			'type'     => 'radio',
			'options'  => array(
				'never'       => 'Never',
				'rarely'      => 'Rarely',
				'sometimes'   => 'Sometimes',
				'often'       => 'Often',
				'every_night' => 'Every night',
			),
			'scoring'  => array(
				'category' => 'Restless Leg Syndrome',
				'weight'   => 2,
				'answers'  => array(
					'never'       => 9,
					'rarely'      => 7,
					'sometimes'   => 5,
					'often'       => 3,
					'every_night' => 1,
				),
			),
			'required' => true,
		),
		'sleep_q10'      => array(
			'title'    => 'Do you experience vivid dreams, nightmares, or sleep paralysis?',
			'type'     => 'radio',
			'options'  => array(
				'never'       => 'Never',
				'rarely'      => 'Rarely',
				'sometimes'   => 'Sometimes',
				'often'       => 'Often',
				'every_night' => 'Every night',
			),
			'scoring'  => array(
				'category' => 'Sleep Disorders',
				'weight'   => 2,
				'answers'  => array(
					'never'       => 9,
					'rarely'      => 7,
					'sometimes'   => 5,
					'often'       => 3,
					'every_night' => 1,
				),
			),
			'required' => true,
		),
		'sleep_q11'      => array(
			'title'    => 'What do you typically do within 1 hour before bedtime?',
			'type'     => 'multiselect',
			'options'  => array(
				'screen_time' => 'Use phone, computer, or watch TV',
				'caffeine'    => 'Consume caffeine (coffee, tea, energy drinks)',
				'alcohol'     => 'Consume alcohol',
				'large_meal'  => 'Eat a large meal',
				'exercise'    => 'Engage in vigorous exercise',
				'work'        => 'Work or study',
				'relaxation'  => 'Relaxation techniques (meditation, reading)',
				'nothing'     => 'Nothing specific',
			),
			'scoring'  => array(
				'category' => 'Sleep Hygiene',
				'weight'   => 1.5,
				'answers'  => array(
					'screen_time' => 3,
					'caffeine'    => 2,
					'alcohol'     => 4,
					'large_meal'  => 4,
					'exercise'    => 4,
					'work'        => 3,
					'relaxation'  => 8,
					'nothing'     => 6,
				),
			),
			'required' => true,
		),
		'sleep_q12'      => array(
			'title'    => 'What is your typical sleep schedule?',
			'type'     => 'radio',
			'options'  => array(
				'consistent'          => 'Very consistent (same time every night)',
				'mostly_consistent'   => 'Mostly consistent (within 1 hour)',
				'somewhat_consistent' => 'Somewhat consistent (within 2 hours)',
				'irregular'           => 'Irregular (varies by 2+ hours)',
				'very_irregular'      => 'Very irregular (no set schedule)',
			),
			'scoring'  => array(
				'category' => 'Sleep Schedule',
				'weight'   => 2,
				'answers'  => array(
					'consistent'          => 9,
					'mostly_consistent'   => 7,
					'somewhat_consistent' => 5,
					'irregular'           => 3,
					'very_irregular'      => 1,
				),
			),
			'required' => true,
		),
		'sleep_q13'      => array(
			'title'    => 'Do you use any sleep aids or medications?',
			'type'     => 'radio',
			'options'  => array(
				'none'         => 'None',
				'melatonin'    => 'Melatonin (natural)',
				'herbal'       => 'Herbal supplements (valerian, chamomile)',
				'otc'          => 'Over-the-counter sleep aids',
				'prescription' => 'Prescription sleep medication',
			),
			'scoring'  => array(
				'category' => 'Sleep Dependency',
				'weight'   => 1.5,
				'answers'  => array(
					'none'         => 9,
					'melatonin'    => 6,
					'herbal'       => 5,
					'otc'          => 3,
					'prescription' => 2,
				),
			),
			'required' => true,
		),
		'sleep_q14'      => array(
			'title'    => 'How would you describe your bedroom environment?',
			'type'     => 'multiselect',
			'options'  => array(
				'dark'          => 'Very dark',
				'quiet'         => 'Very quiet',
				'cool'          => 'Cool temperature (65-68°F)',
				'comfortable'   => 'Comfortable mattress and pillows',
				'bright'        => 'Bright or light',
				'noisy'         => 'Noisy',
				'warm'          => 'Warm temperature',
				'uncomfortable' => 'Uncomfortable mattress or pillows',
			),
			'scoring'  => array(
				'category' => 'Sleep Environment',
				'weight'   => 1.5,
				'answers'  => array(
					'dark'          => 8,
					'quiet'         => 8,
					'cool'          => 8,
					'comfortable'   => 8,
					'bright'        => 3,
					'noisy'         => 3,
					'warm'          => 4,
					'uncomfortable' => 3,
				),
			),
			'required' => true,
		),
		'sleep_symptoms' => array(
			'title'    => 'Select any sleep-related symptoms you experience:',
			'type'     => 'multiselect',
			'options'  => array(
				'insomnia'          => 'Difficulty falling asleep',
				'frequent_waking'   => 'Waking up frequently at night',
				'early_waking'      => 'Waking too early',
				'unrefreshing_sleep'=> 'Unrefreshing sleep',
				'fatigue'           => 'Daytime fatigue',
				'brain_fog'         => 'Morning brain fog',
				'anxiety'           => 'Nighttime anxiety',
				'depression'        => 'Depression affecting sleep',
				'night_sweats'      => 'Night sweats',
				'restless_legs'     => 'Restless legs',
				'none'              => 'None of the above',
			),
			'scoring'  => array(
				'category' => 'Sleep Symptoms',
				'weight'   => 2,
				'answers'  => array(
					'insomnia'           => 1,
					'frequent_waking'    => 2,
					'early_waking'       => 2,
					'unrefreshing_sleep' => 2,
					'fatigue'            => 2,
					'brain_fog'          => 2,
					'anxiety'            => 2,
					'depression'         => 2,
					'night_sweats'       => 2,
					'restless_legs'      => 2,
					'none'               => 8,
				),
			),
			'required' => false,
		),
	),
);
