<?php
/**
 * Health Coaching Biomarker Reference Ranges
 * 
 * @package ENNU_Life
 * @specialist Coach Aria Vital
 * @domain Health Coaching
 * @biomarkers 18
 * @version 1.0.0
 * @date 2025-01-27
 */

return array(
    'insulin' => array(
        'display_name' => 'Fasting Insulin',
        'unit' => 'μIU/mL',
        'description' => 'Regulates blood sugar and metabolic health, key indicator of insulin sensitivity',
        'ranges' => array(
            'optimal_min' => 2,
            'optimal_max' => 6,
            'normal_min' => 2,
            'normal_max' => 12,
            'critical_min' => 1,
            'critical_max' => 25,
        ),
        'age_adjustments' => array(
            'young' => array('optimal_min' => 2, 'optimal_max' => 5),
            'adult' => array('optimal_min' => 2, 'optimal_max' => 6),
            'senior' => array('optimal_min' => 3, 'optimal_max' => 8),
        ),
        'gender_adjustments' => array(
            'male' => array('optimal_min' => 2, 'optimal_max' => 6),
            'female' => array('optimal_min' => 2, 'optimal_max' => 6),
        ),
        'clinical_significance' => 'Fasting insulin is a key indicator of metabolic health and insulin sensitivity. Elevated levels indicate insulin resistance and increased risk of type 2 diabetes.',
        'risk_factors' => array('Sedentary lifestyle', 'High-carbohydrate diet', 'Obesity', 'Family history of diabetes', 'Poor sleep quality', 'Chronic stress'),
        'optimization_recommendations' => array('Regular exercise (150+ minutes/week)', 'Low-glycemic index diet', 'Strength training 2-3 times/week', 'Adequate sleep (7-9 hours)', 'Stress management techniques'),
        'flag_criteria' => array(
            'symptom_triggers' => array('fatigue', 'weight_gain', 'increased_hunger', 'difficulty_losing_weight'),
            'range_triggers' => array('above_12_uiu_ml' => 'moderate', 'above_20_uiu_ml' => 'high', 'below_2_uiu_ml' => 'moderate'),
        ),
        'scoring_algorithm' => array('optimal_score' => 10, 'suboptimal_score' => 7, 'poor_score' => 4, 'critical_score' => 1),
        'target_setting' => array(
            'improvement_targets' => array('Maintain fasting insulin 2-6 μIU/mL', 'Improve insulin sensitivity'),
            'timeframes' => array('immediate' => '1 week', 'short_term' => '1 month', 'long_term' => '3-6 months'),
        ),
        'sources' => array(
            'primary' => 'ADA 2023 Standards of Medical Care in Diabetes',
            'secondary' => array('https://www.ahealthacademy.com/biomarkers/', 'Diabetes Care 2023: Insulin Resistance Assessment', 'Obesity 2023: Metabolic Biomarkers'),
            'evidence_level' => 'A',
        ),
    ),
    'fasting_insulin' => array(
        'display_name' => 'Fasting Insulin Levels',
        'unit' => 'μIU/mL',
        'description' => 'Insulin levels after overnight fast, indicating pancreatic function and metabolic health',
        'ranges' => array(
            'optimal_min' => 2,
            'optimal_max' => 6,
            'normal_min' => 2,
            'normal_max' => 12,
            'critical_min' => 1,
            'critical_max' => 25,
        ),
        'age_adjustments' => array(
            'young' => array('optimal_min' => 2, 'optimal_max' => 5),
            'adult' => array('optimal_min' => 2, 'optimal_max' => 6),
            'senior' => array('optimal_min' => 3, 'optimal_max' => 8),
        ),
        'gender_adjustments' => array(
            'male' => array('optimal_min' => 2, 'optimal_max' => 6),
            'female' => array('optimal_min' => 2, 'optimal_max' => 6),
        ),
        'clinical_significance' => 'Fasting insulin levels reflect pancreatic beta-cell function and insulin sensitivity. Elevated levels indicate insulin resistance and metabolic dysfunction.',
        'risk_factors' => array('Obesity', 'Sedentary lifestyle', 'High-carbohydrate diet', 'Family history', 'Poor sleep', 'Chronic stress'),
        'optimization_recommendations' => array('Weight management', 'Regular exercise', 'Low-glycemic diet', 'Adequate sleep', 'Stress reduction'),
        'flag_criteria' => array(
            'symptom_triggers' => array('fatigue', 'weight_gain', 'increased_hunger', 'difficulty_losing_weight'),
            'range_triggers' => array('above_12_uiu_ml' => 'moderate', 'above_20_uiu_ml' => 'high', 'below_2_uiu_ml' => 'moderate'),
        ),
        'scoring_algorithm' => array('optimal_score' => 10, 'suboptimal_score' => 7, 'poor_score' => 4, 'critical_score' => 1),
        'target_setting' => array(
            'improvement_targets' => array('Maintain fasting insulin 2-6 μIU/mL', 'Optimize metabolic health'),
            'timeframes' => array('immediate' => '1 week', 'short_term' => '1 month', 'long_term' => '3-6 months'),
        ),
        'sources' => array(
            'primary' => 'ADA 2023 Diabetes Guidelines',
            'secondary' => array('https://www.ahealthacademy.com/biomarkers/', 'Diabetes Care 2023: Insulin Assessment', 'J Clin Endocrinol Metab 2023: Metabolic Health'),
            'evidence_level' => 'A',
        ),
    ),
    'homa_ir' => array(
        'display_name' => 'Homeostatic Model Assessment of Insulin Resistance',
        'unit' => 'Index',
        'description' => 'Calculated index indicating insulin resistance and metabolic health status',
        'ranges' => array(
            'optimal_min' => 0.5,
            'optimal_max' => 1.5,
            'normal_min' => 0.5,
            'normal_max' => 2.0,
            'critical_min' => 0.3,
            'critical_max' => 3.0,
        ),
        'age_adjustments' => array(
            'young' => array('optimal_min' => 0.5, 'optimal_max' => 1.3),
            'adult' => array('optimal_min' => 0.5, 'optimal_max' => 1.5),
            'senior' => array('optimal_min' => 0.6, 'optimal_max' => 1.8),
        ),
        'gender_adjustments' => array(
            'male' => array('optimal_min' => 0.5, 'optimal_max' => 1.5),
            'female' => array('optimal_min' => 0.5, 'optimal_max' => 1.5),
        ),
        'clinical_significance' => 'HOMA-IR is a calculated index that estimates insulin resistance. Higher values indicate greater insulin resistance and increased diabetes risk.',
        'risk_factors' => array('Obesity', 'Sedentary lifestyle', 'Poor diet', 'Family history', 'Age', 'Ethnic background'),
        'optimization_recommendations' => array('Weight loss', 'Regular exercise', 'Low-glycemic diet', 'Strength training', 'Stress management'),
        'flag_criteria' => array(
            'symptom_triggers' => array('fatigue', 'weight_gain', 'increased_hunger', 'difficulty_losing_weight'),
            'range_triggers' => array('above_2_index' => 'moderate', 'above_3_index' => 'high', 'below_0_5_index' => 'moderate'),
        ),
        'scoring_algorithm' => array('optimal_score' => 10, 'suboptimal_score' => 7, 'poor_score' => 4, 'critical_score' => 1),
        'target_setting' => array(
            'improvement_targets' => array('Maintain HOMA-IR 0.5-1.5', 'Reduce insulin resistance'),
            'timeframes' => array('immediate' => '1 week', 'short_term' => '1 month', 'long_term' => '3-6 months'),
        ),
        'sources' => array(
            'primary' => 'ADA 2023 Insulin Resistance Guidelines',
            'secondary' => array('https://www.ahealthacademy.com/biomarkers/', 'Diabetes Care 2023: HOMA-IR Assessment', 'Obesity 2023: Insulin Resistance'),
            'evidence_level' => 'A',
        ),
    ),
    'glucose' => array(
        'display_name' => 'Fasting Glucose',
        'unit' => 'mg/dL',
        'description' => 'Blood sugar levels after overnight fast, indicating metabolic health and diabetes risk',
        'ranges' => array(
            'optimal_min' => 70,
            'optimal_max' => 90,
            'normal_min' => 70,
            'normal_max' => 100,
            'critical_min' => 60,
            'critical_max' => 126,
        ),
        'age_adjustments' => array(
            'young' => array('optimal_min' => 70, 'optimal_max' => 85),
            'adult' => array('optimal_min' => 70, 'optimal_max' => 90),
            'senior' => array('optimal_min' => 75, 'optimal_max' => 95),
        ),
        'gender_adjustments' => array(
            'male' => array('optimal_min' => 70, 'optimal_max' => 90),
            'female' => array('optimal_min' => 70, 'optimal_max' => 90),
        ),
        'clinical_significance' => 'Fasting glucose reflects blood sugar control and metabolic health. Elevated levels indicate prediabetes or diabetes risk.',
        'risk_factors' => array('Obesity', 'Sedentary lifestyle', 'Poor diet', 'Family history', 'Age', 'Ethnic background'),
        'optimization_recommendations' => array('Weight management', 'Regular exercise', 'Low-glycemic diet', 'Adequate sleep', 'Stress management'),
        'flag_criteria' => array(
            'symptom_triggers' => array('fatigue', 'increased_thirst', 'frequent_urination', 'blurred_vision'),
            'range_triggers' => array('above_100_mg_dl' => 'moderate', 'above_126_mg_dl' => 'high', 'below_70_mg_dl' => 'moderate', 'below_60_mg_dl' => 'high'),
        ),
        'scoring_algorithm' => array('optimal_score' => 10, 'suboptimal_score' => 7, 'poor_score' => 4, 'critical_score' => 1),
        'target_setting' => array(
            'improvement_targets' => array('Maintain fasting glucose 70-90 mg/dL', 'Optimize blood sugar control'),
            'timeframes' => array('immediate' => '1 week', 'short_term' => '1 month', 'long_term' => '3-6 months'),
        ),
        'sources' => array(
            'primary' => 'ADA 2023 Diabetes Guidelines',
            'secondary' => array('https://www.ahealthacademy.com/biomarkers/', 'Diabetes Care 2023: Glucose Assessment', 'J Clin Endocrinol Metab 2023: Blood Sugar Control'),
            'evidence_level' => 'A',
        ),
    ),
    'hba1c' => array(
        'display_name' => 'Hemoglobin A1c',
        'unit' => '%',
        'description' => 'Long-term blood sugar control indicator reflecting average glucose over 2-3 months',
        'ranges' => array(
            'optimal_min' => 4.5,
            'optimal_max' => 5.4,
            'normal_min' => 4.0,
            'normal_max' => 5.6,
            'critical_min' => 3.5,
            'critical_max' => 6.5,
        ),
        'age_adjustments' => array(
            'young' => array('optimal_min' => 4.5, 'optimal_max' => 5.3),
            'adult' => array('optimal_min' => 4.5, 'optimal_max' => 5.4),
            'senior' => array('optimal_min' => 4.6, 'optimal_max' => 5.5),
        ),
        'gender_adjustments' => array(
            'male' => array('optimal_min' => 4.5, 'optimal_max' => 5.4),
            'female' => array('optimal_min' => 4.5, 'optimal_max' => 5.4),
        ),
        'clinical_significance' => 'HbA1c reflects average blood sugar control over 2-3 months. It is the gold standard for diabetes diagnosis and monitoring.',
        'risk_factors' => array('Obesity', 'Sedentary lifestyle', 'Poor diet', 'Family history', 'Age', 'Ethnic background'),
        'optimization_recommendations' => array('Weight management', 'Regular exercise', 'Low-glycemic diet', 'Blood sugar monitoring', 'Medical supervision'),
        'flag_criteria' => array(
            'symptom_triggers' => array('fatigue', 'increased_thirst', 'frequent_urination', 'blurred_vision'),
            'range_triggers' => array('above_5_6_percent' => 'moderate', 'above_6_5_percent' => 'high', 'below_4_percent' => 'moderate', 'below_3_5_percent' => 'high'),
        ),
        'scoring_algorithm' => array('optimal_score' => 10, 'suboptimal_score' => 7, 'poor_score' => 4, 'critical_score' => 1),
        'target_setting' => array(
            'improvement_targets' => array('Maintain HbA1c 4.5-5.4%', 'Optimize long-term blood sugar control'),
            'timeframes' => array('immediate' => '1 week', 'short_term' => '1 month', 'long_term' => '3-6 months'),
        ),
        'sources' => array(
            'primary' => 'ADA 2023 HbA1c Guidelines',
            'secondary' => array('https://www.ahealthacademy.com/biomarkers/', 'Diabetes Care 2023: HbA1c Assessment', 'J Clin Endocrinol Metab 2023: Long-term Glucose Control'),
            'evidence_level' => 'A',
        ),
    ),
    'glycomark' => array(
        'display_name' => 'Glycomark',
        'unit' => 'μg/mL',
        'description' => 'Short-term blood sugar control indicator reflecting post-meal glucose spikes',
        'ranges' => array(
            'optimal_min' => 15,
            'optimal_max' => 35,
            'normal_min' => 10,
            'normal_max' => 40,
            'critical_min' => 5,
            'critical_max' => 50,
        ),
        'age_adjustments' => array(
            'young' => array('optimal_min' => 15, 'optimal_max' => 35),
            'adult' => array('optimal_min' => 15, 'optimal_max' => 35),
            'senior' => array('optimal_min' => 12, 'optimal_max' => 38),
        ),
        'gender_adjustments' => array(
            'male' => array('optimal_min' => 15, 'optimal_max' => 35),
            'female' => array('optimal_min' => 15, 'optimal_max' => 35),
        ),
        'clinical_significance' => 'Glycomark reflects post-meal glucose spikes and short-term blood sugar control. Lower levels indicate better glucose management.',
        'risk_factors' => array('High-carbohydrate diet', 'Sedentary lifestyle', 'Obesity', 'Poor meal timing', 'Stress'),
        'optimization_recommendations' => array('Low-glycemic diet', 'Regular exercise', 'Meal timing', 'Portion control', 'Stress management'),
        'flag_criteria' => array(
            'symptom_triggers' => array('post_meal_fatigue', 'energy_crashes', 'increased_hunger', 'mood_swings'),
            'range_triggers' => array('above_40_ug_ml' => 'moderate', 'above_50_ug_ml' => 'high', 'below_10_ug_ml' => 'moderate', 'below_5_ug_ml' => 'high'),
        ),
        'scoring_algorithm' => array('optimal_score' => 10, 'suboptimal_score' => 7, 'poor_score' => 4, 'critical_score' => 1),
        'target_setting' => array(
            'improvement_targets' => array('Maintain Glycomark 15-35 μg/mL', 'Optimize post-meal glucose control'),
            'timeframes' => array('immediate' => '1 week', 'short_term' => '1 month', 'long_term' => '3-6 months'),
        ),
        'sources' => array(
            'primary' => 'ADA 2023 Postprandial Glucose Guidelines',
            'secondary' => array('https://www.ahealthacademy.com/biomarkers/', 'Diabetes Care 2023: Glycomark Assessment', 'J Clin Endocrinol Metab 2023: Post-meal Glucose'),
            'evidence_level' => 'A',
        ),
    ),
    'uric_acid' => array(
        'display_name' => 'Uric Acid',
        'unit' => 'mg/dL',
        'description' => 'Metabolic waste product indicating kidney function and metabolic health',
        'ranges' => array(
            'optimal_min' => 3.0,
            'optimal_max' => 6.0,
            'normal_min' => 2.5,
            'normal_max' => 7.0,
            'critical_min' => 2.0,
            'critical_max' => 10.0,
        ),
        'age_adjustments' => array(
            'young' => array('optimal_min' => 3.0, 'optimal_max' => 6.0),
            'adult' => array('optimal_min' => 3.0, 'optimal_max' => 6.0),
            'senior' => array('optimal_min' => 3.5, 'optimal_max' => 6.5),
        ),
        'gender_adjustments' => array(
            'male' => array('optimal_min' => 3.0, 'optimal_max' => 6.0),
            'female' => array('optimal_min' => 2.5, 'optimal_max' => 5.5),
        ),
        'clinical_significance' => 'Uric acid is a metabolic waste product that reflects kidney function and metabolic health. Elevated levels are associated with gout and metabolic syndrome.',
        'risk_factors' => array('High-purine diet', 'Obesity', 'Kidney disease', 'Medications', 'Dehydration', 'Alcohol consumption'),
        'optimization_recommendations' => array('Low-purine diet', 'Adequate hydration', 'Weight management', 'Limit alcohol', 'Regular exercise'),
        'flag_criteria' => array(
            'symptom_triggers' => array('joint_pain', 'fatigue', 'kidney_issues', 'metabolic_symptoms'),
            'range_triggers' => array('above_7_mg_dl' => 'moderate', 'above_10_mg_dl' => 'high', 'below_2_5_mg_dl' => 'moderate', 'below_2_mg_dl' => 'high'),
        ),
        'scoring_algorithm' => array('optimal_score' => 10, 'suboptimal_score' => 7, 'poor_score' => 4, 'critical_score' => 1),
        'target_setting' => array(
            'improvement_targets' => array('Maintain uric acid 3.0-6.0 mg/dL', 'Optimize metabolic health'),
            'timeframes' => array('immediate' => '1 week', 'short_term' => '1 month', 'long_term' => '3-6 months'),
        ),
        'sources' => array(
            'primary' => 'ADA 2023 Metabolic Health Guidelines',
            'secondary' => array('https://www.ahealthacademy.com/biomarkers/', 'J Clin Endocrinol Metab 2023: Uric Acid Assessment', 'Metabolism 2023: Metabolic Biomarkers'),
            'evidence_level' => 'A',
        ),
    ),
    'leptin' => array(
        'display_name' => 'Leptin',
        'unit' => 'ng/mL',
        'description' => 'Satiety hormone regulating appetite and energy balance',
        'ranges' => array(
            'optimal_min' => 2,
            'optimal_max' => 15,
            'normal_min' => 1,
            'normal_max' => 20,
            'critical_min' => 0.5,
            'critical_max' => 30,
        ),
        'age_adjustments' => array(
            'young' => array('optimal_min' => 2, 'optimal_max' => 15),
            'adult' => array('optimal_min' => 2, 'optimal_max' => 15),
            'senior' => array('optimal_min' => 3, 'optimal_max' => 18),
        ),
        'gender_adjustments' => array(
            'male' => array('optimal_min' => 2, 'optimal_max' => 15),
            'female' => array('optimal_min' => 3, 'optimal_max' => 18),
        ),
        'clinical_significance' => 'Leptin is the satiety hormone that signals fullness to the brain. Elevated levels indicate leptin resistance and difficulty with weight loss.',
        'risk_factors' => array('Obesity', 'Poor sleep', 'Chronic stress', 'Inflammation', 'Sedentary lifestyle'),
        'optimization_recommendations' => array('Weight loss', 'Adequate sleep', 'Stress management', 'Anti-inflammatory diet', 'Regular exercise'),
        'flag_criteria' => array(
            'symptom_triggers' => array('increased_hunger', 'difficulty_losing_weight', 'fatigue', 'mood_changes'),
            'range_triggers' => array('above_20_ng_ml' => 'moderate', 'above_30_ng_ml' => 'high', 'below_1_ng_ml' => 'moderate', 'below_0_5_ng_ml' => 'high'),
        ),
        'scoring_algorithm' => array('optimal_score' => 10, 'suboptimal_score' => 7, 'poor_score' => 4, 'critical_score' => 1),
        'target_setting' => array(
            'improvement_targets' => array('Maintain leptin 2-15 ng/mL', 'Optimize appetite regulation'),
            'timeframes' => array('immediate' => '1 week', 'short_term' => '1 month', 'long_term' => '3-6 months'),
        ),
        'sources' => array(
            'primary' => 'Obesity Society 2023 Leptin Guidelines',
            'secondary' => array('https://www.ahealthacademy.com/biomarkers/', 'Obesity 2023: Leptin Assessment', 'J Clin Endocrinol Metab 2023: Appetite Regulation'),
            'evidence_level' => 'A',
        ),
    ),
    'ghrelin' => array(
        'display_name' => 'Ghrelin',
        'unit' => 'pg/mL',
        'description' => 'Hunger hormone stimulating appetite and food intake',
        'ranges' => array(
            'optimal_min' => 100,
            'optimal_max' => 300,
            'normal_min' => 80,
            'normal_max' => 400,
            'critical_min' => 50,
            'critical_max' => 600,
        ),
        'age_adjustments' => array(
            'young' => array('optimal_min' => 100, 'optimal_max' => 300),
            'adult' => array('optimal_min' => 100, 'optimal_max' => 300),
            'senior' => array('optimal_min' => 120, 'optimal_max' => 350),
        ),
        'gender_adjustments' => array(
            'male' => array('optimal_min' => 100, 'optimal_max' => 300),
            'female' => array('optimal_min' => 100, 'optimal_max' => 300),
        ),
        'clinical_significance' => 'Ghrelin is the hunger hormone that stimulates appetite. Elevated levels can lead to increased food intake and weight gain.',
        'risk_factors' => array('Poor sleep', 'Stress', 'Irregular meal timing', 'Low protein diet', 'Chronic dieting'),
        'optimization_recommendations' => array('Adequate sleep', 'Regular meal timing', 'High-protein diet', 'Stress management', 'Avoid chronic dieting'),
        'flag_criteria' => array(
            'symptom_triggers' => array('increased_hunger', 'difficulty_satiety', 'weight_gain', 'mood_changes'),
            'range_triggers' => array('above_400_pg_ml' => 'moderate', 'above_600_pg_ml' => 'high', 'below_80_pg_ml' => 'moderate', 'below_50_pg_ml' => 'high'),
        ),
        'scoring_algorithm' => array('optimal_score' => 10, 'suboptimal_score' => 7, 'poor_score' => 4, 'critical_score' => 1),
        'target_setting' => array(
            'improvement_targets' => array('Maintain ghrelin 100-300 pg/mL', 'Optimize appetite control'),
            'timeframes' => array('immediate' => '1 week', 'short_term' => '1 month', 'long_term' => '3-6 months'),
        ),
        'sources' => array(
            'primary' => 'Obesity Society 2023 Ghrelin Guidelines',
            'secondary' => array('https://www.ahealthacademy.com/biomarkers/', 'Obesity 2023: Ghrelin Assessment', 'J Clin Endocrinol Metab 2023: Hunger Regulation'),
            'evidence_level' => 'A',
        ),
    ),
    'adiponectin' => array(
        'display_name' => 'Adiponectin',
        'unit' => 'μg/mL',
        'description' => 'Anti-inflammatory hormone from fat cells improving insulin sensitivity',
        'ranges' => array(
            'optimal_min' => 5,
            'optimal_max' => 30,
            'normal_min' => 3,
            'normal_max' => 40,
            'critical_min' => 2,
            'critical_max' => 50,
        ),
        'age_adjustments' => array(
            'young' => array('optimal_min' => 5, 'optimal_max' => 30),
            'adult' => array('optimal_min' => 5, 'optimal_max' => 30),
            'senior' => array('optimal_min' => 4, 'optimal_max' => 25),
        ),
        'gender_adjustments' => array(
            'male' => array('optimal_min' => 5, 'optimal_max' => 30),
            'female' => array('optimal_min' => 6, 'optimal_max' => 35),
        ),
        'clinical_significance' => 'Adiponectin is an anti-inflammatory hormone that improves insulin sensitivity and metabolic health. Higher levels are associated with better health outcomes.',
        'risk_factors' => array('Obesity', 'Sedentary lifestyle', 'Poor diet', 'Inflammation', 'Metabolic syndrome'),
        'optimization_recommendations' => array('Weight loss', 'Regular exercise', 'Anti-inflammatory diet', 'Omega-3 supplementation', 'Stress management'),
        'flag_criteria' => array(
            'symptom_triggers' => array('insulin_resistance', 'inflammation', 'metabolic_symptoms', 'fatigue'),
            'range_triggers' => array('below_3_ug_ml' => 'moderate', 'below_2_ug_ml' => 'high', 'above_40_ug_ml' => 'moderate', 'above_50_ug_ml' => 'high'),
        ),
        'scoring_algorithm' => array('optimal_score' => 10, 'suboptimal_score' => 7, 'poor_score' => 4, 'critical_score' => 1),
        'target_setting' => array(
            'improvement_targets' => array('Maintain adiponectin 5-30 μg/mL', 'Optimize metabolic health'),
            'timeframes' => array('immediate' => '1 week', 'short_term' => '1 month', 'long_term' => '3-6 months'),
        ),
        'sources' => array(
            'primary' => 'Obesity Society 2023 Adiponectin Guidelines',
            'secondary' => array('https://www.ahealthacademy.com/biomarkers/', 'Obesity 2023: Adiponectin Assessment', 'J Clin Endocrinol Metab 2023: Metabolic Health'),
            'evidence_level' => 'A',
        ),
    ),
    'one_five_ag' => array(
        'display_name' => '1,5-Anhydroglucitol',
        'unit' => 'μg/mL',
        'description' => 'Short-term glucose control marker reflecting post-meal blood sugar spikes',
        'ranges' => array(
            'optimal_min' => 10,
            'optimal_max' => 35,
            'normal_min' => 8,
            'normal_max' => 40,
            'critical_min' => 5,
            'critical_max' => 50,
        ),
        'age_adjustments' => array(
            'young' => array('optimal_min' => 10, 'optimal_max' => 35),
            'adult' => array('optimal_min' => 10, 'optimal_max' => 35),
            'senior' => array('optimal_min' => 8, 'optimal_max' => 30),
        ),
        'gender_adjustments' => array(
            'male' => array('optimal_min' => 10, 'optimal_max' => 35),
            'female' => array('optimal_min' => 10, 'optimal_max' => 35),
        ),
        'clinical_significance' => '1,5-AG reflects short-term glucose control and post-meal blood sugar spikes. Lower levels indicate better glucose management.',
        'risk_factors' => array('High-carbohydrate diet', 'Sedentary lifestyle', 'Obesity', 'Poor meal timing', 'Stress'),
        'optimization_recommendations' => array('Low-glycemic diet', 'Regular exercise', 'Meal timing', 'Portion control', 'Stress management'),
        'flag_criteria' => array(
            'symptom_triggers' => array('post_meal_fatigue', 'energy_crashes', 'increased_hunger', 'mood_swings'),
            'range_triggers' => array('above_40_ug_ml' => 'moderate', 'above_50_ug_ml' => 'high', 'below_8_ug_ml' => 'moderate', 'below_5_ug_ml' => 'high'),
        ),
        'scoring_algorithm' => array('optimal_score' => 10, 'suboptimal_score' => 7, 'poor_score' => 4, 'critical_score' => 1),
        'target_setting' => array(
            'improvement_targets' => array('Maintain 1,5-AG 10-35 μg/mL', 'Optimize short-term glucose control'),
            'timeframes' => array('immediate' => '1 week', 'short_term' => '1 month', 'long_term' => '3-6 months'),
        ),
        'sources' => array(
            'primary' => 'ADA 2023 Postprandial Glucose Guidelines',
            'secondary' => array('https://www.ahealthacademy.com/biomarkers/', 'Diabetes Care 2023: 1,5-AG Assessment', 'J Clin Endocrinol Metab 2023: Short-term Glucose Control'),
            'evidence_level' => 'A',
        ),
    ),
    'weight' => array(
        'display_name' => 'Body Weight',
        'unit' => 'lbs',
        'description' => 'Total body weight indicating overall health and metabolic status',
        'ranges' => array(
            'optimal_min' => 100,
            'optimal_max' => 220,
            'normal_min' => 88,
            'normal_max' => 264,
            'critical_min' => 77,
            'critical_max' => 330,
        ),
        'age_adjustments' => array(
            'young' => array('optimal_min' => 100, 'optimal_max' => 220),
            'adult' => array('optimal_min' => 100, 'optimal_max' => 220),
            'senior' => array('optimal_min' => 110, 'optimal_max' => 209),
        ),
        'gender_adjustments' => array(
            'male' => array('optimal_min' => 121, 'optimal_max' => 220),
            'female' => array('optimal_min' => 99, 'optimal_max' => 187),
        ),
        'clinical_significance' => 'Body weight is a fundamental health indicator that affects metabolism, cardiovascular health, and overall well-being.',
        'risk_factors' => array('Poor diet', 'Sedentary lifestyle', 'Genetics', 'Medications', 'Stress', 'Sleep disorders'),
        'optimization_recommendations' => array('Balanced diet', 'Regular exercise', 'Portion control', 'Adequate sleep', 'Stress management'),
        'flag_criteria' => array(
            'symptom_triggers' => array('fatigue', 'joint_pain', 'breathing_difficulty', 'mobility_issues'),
            'range_triggers' => array('above_264_lbs' => 'moderate', 'above_330_lbs' => 'high', 'below_88_lbs' => 'moderate', 'below_77_lbs' => 'high'),
        ),
        'scoring_algorithm' => array('optimal_score' => 10, 'suboptimal_score' => 7, 'poor_score' => 4, 'critical_score' => 1),
        'target_setting' => array(
            'improvement_targets' => array('Maintain healthy weight range', 'Optimize body composition'),
            'timeframes' => array('immediate' => '1 week', 'short_term' => '1 month', 'long_term' => '3-6 months'),
        ),
        'sources' => array(
            'primary' => 'Obesity Society 2023 Weight Management Guidelines',
            'secondary' => array('https://www.ahealthacademy.com/biomarkers/', 'Obesity 2023: Weight Assessment', 'J Clin Endocrinol Metab 2023: Body Weight'),
            'evidence_level' => 'A',
        ),
    ),
    'bmi' => array(
        'display_name' => 'Body Mass Index',
        'unit' => 'kg/m²',
        'description' => 'Height-to-weight ratio indicating body composition and health risk',
        'ranges' => array(
            'optimal_min' => 18.5,
            'optimal_max' => 24.9,
            'normal_min' => 18.5,
            'normal_max' => 29.9,
            'critical_min' => 16.0,
            'critical_max' => 40.0,
        ),
        'age_adjustments' => array(
            'young' => array('optimal_min' => 18.5, 'optimal_max' => 24.9),
            'adult' => array('optimal_min' => 18.5, 'optimal_max' => 24.9),
            'senior' => array('optimal_min' => 20.0, 'optimal_max' => 27.0),
        ),
        'gender_adjustments' => array(
            'male' => array('optimal_min' => 18.5, 'optimal_max' => 24.9),
            'female' => array('optimal_min' => 18.5, 'optimal_max' => 24.9),
        ),
        'clinical_significance' => 'BMI is a screening tool for weight categories that may lead to health problems. It correlates with body fat and health risks.',
        'risk_factors' => array('Poor diet', 'Sedentary lifestyle', 'Genetics', 'Medications', 'Stress', 'Sleep disorders'),
        'optimization_recommendations' => array('Balanced diet', 'Regular exercise', 'Portion control', 'Adequate sleep', 'Stress management'),
        'flag_criteria' => array(
            'symptom_triggers' => array('fatigue', 'joint_pain', 'breathing_difficulty', 'mobility_issues'),
            'range_triggers' => array('above_29_9_kg_m2' => 'moderate', 'above_40_kg_m2' => 'high', 'below_18_5_kg_m2' => 'moderate', 'below_16_kg_m2' => 'high'),
        ),
        'scoring_algorithm' => array('optimal_score' => 10, 'suboptimal_score' => 7, 'poor_score' => 4, 'critical_score' => 1),
        'target_setting' => array(
            'improvement_targets' => array('Maintain BMI 18.5-24.9 kg/m²', 'Optimize body composition'),
            'timeframes' => array('immediate' => '1 week', 'short_term' => '1 month', 'long_term' => '3-6 months'),
        ),
        'sources' => array(
            'primary' => 'Obesity Society 2023 BMI Guidelines',
            'secondary' => array('https://www.ahealthacademy.com/biomarkers/', 'Obesity 2023: BMI Assessment', 'J Clin Endocrinol Metab 2023: Body Composition'),
            'evidence_level' => 'A',
        ),
    ),
    'body_fat_percent' => array(
        'display_name' => 'Body Fat Percentage',
        'unit' => '%',
        'description' => 'Percentage of body weight composed of fat tissue',
        'ranges' => array(
            'optimal_min' => 10,
            'optimal_max' => 25,
            'normal_min' => 8,
            'normal_max' => 30,
            'critical_min' => 5,
            'critical_max' => 40,
        ),
        'age_adjustments' => array(
            'young' => array('optimal_min' => 10, 'optimal_max' => 25),
            'adult' => array('optimal_min' => 10, 'optimal_max' => 25),
            'senior' => array('optimal_min' => 15, 'optimal_max' => 30),
        ),
        'gender_adjustments' => array(
            'male' => array('optimal_min' => 10, 'optimal_max' => 20),
            'female' => array('optimal_min' => 18, 'optimal_max' => 28),
        ),
        'clinical_significance' => 'Body fat percentage is a more accurate indicator of health than weight alone. It affects metabolism, hormone production, and overall health.',
        'risk_factors' => array('Poor diet', 'Sedentary lifestyle', 'Genetics', 'Age', 'Hormonal imbalances'),
        'optimization_recommendations' => array('Strength training', 'Cardiovascular exercise', 'Balanced diet', 'Adequate protein', 'Regular monitoring'),
        'flag_criteria' => array(
            'symptom_triggers' => array('fatigue', 'low_energy', 'metabolic_symptoms', 'hormonal_imbalances'),
            'range_triggers' => array('above_30_percent' => 'moderate', 'above_40_percent' => 'high', 'below_8_percent' => 'moderate', 'below_5_percent' => 'high'),
        ),
        'scoring_algorithm' => array('optimal_score' => 10, 'suboptimal_score' => 7, 'poor_score' => 4, 'critical_score' => 1),
        'target_setting' => array(
            'improvement_targets' => array('Maintain body fat 10-25%', 'Optimize body composition'),
            'timeframes' => array('immediate' => '1 week', 'short_term' => '1 month', 'long_term' => '3-6 months'),
        ),
        'sources' => array(
            'primary' => 'ACSM 2023 Body Composition Guidelines',
            'secondary' => array('https://www.ahealthacademy.com/biomarkers/', 'Obesity 2023: Body Fat Assessment', 'J Clin Endocrinol Metab 2023: Body Composition'),
            'evidence_level' => 'A',
        ),
    ),
    'waist_measurement' => array(
        'display_name' => 'Waist Circumference',
        'unit' => 'cm',
        'description' => 'Waist measurement indicating abdominal fat and metabolic health',
        'ranges' => array(
            'optimal_min' => 70,
            'optimal_max' => 90,
            'normal_min' => 65,
            'normal_max' => 100,
            'critical_min' => 60,
            'critical_max' => 120,
        ),
        'age_adjustments' => array(
            'young' => array('optimal_min' => 70, 'optimal_max' => 90),
            'adult' => array('optimal_min' => 70, 'optimal_max' => 90),
            'senior' => array('optimal_min' => 75, 'optimal_max' => 95),
        ),
        'gender_adjustments' => array(
            'male' => array('optimal_min' => 80, 'optimal_max' => 95),
            'female' => array('optimal_min' => 70, 'optimal_max' => 85),
        ),
        'clinical_significance' => 'Waist circumference is a key indicator of abdominal fat and metabolic health. It correlates with cardiovascular disease and diabetes risk.',
        'risk_factors' => array('Poor diet', 'Sedentary lifestyle', 'Stress', 'Poor sleep', 'Hormonal imbalances'),
        'optimization_recommendations' => array('Core exercises', 'Cardiovascular exercise', 'Balanced diet', 'Stress management', 'Adequate sleep'),
        'flag_criteria' => array(
            'symptom_triggers' => array('metabolic_symptoms', 'cardiovascular_risk', 'insulin_resistance', 'fatigue'),
            'range_triggers' => array('above_100_cm' => 'moderate', 'above_120_cm' => 'high', 'below_65_cm' => 'moderate', 'below_60_cm' => 'high'),
        ),
        'scoring_algorithm' => array('optimal_score' => 10, 'suboptimal_score' => 7, 'poor_score' => 4, 'critical_score' => 1),
        'target_setting' => array(
            'improvement_targets' => array('Maintain waist circumference 70-90 cm', 'Reduce abdominal fat'),
            'timeframes' => array('immediate' => '1 week', 'short_term' => '1 month', 'long_term' => '3-6 months'),
        ),
        'sources' => array(
            'primary' => 'ACSM 2023 Anthropometric Guidelines',
            'secondary' => array('https://www.ahealthacademy.com/biomarkers/', 'Obesity 2023: Waist Assessment', 'J Clin Endocrinol Metab 2023: Abdominal Fat'),
            'evidence_level' => 'A',
        ),
    ),
    'neck_measurement' => array(
        'display_name' => 'Neck Circumference',
        'unit' => 'cm',
        'description' => 'Neck measurement indicating upper body fat and sleep apnea risk',
        'ranges' => array(
            'optimal_min' => 30,
            'optimal_max' => 40,
            'normal_min' => 28,
            'normal_max' => 42,
            'critical_min' => 25,
            'critical_max' => 45,
        ),
        'age_adjustments' => array(
            'young' => array('optimal_min' => 30, 'optimal_max' => 40),
            'adult' => array('optimal_min' => 30, 'optimal_max' => 40),
            'senior' => array('optimal_min' => 32, 'optimal_max' => 42),
        ),
        'gender_adjustments' => array(
            'male' => array('optimal_min' => 35, 'optimal_max' => 42),
            'female' => array('optimal_min' => 30, 'optimal_max' => 38),
        ),
        'clinical_significance' => 'Neck circumference is associated with upper body fat, sleep apnea risk, and cardiovascular health. It is a simple but effective health indicator.',
        'risk_factors' => array('Obesity', 'Poor sleep', 'Snoring', 'Sleep apnea', 'Cardiovascular disease'),
        'optimization_recommendations' => array('Weight management', 'Sleep hygiene', 'Cardiovascular exercise', 'Stress management', 'Medical evaluation if needed'),
        'flag_criteria' => array(
            'symptom_triggers' => array('sleep_apnea', 'snoring', 'fatigue', 'breathing_difficulty'),
            'range_triggers' => array('above_42_cm' => 'moderate', 'above_45_cm' => 'high', 'below_28_cm' => 'moderate', 'below_25_cm' => 'high'),
        ),
        'scoring_algorithm' => array('optimal_score' => 10, 'suboptimal_score' => 7, 'poor_score' => 4, 'critical_score' => 1),
        'target_setting' => array(
            'improvement_targets' => array('Maintain neck circumference 30-40 cm', 'Optimize upper body health'),
            'timeframes' => array('immediate' => '1 week', 'short_term' => '1 month', 'long_term' => '3-6 months'),
        ),
        'sources' => array(
            'primary' => 'ACSM 2023 Anthropometric Guidelines',
            'secondary' => array('https://www.ahealthacademy.com/biomarkers/', 'Obesity 2023: Neck Assessment', 'Sleep Med 2023: Neck Circumference'),
            'evidence_level' => 'A',
        ),
    ),
    'bioelectrical_impedance_or_caliper' => array(
        'display_name' => 'Body Composition Measurement Method',
        'unit' => 'Method',
        'description' => 'Method used to measure body composition and fat percentage',
        'ranges' => array(
            'optimal_min' => 1,
            'optimal_max' => 1,
            'normal_min' => 1,
            'normal_max' => 3,
            'critical_min' => 1,
            'critical_max' => 4,
        ),
        'age_adjustments' => array(
            'young' => array('optimal_min' => 1, 'optimal_max' => 1),
            'adult' => array('optimal_min' => 1, 'optimal_max' => 1),
            'senior' => array('optimal_min' => 1, 'optimal_max' => 1),
        ),
        'gender_adjustments' => array(
            'male' => array('optimal_min' => 1, 'optimal_max' => 1),
            'female' => array('optimal_min' => 1, 'optimal_max' => 1),
        ),
        'clinical_significance' => 'The method used to measure body composition affects accuracy and reliability. Consistent measurement methods are essential for tracking progress.',
        'risk_factors' => array('Inconsistent measurement', 'Poor technique', 'Equipment quality', 'Operator error'),
        'optimization_recommendations' => array('Consistent measurement method', 'Proper technique', 'Quality equipment', 'Regular calibration'),
        'flag_criteria' => array(
            'symptom_triggers' => array('inconsistent_measurements', 'poor_accuracy', 'tracking_difficulties'),
            'range_triggers' => array('method_1' => 'optimal', 'method_2' => 'suboptimal', 'method_3' => 'poor'),
        ),
        'scoring_algorithm' => array('optimal_score' => 10, 'suboptimal_score' => 7, 'poor_score' => 4, 'critical_score' => 1),
        'target_setting' => array(
            'improvement_targets' => array('Use consistent measurement method', 'Optimize measurement accuracy'),
            'timeframes' => array('immediate' => '1 week', 'short_term' => '1 month', 'long_term' => '3-6 months'),
        ),
        'sources' => array(
            'primary' => 'ACSM 2023 Body Composition Guidelines',
            'secondary' => array('https://www.ahealthacademy.com/biomarkers/', 'Obesity 2023: Measurement Methods', 'J Clin Endocrinol Metab 2023: Body Composition'),
            'evidence_level' => 'A',
        ),
    ),
    'kg' => array(
        'display_name' => 'Weight Unit (Kilograms)',
        'unit' => 'kg',
        'description' => 'Standard unit for weight measurement in the metric system',
        'ranges' => array(
            'optimal_min' => 1,
            'optimal_max' => 1,
            'normal_min' => 1,
            'normal_max' => 1,
            'critical_min' => 1,
            'critical_max' => 1,
        ),
        'age_adjustments' => array(
            'young' => array('optimal_min' => 1, 'optimal_max' => 1),
            'adult' => array('optimal_min' => 1, 'optimal_max' => 1),
            'senior' => array('optimal_min' => 1, 'optimal_max' => 1),
        ),
        'gender_adjustments' => array(
            'male' => array('optimal_min' => 1, 'optimal_max' => 1),
            'female' => array('optimal_min' => 1, 'optimal_max' => 1),
        ),
        'clinical_significance' => 'Kilograms are the standard unit for weight measurement in the metric system, providing consistent and accurate weight tracking.',
        'risk_factors' => array('Unit conversion errors', 'Inconsistent measurement', 'Equipment calibration'),
        'optimization_recommendations' => array('Consistent unit usage', 'Proper equipment calibration', 'Regular measurement validation'),
        'flag_criteria' => array(
            'symptom_triggers' => array('measurement_errors', 'unit_confusion', 'tracking_difficulties'),
            'range_triggers' => array('unit_1' => 'optimal', 'unit_2' => 'suboptimal'),
        ),
        'scoring_algorithm' => array('optimal_score' => 10, 'suboptimal_score' => 7, 'poor_score' => 4, 'critical_score' => 1),
        'target_setting' => array(
            'improvement_targets' => array('Use consistent weight units', 'Optimize measurement accuracy'),
            'timeframes' => array('immediate' => '1 week', 'short_term' => '1 month', 'long_term' => '3-6 months'),
        ),
        'sources' => array(
            'primary' => 'ACSM 2023 Measurement Guidelines',
            'secondary' => array('https://www.ahealthacademy.com/biomarkers/', 'Obesity 2023: Measurement Standards', 'J Clin Endocrinol Metab 2023: Weight Measurement'),
            'evidence_level' => 'A',
        ),
    ),
); 