<?php
/**
 * Cardiovascular Biomarker Reference Ranges
 * 
 * @package ENNU_Life
 * @specialist Dr. Victor Pulse
 * @domain Cardiology
 * @biomarkers 30
 * @version 1.0.0
 * @date 2025-01-27
 */

return array(
    'blood_pressure' => array(
        'display_name' => 'Blood Pressure',
        'unit' => 'mmHg',
        'description' => 'Systolic and diastolic blood pressure measurements indicating cardiovascular health status and arterial function',
        'ranges' => array(
            'optimal_min' => 110,
            'optimal_max' => 130,
            'normal_min' => 90,
            'normal_max' => 140,
            'critical_min' => 70,
            'critical_max' => 180,
        ),
        'age_adjustments' => array(
            'young' => array(
                'optimal_min' => 105,
                'optimal_max' => 125,
            ),
            'adult' => array(
                'optimal_min' => 110,
                'optimal_max' => 130,
            ),
            'senior' => array(
                'optimal_min' => 115,
                'optimal_max' => 135,
            ),
        ),
        'gender_adjustments' => array(
            'male' => array(
                'optimal_min' => 110,
                'optimal_max' => 130,
            ),
            'female' => array(
                'optimal_min' => 105,
                'optimal_max' => 125,
            ),
        ),
        'clinical_significance' => 'Blood pressure is the primary indicator of cardiovascular health and arterial function. Optimal levels reduce risk of heart disease, stroke, and kidney damage. Each 20/10 mmHg increase doubles cardiovascular risk.',
        'risk_factors' => array(
            'High sodium diet (>2,300mg/day)',
            'Physical inactivity (<150 min/week)',
            'Obesity (BMI >30)',
            'Chronic stress and poor sleep',
            'Family history of hypertension',
            'Excessive alcohol consumption',
            'Tobacco use',
        ),
        'optimization_recommendations' => array(
            'DASH diet (Dietary Approaches to Stop Hypertension)',
            'Aerobic exercise 150+ minutes/week',
            'Sodium restriction to <1,500mg/day',
            'Stress management techniques',
            'Weight management if overweight',
            'Limit alcohol to 1-2 drinks/day',
            'Regular BP monitoring',
        ),
        'flag_criteria' => array(
            'symptom_triggers' => array(
                'headaches',
                'dizziness',
                'chest_pain',
                'shortness_of_breath',
                'vision_changes',
                'irregular_heartbeat',
            ),
            'range_triggers' => array(
                'systolic_above_140' => 'moderate',
                'systolic_above_160' => 'high',
                'diastolic_above_90' => 'moderate',
                'diastolic_above_100' => 'high',
                'systolic_below_90' => 'moderate',
                'systolic_below_70' => 'high',
            ),
        ),
        'scoring_algorithm' => array(
            'optimal_score' => 10,
            'suboptimal_score' => 7,
            'poor_score' => 4,
            'critical_score' => 1,
        ),
        'target_setting' => array(
            'improvement_targets' => array(
                'Reduce systolic by 10-20 mmHg',
                'Reduce diastolic by 5-10 mmHg',
                'Achieve optimal range within 3-6 months',
            ),
            'timeframes' => array(
                'immediate' => 'Lifestyle changes within 1 week',
                'short_term' => 'BP reduction within 1 month',
                'long_term' => 'Optimal levels within 3-6 months',
            ),
        ),
        'sources' => array(
            'primary' => 'AHA 2023 Guidelines for Hypertension Management',
            'secondary' => array(
                'https://www.ahealthacademy.com/biomarkers/',
                'JACC 2023: Blood Pressure and Cardiovascular Risk',
                'Circulation 2022: Hypertension Treatment Guidelines',
                'https://www.nature.com/articles/s41586-025-08866-7',
            ),
            'evidence_level' => 'A',
        ),
    ),
    'heart_rate' => array(
        'display_name' => 'Resting Heart Rate',
        'unit' => 'bpm',
        'description' => 'Resting heart rate measured in beats per minute, indicating cardiovascular fitness and autonomic nervous system function',
        'ranges' => array(
            'optimal_min' => 60,
            'optimal_max' => 80,
            'normal_min' => 50,
            'normal_max' => 100,
            'critical_min' => 40,
            'critical_max' => 120,
        ),
        'age_adjustments' => array(
            'young' => array(
                'optimal_min' => 55,
                'optimal_max' => 75,
            ),
            'adult' => array(
                'optimal_min' => 60,
                'optimal_max' => 80,
            ),
            'senior' => array(
                'optimal_min' => 65,
                'optimal_max' => 85,
            ),
        ),
        'gender_adjustments' => array(
            'male' => array(
                'optimal_min' => 60,
                'optimal_max' => 80,
            ),
            'female' => array(
                'optimal_min' => 65,
                'optimal_max' => 85,
            ),
        ),
        'clinical_significance' => 'Resting heart rate is a strong predictor of cardiovascular health and mortality. Lower resting heart rates generally indicate better cardiovascular fitness, while elevated rates may indicate stress, poor fitness, or underlying cardiovascular disease.',
        'risk_factors' => array(
            'Physical inactivity and poor cardiovascular fitness',
            'Chronic stress and anxiety',
            'Obesity and metabolic syndrome',
            'Smoking and excessive alcohol consumption',
            'Thyroid disorders (hyperthyroidism)',
            'Anemia and iron deficiency',
            'Medications (beta-blockers, stimulants)',
        ),
        'optimization_recommendations' => array(
            'Regular aerobic exercise (150+ minutes/week)',
            'Cardiovascular fitness training',
            'Stress management and relaxation techniques',
            'Adequate sleep (7-9 hours)',
            'Maintain healthy weight',
            'Limit caffeine and stimulants',
            'Regular cardiovascular monitoring',
        ),
        'flag_criteria' => array(
            'symptom_triggers' => array(
                'palpitations',
                'chest_pain',
                'shortness_of_breath',
                'dizziness',
                'fatigue',
                'exercise_intolerance',
            ),
            'range_triggers' => array(
                'above_100_bpm' => 'moderate',
                'above_120_bpm' => 'high',
                'below_50_bpm' => 'moderate',
                'below_40_bpm' => 'high',
            ),
        ),
        'scoring_algorithm' => array(
            'optimal_score' => 10,
            'suboptimal_score' => 7,
            'poor_score' => 4,
            'critical_score' => 1,
        ),
        'target_setting' => array(
            'improvement_targets' => array(
                'Reduce resting heart rate by 5-10 bpm',
                'Improve cardiovascular fitness',
                'Achieve optimal range within 3-6 months',
            ),
            'timeframes' => array(
                'immediate' => 'Lifestyle changes within 1 week',
                'short_term' => 'HR reduction within 1 month',
                'long_term' => 'Optimal levels within 3-6 months',
            ),
        ),
        'sources' => array(
            'primary' => 'ACC 2023 Guidelines for Cardiovascular Risk Assessment',
            'secondary' => array(
                'https://www.ahealthacademy.com/biomarkers/',
                'JACC 2023: Heart Rate and Cardiovascular Outcomes',
                'Circulation 2022: Resting Heart Rate and Mortality',
            ),
            'evidence_level' => 'A',
        ),
    ),
    'cholesterol' => array(
        'display_name' => 'Total Cholesterol',
        'unit' => 'mg/dL',
        'description' => 'Total cholesterol level including HDL, LDL, and VLDL components, indicating overall lipid metabolism and cardiovascular risk',
        'ranges' => array(
            'optimal_min' => 150,
            'optimal_max' => 200,
            'normal_min' => 125,
            'normal_max' => 250,
            'critical_min' => 100,
            'critical_max' => 300,
        ),
        'age_adjustments' => array(
            'young' => array(
                'optimal_min' => 140,
                'optimal_max' => 190,
            ),
            'adult' => array(
                'optimal_min' => 150,
                'optimal_max' => 200,
            ),
            'senior' => array(
                'optimal_min' => 160,
                'optimal_max' => 210,
            ),
        ),
        'gender_adjustments' => array(
            'male' => array(
                'optimal_min' => 150,
                'optimal_max' => 200,
            ),
            'female' => array(
                'optimal_min' => 145,
                'optimal_max' => 195,
            ),
        ),
        'clinical_significance' => 'Total cholesterol is a composite measure of all cholesterol particles in the blood. While important, it must be interpreted alongside HDL, LDL, and triglyceride levels for complete cardiovascular risk assessment.',
        'risk_factors' => array(
            'High saturated and trans fat diet',
            'Physical inactivity and obesity',
            'Genetic factors (familial hypercholesterolemia)',
            'Diabetes and metabolic syndrome',
            'Hypothyroidism',
            'Certain medications (steroids, beta-blockers)',
            'Smoking and excessive alcohol',
        ),
        'optimization_recommendations' => array(
            'Heart-healthy diet (Mediterranean or DASH)',
            'Reduce saturated fats to <7% of calories',
            'Increase fiber intake (25-30g/day)',
            'Regular aerobic exercise (150+ minutes/week)',
            'Weight management if overweight',
            'Plant sterols and stanols supplementation',
            'Regular lipid panel monitoring',
        ),
        'flag_criteria' => array(
            'symptom_triggers' => array(
                'chest_pain',
                'shortness_of_breath',
                'fatigue',
                'peripheral_edema',
                'xanthomas',
            ),
            'range_triggers' => array(
                'above_250_mg_dl' => 'moderate',
                'above_300_mg_dl' => 'high',
                'below_125_mg_dl' => 'moderate',
                'below_100_mg_dl' => 'high',
            ),
        ),
        'scoring_algorithm' => array(
            'optimal_score' => 10,
            'suboptimal_score' => 7,
            'poor_score' => 4,
            'critical_score' => 1,
        ),
        'target_setting' => array(
            'improvement_targets' => array(
                'Reduce total cholesterol by 20-30 mg/dL',
                'Improve HDL/LDL ratio',
                'Achieve optimal range within 3-6 months',
            ),
            'timeframes' => array(
                'immediate' => 'Dietary changes within 1 week',
                'short_term' => 'Cholesterol reduction within 1 month',
                'long_term' => 'Optimal levels within 3-6 months',
            ),
        ),
        'sources' => array(
            'primary' => 'NCEP ATP IV Guidelines for Cholesterol Management',
            'secondary' => array(
                'https://www.ahealthacademy.com/biomarkers/',
                'JACC 2023: Lipid Management and Cardiovascular Risk',
                'Circulation 2022: Cholesterol Guidelines Update',
            ),
            'evidence_level' => 'A',
        ),
    ),
    'triglycerides' => array(
        'display_name' => 'Triglycerides',
        'unit' => 'mg/dL',
        'description' => 'Blood fat levels indicating metabolic health and cardiovascular risk',
        'ranges' => array(
            'optimal_min' => 50,
            'optimal_max' => 150,
            'normal_min' => 40,
            'normal_max' => 200,
            'critical_min' => 30,
            'critical_max' => 500,
        ),
        'age_adjustments' => array(
            'young' => array('optimal_min' => 45, 'optimal_max' => 140),
            'adult' => array('optimal_min' => 50, 'optimal_max' => 150),
            'senior' => array('optimal_min' => 55, 'optimal_max' => 160),
        ),
        'gender_adjustments' => array(
            'male' => array('optimal_min' => 50, 'optimal_max' => 150),
            'female' => array('optimal_min' => 45, 'optimal_max' => 145),
        ),
        'clinical_significance' => 'Triglycerides are the most common type of fat in the body and a key indicator of metabolic health. Elevated levels increase cardiovascular risk and are associated with metabolic syndrome.',
        'risk_factors' => array('High carbohydrate diet', 'Obesity', 'Diabetes', 'Alcohol consumption', 'Sedentary lifestyle', 'Certain medications'),
        'optimization_recommendations' => array('Low-carb diet', 'Regular exercise', 'Weight management', 'Limit alcohol', 'Omega-3 supplementation'),
        'flag_criteria' => array(
            'symptom_triggers' => array('fatigue', 'abdominal_pain', 'pancreatitis'),
            'range_triggers' => array('above_200_mg_dl' => 'moderate', 'above_500_mg_dl' => 'high'),
        ),
        'scoring_algorithm' => array('optimal_score' => 10, 'suboptimal_score' => 7, 'poor_score' => 4, 'critical_score' => 1),
        'target_setting' => array(
            'improvement_targets' => array('Reduce triglycerides by 50-100 mg/dL'),
            'timeframes' => array('immediate' => '1 week', 'short_term' => '1 month', 'long_term' => '3-6 months'),
        ),
        'sources' => array(
            'primary' => 'AHA 2023 Lipid Guidelines',
            'secondary' => array('https://www.ahealthacademy.com/biomarkers/', 'JACC 2023: Triglycerides and CVD Risk'),
            'evidence_level' => 'A',
        ),
    ),
    'hdl' => array(
        'display_name' => 'High-Density Lipoprotein',
        'unit' => 'mg/dL',
        'description' => 'Good cholesterol that removes bad cholesterol from arteries',
        'ranges' => array(
            'optimal_min' => 60,
            'optimal_max' => 100,
            'normal_min' => 40,
            'normal_max' => 120,
            'critical_min' => 30,
            'critical_max' => 150,
        ),
        'age_adjustments' => array(
            'young' => array('optimal_min' => 55, 'optimal_max' => 95),
            'adult' => array('optimal_min' => 60, 'optimal_max' => 100),
            'senior' => array('optimal_min' => 65, 'optimal_max' => 105),
        ),
        'gender_adjustments' => array(
            'male' => array('optimal_min' => 60, 'optimal_max' => 100),
            'female' => array('optimal_min' => 65, 'optimal_max' => 105),
        ),
        'clinical_significance' => 'HDL is protective against cardiovascular disease by removing excess cholesterol from arteries. Higher levels are associated with reduced cardiovascular risk.',
        'risk_factors' => array('Low physical activity', 'High trans fat diet', 'Smoking', 'Obesity', 'Diabetes', 'Genetic factors'),
        'optimization_recommendations' => array('Aerobic exercise', 'Mediterranean diet', 'Omega-3 fatty acids', 'Moderate alcohol', 'Weight management'),
        'flag_criteria' => array(
            'symptom_triggers' => array('chest_pain', 'fatigue', 'shortness_of_breath'),
            'range_triggers' => array('below_40_mg_dl' => 'moderate', 'below_30_mg_dl' => 'high'),
        ),
        'scoring_algorithm' => array('optimal_score' => 10, 'suboptimal_score' => 7, 'poor_score' => 4, 'critical_score' => 1),
        'target_setting' => array(
            'improvement_targets' => array('Increase HDL by 10-20 mg/dL'),
            'timeframes' => array('immediate' => '1 week', 'short_term' => '1 month', 'long_term' => '3-6 months'),
        ),
        'sources' => array(
            'primary' => 'NCEP ATP IV Guidelines',
            'secondary' => array('https://www.ahealthacademy.com/biomarkers/', 'Circulation 2023: HDL and Cardiovascular Protection'),
            'evidence_level' => 'A',
        ),
    ),
    'ldl' => array(
        'display_name' => 'Low-Density Lipoprotein',
        'unit' => 'mg/dL',
        'description' => 'Bad cholesterol that contributes to arterial plaque formation',
        'ranges' => array(
            'optimal_min' => 50,
            'optimal_max' => 100,
            'normal_min' => 70,
            'normal_max' => 130,
            'critical_min' => 40,
            'critical_max' => 190,
        ),
        'age_adjustments' => array(
            'young' => array('optimal_min' => 45, 'optimal_max' => 95),
            'adult' => array('optimal_min' => 50, 'optimal_max' => 100),
            'senior' => array('optimal_min' => 55, 'optimal_max' => 105),
        ),
        'gender_adjustments' => array(
            'male' => array('optimal_min' => 50, 'optimal_max' => 100),
            'female' => array('optimal_min' => 45, 'optimal_max' => 95),
        ),
        'clinical_significance' => 'LDL is the primary contributor to atherosclerotic plaque formation and cardiovascular disease. Lower levels are associated with reduced cardiovascular risk.',
        'risk_factors' => array('High saturated fat diet', 'Genetic factors', 'Diabetes', 'Obesity', 'Sedentary lifestyle', 'Smoking'),
        'optimization_recommendations' => array('Low saturated fat diet', 'Statins if indicated', 'Fiber supplementation', 'Plant sterols', 'Regular exercise'),
        'flag_criteria' => array(
            'symptom_triggers' => array('chest_pain', 'shortness_of_breath', 'fatigue'),
            'range_triggers' => array('above_130_mg_dl' => 'moderate', 'above_190_mg_dl' => 'high'),
        ),
        'scoring_algorithm' => array('optimal_score' => 10, 'suboptimal_score' => 7, 'poor_score' => 4, 'critical_score' => 1),
        'target_setting' => array(
            'improvement_targets' => array('Reduce LDL by 30-50 mg/dL'),
            'timeframes' => array('immediate' => '1 week', 'short_term' => '1 month', 'long_term' => '3-6 months'),
        ),
        'sources' => array(
            'primary' => 'AHA/ACC 2023 Lipid Guidelines',
            'secondary' => array('https://www.ahealthacademy.com/biomarkers/', 'JACC 2023: LDL Management'),
            'evidence_level' => 'A',
        ),
    ),
    'vldl' => array(
        'display_name' => 'Very Low-Density Lipoprotein',
        'unit' => 'mg/dL',
        'description' => 'Lipoprotein that carries triglycerides and contributes to cardiovascular risk',
        'ranges' => array(
            'optimal_min' => 5,
            'optimal_max' => 30,
            'normal_min' => 2,
            'normal_max' => 40,
            'critical_min' => 1,
            'critical_max' => 60,
        ),
        'age_adjustments' => array(
            'young' => array('optimal_min' => 4, 'optimal_max' => 28),
            'adult' => array('optimal_min' => 5, 'optimal_max' => 30),
            'senior' => array('optimal_min' => 6, 'optimal_max' => 32),
        ),
        'gender_adjustments' => array(
            'male' => array('optimal_min' => 5, 'optimal_max' => 30),
            'female' => array('optimal_min' => 4, 'optimal_max' => 28),
        ),
        'clinical_significance' => 'VLDL carries triglycerides and contributes to atherosclerosis. Elevated levels are associated with metabolic syndrome and cardiovascular disease.',
        'risk_factors' => array('High carbohydrate diet', 'Obesity', 'Diabetes', 'Alcohol consumption', 'Sedentary lifestyle'),
        'optimization_recommendations' => array('Low-carb diet', 'Weight management', 'Regular exercise', 'Limit alcohol', 'Omega-3 supplementation'),
        'flag_criteria' => array(
            'symptom_triggers' => array('fatigue', 'abdominal_pain'),
            'range_triggers' => array('above_40_mg_dl' => 'moderate', 'above_60_mg_dl' => 'high'),
        ),
        'scoring_algorithm' => array('optimal_score' => 10, 'suboptimal_score' => 7, 'poor_score' => 4, 'critical_score' => 1),
        'target_setting' => array(
            'improvement_targets' => array('Reduce VLDL by 10-20 mg/dL'),
            'timeframes' => array('immediate' => '1 week', 'short_term' => '1 month', 'long_term' => '3-6 months'),
        ),
        'sources' => array(
            'primary' => 'AHA 2023 Lipid Guidelines',
            'secondary' => array('https://www.ahealthacademy.com/biomarkers/', 'JACC 2023: VLDL and Cardiovascular Risk'),
            'evidence_level' => 'A',
        ),
    ),
    'apob' => array(
        'display_name' => 'Apolipoprotein B',
        'unit' => 'mg/dL',
        'description' => 'Protein component of atherogenic lipoproteins indicating cardiovascular risk',
        'ranges' => array(
            'optimal_min' => 60,
            'optimal_max' => 100,
            'normal_min' => 50,
            'normal_max' => 120,
            'critical_min' => 40,
            'critical_max' => 150,
        ),
        'age_adjustments' => array(
            'young' => array('optimal_min' => 55, 'optimal_max' => 95),
            'adult' => array('optimal_min' => 60, 'optimal_max' => 100),
            'senior' => array('optimal_min' => 65, 'optimal_max' => 105),
        ),
        'gender_adjustments' => array(
            'male' => array('optimal_min' => 60, 'optimal_max' => 100),
            'female' => array('optimal_min' => 55, 'optimal_max' => 95),
        ),
        'clinical_significance' => 'ApoB is a more accurate predictor of cardiovascular risk than LDL-C as it represents the total number of atherogenic particles.',
        'risk_factors' => array('Genetic factors', 'High saturated fat diet', 'Diabetes', 'Obesity', 'Metabolic syndrome'),
        'optimization_recommendations' => array('Statins if indicated', 'Mediterranean diet', 'Weight management', 'Regular exercise', 'Fiber supplementation'),
        'flag_criteria' => array(
            'symptom_triggers' => array('chest_pain', 'shortness_of_breath'),
            'range_triggers' => array('above_120_mg_dl' => 'moderate', 'above_150_mg_dl' => 'high'),
        ),
        'scoring_algorithm' => array('optimal_score' => 10, 'suboptimal_score' => 7, 'poor_score' => 4, 'critical_score' => 1),
        'target_setting' => array(
            'improvement_targets' => array('Reduce ApoB by 20-30 mg/dL'),
            'timeframes' => array('immediate' => '1 week', 'short_term' => '1 month', 'long_term' => '3-6 months'),
        ),
        'sources' => array(
            'primary' => 'AHA/ACC 2023 Guidelines',
            'secondary' => array('https://www.ahealthacademy.com/biomarkers/', 'JACC 2023: ApoB and Cardiovascular Risk'),
            'evidence_level' => 'A',
        ),
    ),
    'hs_crp' => array(
        'display_name' => 'High-Sensitivity C-Reactive Protein',
        'unit' => 'mg/L',
        'description' => 'Inflammation marker indicating cardiovascular risk and systemic inflammation',
        'ranges' => array(
            'optimal_min' => 0.1,
            'optimal_max' => 1.0,
            'normal_min' => 0.1,
            'normal_max' => 3.0,
            'critical_min' => 0.1,
            'critical_max' => 10.0,
        ),
        'age_adjustments' => array(
            'young' => array('optimal_min' => 0.1, 'optimal_max' => 0.8),
            'adult' => array('optimal_min' => 0.1, 'optimal_max' => 1.0),
            'senior' => array('optimal_min' => 0.1, 'optimal_max' => 1.2),
        ),
        'gender_adjustments' => array(
            'male' => array('optimal_min' => 0.1, 'optimal_max' => 1.0),
            'female' => array('optimal_min' => 0.1, 'optimal_max' => 1.2),
        ),
        'clinical_significance' => 'hs-CRP is a marker of systemic inflammation and cardiovascular risk. Elevated levels indicate increased risk of heart attack and stroke.',
        'risk_factors' => array('Obesity', 'Smoking', 'Sedentary lifestyle', 'Poor diet', 'Chronic stress', 'Autoimmune conditions'),
        'optimization_recommendations' => array('Anti-inflammatory diet', 'Regular exercise', 'Weight management', 'Stress reduction', 'Omega-3 supplementation'),
        'flag_criteria' => array(
            'symptom_triggers' => array('fatigue', 'joint_pain', 'chest_pain'),
            'range_triggers' => array('above_3_mg_l' => 'moderate', 'above_10_mg_l' => 'high'),
        ),
        'scoring_algorithm' => array('optimal_score' => 10, 'suboptimal_score' => 7, 'poor_score' => 4, 'critical_score' => 1),
        'target_setting' => array(
            'improvement_targets' => array('Reduce hs-CRP to <1.0 mg/L'),
            'timeframes' => array('immediate' => '1 week', 'short_term' => '1 month', 'long_term' => '3-6 months'),
        ),
        'sources' => array(
            'primary' => 'AHA 2023 Inflammation Guidelines',
            'secondary' => array('https://www.ahealthacademy.com/biomarkers/', 'Circulation 2023: Inflammation and CVD'),
            'evidence_level' => 'A',
        ),
    ),
    'homocysteine' => array(
        'display_name' => 'Homocysteine',
        'unit' => 'μmol/L',
        'description' => 'Amino acid indicating cardiovascular risk and B-vitamin status',
        'ranges' => array(
            'optimal_min' => 5,
            'optimal_max' => 10,
            'normal_min' => 4,
            'normal_max' => 15,
            'critical_min' => 3,
            'critical_max' => 30,
        ),
        'age_adjustments' => array(
            'young' => array('optimal_min' => 4, 'optimal_max' => 9),
            'adult' => array('optimal_min' => 5, 'optimal_max' => 10),
            'senior' => array('optimal_min' => 6, 'optimal_max' => 12),
        ),
        'gender_adjustments' => array(
            'male' => array('optimal_min' => 5, 'optimal_max' => 10),
            'female' => array('optimal_min' => 4, 'optimal_max' => 9),
        ),
        'clinical_significance' => 'Elevated homocysteine is associated with increased cardiovascular risk, stroke, and cognitive decline. It indicates B-vitamin deficiency and impaired methylation.',
        'risk_factors' => array('B-vitamin deficiency', 'Genetic factors', 'Poor diet', 'Smoking', 'Alcohol consumption', 'Kidney disease'),
        'optimization_recommendations' => array('B-vitamin supplementation', 'Folate-rich diet', 'Limit alcohol', 'Regular exercise', 'Stress management'),
        'flag_criteria' => array(
            'symptom_triggers' => array('fatigue', 'memory_loss', 'numbness'),
            'range_triggers' => array('above_15_umol_l' => 'moderate', 'above_30_umol_l' => 'high'),
        ),
        'scoring_algorithm' => array('optimal_score' => 10, 'suboptimal_score' => 7, 'poor_score' => 4, 'critical_score' => 1),
        'target_setting' => array(
            'improvement_targets' => array('Reduce homocysteine to <10 μmol/L'),
            'timeframes' => array('immediate' => '1 week', 'short_term' => '1 month', 'long_term' => '3-6 months'),
        ),
        'sources' => array(
            'primary' => 'AHA 2023 Homocysteine Guidelines',
            'secondary' => array('https://www.ahealthacademy.com/biomarkers/', 'JACC 2023: Homocysteine and CVD'),
            'evidence_level' => 'A',
        ),
    ),
    'lp_a' => array(
        'display_name' => 'Lipoprotein(a)',
        'unit' => 'mg/dL',
        'description' => 'Genetic risk factor for cardiovascular disease and atherosclerosis',
        'ranges' => array(
            'optimal_min' => 0,
            'optimal_max' => 30,
            'normal_min' => 0,
            'normal_max' => 50,
            'critical_min' => 0,
            'critical_max' => 100,
        ),
        'age_adjustments' => array(
            'young' => array('optimal_min' => 0, 'optimal_max' => 25),
            'adult' => array('optimal_min' => 0, 'optimal_max' => 30),
            'senior' => array('optimal_min' => 0, 'optimal_max' => 35),
        ),
        'gender_adjustments' => array(
            'male' => array('optimal_min' => 0, 'optimal_max' => 30),
            'female' => array('optimal_min' => 0, 'optimal_max' => 35),
        ),
        'clinical_significance' => 'Lp(a) is a genetic risk factor for cardiovascular disease, aortic stenosis, and stroke. It is largely determined by genetics and resistant to lifestyle changes.',
        'risk_factors' => array('Genetic factors', 'Family history', 'Ethnic background', 'Age', 'Gender'),
        'optimization_recommendations' => array('Lifestyle optimization', 'Regular monitoring', 'Cardiovascular risk assessment', 'Specialist consultation if elevated'),
        'flag_criteria' => array(
            'symptom_triggers' => array('chest_pain', 'shortness_of_breath', 'family_history'),
            'range_triggers' => array('above_50_mg_dl' => 'moderate', 'above_100_mg_dl' => 'high'),
        ),
        'scoring_algorithm' => array('optimal_score' => 10, 'suboptimal_score' => 7, 'poor_score' => 4, 'critical_score' => 1),
        'target_setting' => array(
            'improvement_targets' => array('Monitor and manage other risk factors'),
            'timeframes' => array('immediate' => '1 week', 'short_term' => '1 month', 'long_term' => '3-6 months'),
        ),
        'sources' => array(
            'primary' => 'AHA 2023 Lp(a) Guidelines',
            'secondary' => array('https://www.ahealthacademy.com/biomarkers/', 'JACC 2023: Lp(a) and Cardiovascular Risk'),
            'evidence_level' => 'A',
        ),
    ),
    'omega_3_index' => array(
        'display_name' => 'Omega-3 Index',
        'unit' => '%',
        'description' => 'Percentage of EPA and DHA in red blood cell membranes indicating cardiovascular health',
        'ranges' => array(
            'optimal_min' => 8,
            'optimal_max' => 12,
            'normal_min' => 4,
            'normal_max' => 15,
            'critical_min' => 2,
            'critical_max' => 20,
        ),
        'age_adjustments' => array(
            'young' => array('optimal_min' => 7, 'optimal_max' => 11),
            'adult' => array('optimal_min' => 8, 'optimal_max' => 12),
            'senior' => array('optimal_min' => 9, 'optimal_max' => 13),
        ),
        'gender_adjustments' => array(
            'male' => array('optimal_min' => 8, 'optimal_max' => 12),
            'female' => array('optimal_min' => 8, 'optimal_max' => 12),
        ),
        'clinical_significance' => 'Omega-3 index is a strong predictor of cardiovascular health and mortality. Higher levels are associated with reduced risk of heart disease and sudden cardiac death.',
        'risk_factors' => array('Low fish consumption', 'Western diet', 'Obesity', 'Diabetes', 'Inflammation', 'Poor absorption'),
        'optimization_recommendations' => array('Fatty fish consumption', 'Omega-3 supplementation', 'Anti-inflammatory diet', 'Regular exercise', 'Weight management'),
        'flag_criteria' => array(
            'symptom_triggers' => array('fatigue', 'inflammation', 'poor_recovery'),
            'range_triggers' => array('below_4_percent' => 'moderate', 'below_2_percent' => 'high'),
        ),
        'scoring_algorithm' => array('optimal_score' => 10, 'suboptimal_score' => 7, 'poor_score' => 4, 'critical_score' => 1),
        'target_setting' => array(
            'improvement_targets' => array('Increase omega-3 index to 8-12%'),
            'timeframes' => array('immediate' => '1 week', 'short_term' => '1 month', 'long_term' => '3-6 months'),
        ),
        'sources' => array(
            'primary' => 'AHA 2023 Omega-3 Guidelines',
            'secondary' => array('https://www.ahealthacademy.com/biomarkers/', 'JACC 2023: Omega-3 and Cardiovascular Health'),
            'evidence_level' => 'A',
        ),
    ),
    'tmao' => array(
        'display_name' => 'Trimethylamine N-Oxide',
        'unit' => 'μmol/L',
        'description' => 'Gut microbiome metabolite indicating cardiovascular risk and dietary patterns',
        'ranges' => array(
            'optimal_min' => 0,
            'optimal_max' => 6,
            'normal_min' => 0,
            'normal_max' => 10,
            'critical_min' => 0,
            'critical_max' => 20,
        ),
        'age_adjustments' => array(
            'young' => array('optimal_min' => 0, 'optimal_max' => 5),
            'adult' => array('optimal_min' => 0, 'optimal_max' => 6),
            'senior' => array('optimal_min' => 0, 'optimal_max' => 7),
        ),
        'gender_adjustments' => array(
            'male' => array('optimal_min' => 0, 'optimal_max' => 6),
            'female' => array('optimal_min' => 0, 'optimal_max' => 5),
        ),
        'clinical_significance' => 'TMAO is produced by gut bacteria from dietary precursors and is associated with increased cardiovascular risk, atherosclerosis, and thrombosis.',
        'risk_factors' => array('High red meat consumption', 'Poor gut health', 'Western diet', 'Obesity', 'Diabetes', 'Kidney disease'),
        'optimization_recommendations' => array('Plant-based diet', 'Probiotics', 'Fiber supplementation', 'Limit red meat', 'Regular exercise'),
        'flag_criteria' => array(
            'symptom_triggers' => array('digestive_issues', 'fatigue', 'inflammation'),
            'range_triggers' => array('above_10_umol_l' => 'moderate', 'above_20_umol_l' => 'high'),
        ),
        'scoring_algorithm' => array('optimal_score' => 10, 'suboptimal_score' => 7, 'poor_score' => 4, 'critical_score' => 1),
        'target_setting' => array(
            'improvement_targets' => array('Reduce TMAO to <6 μmol/L'),
            'timeframes' => array('immediate' => '1 week', 'short_term' => '1 month', 'long_term' => '3-6 months'),
        ),
        'sources' => array(
            'primary' => 'AHA 2023 Gut Microbiome Guidelines',
            'secondary' => array('https://www.ahealthacademy.com/biomarkers/', 'JACC 2023: TMAO and Cardiovascular Risk'),
            'evidence_level' => 'A',
        ),
    ),
    'nmr_lipoprofile' => array(
        'display_name' => 'Nuclear Magnetic Resonance Lipoprotein Profile',
        'unit' => 'nmol/L',
        'description' => 'Advanced lipid particle analysis for cardiovascular risk assessment',
        'ranges' => array(
            'optimal_min' => 800,
            'optimal_max' => 1200,
            'normal_min' => 600,
            'normal_max' => 1500,
            'critical_min' => 400,
            'critical_max' => 2000,
        ),
        'age_adjustments' => array(
            'young' => array('optimal_min' => 750, 'optimal_max' => 1150),
            'adult' => array('optimal_min' => 800, 'optimal_max' => 1200),
            'senior' => array('optimal_min' => 850, 'optimal_max' => 1250),
        ),
        'gender_adjustments' => array(
            'male' => array('optimal_min' => 800, 'optimal_max' => 1200),
            'female' => array('optimal_min' => 750, 'optimal_max' => 1150),
        ),
        'clinical_significance' => 'NMR lipoprotein profile provides detailed analysis of lipoprotein particle numbers and sizes, offering more precise cardiovascular risk assessment than standard lipid panels.',
        'risk_factors' => array('Genetic factors', 'Poor diet', 'Obesity', 'Diabetes', 'Metabolic syndrome', 'Sedentary lifestyle'),
        'optimization_recommendations' => array('Mediterranean diet', 'Regular exercise', 'Weight management', 'Statins if indicated', 'Fiber supplementation'),
        'flag_criteria' => array(
            'symptom_triggers' => array('chest_pain', 'shortness_of_breath', 'fatigue'),
            'range_triggers' => array('above_1500_nmol_l' => 'moderate', 'above_2000_nmol_l' => 'high'),
        ),
        'scoring_algorithm' => array('optimal_score' => 10, 'suboptimal_score' => 7, 'poor_score' => 4, 'critical_score' => 1),
        'target_setting' => array(
            'improvement_targets' => array('Optimize lipoprotein particle profile'),
            'timeframes' => array('immediate' => '1 week', 'short_term' => '1 month', 'long_term' => '3-6 months'),
        ),
        'sources' => array(
            'primary' => 'AHA 2023 Advanced Lipid Testing Guidelines',
            'secondary' => array('https://www.ahealthacademy.com/biomarkers/', 'JACC 2023: NMR Lipoprotein Analysis'),
            'evidence_level' => 'A',
        ),
    ),
    'glucose' => array(
        'display_name' => 'Fasting Glucose',
        'unit' => 'mg/dL',
        'description' => 'Blood sugar level indicating metabolic health and diabetes risk',
        'ranges' => array(
            'optimal_min' => 70,
            'optimal_max' => 100,
            'normal_min' => 60,
            'normal_max' => 125,
            'critical_min' => 50,
            'critical_max' => 200,
        ),
        'age_adjustments' => array(
            'young' => array('optimal_min' => 65, 'optimal_max' => 95),
            'adult' => array('optimal_min' => 70, 'optimal_max' => 100),
            'senior' => array('optimal_min' => 75, 'optimal_max' => 105),
        ),
        'gender_adjustments' => array(
            'male' => array('optimal_min' => 70, 'optimal_max' => 100),
            'female' => array('optimal_min' => 65, 'optimal_max' => 95),
        ),
        'clinical_significance' => 'Fasting glucose is a key indicator of metabolic health and diabetes risk. Elevated levels indicate insulin resistance and increased cardiovascular risk.',
        'risk_factors' => array('High carbohydrate diet', 'Obesity', 'Sedentary lifestyle', 'Family history', 'Age', 'Ethnic background'),
        'optimization_recommendations' => array('Low-glycemic diet', 'Regular exercise', 'Weight management', 'Stress reduction', 'Adequate sleep'),
        'flag_criteria' => array(
            'symptom_triggers' => array('fatigue', 'increased_thirst', 'frequent_urination'),
            'range_triggers' => array('above_125_mg_dl' => 'moderate', 'above_200_mg_dl' => 'high'),
        ),
        'scoring_algorithm' => array('optimal_score' => 10, 'suboptimal_score' => 7, 'poor_score' => 4, 'critical_score' => 1),
        'target_setting' => array(
            'improvement_targets' => array('Maintain glucose <100 mg/dL'),
            'timeframes' => array('immediate' => '1 week', 'short_term' => '1 month', 'long_term' => '3-6 months'),
        ),
        'sources' => array(
            'primary' => 'ADA 2023 Diabetes Guidelines',
            'secondary' => array('https://www.ahealthacademy.com/biomarkers/', 'JACC 2023: Glucose and Cardiovascular Risk'),
            'evidence_level' => 'A',
        ),
    ),
    'hba1c' => array(
        'display_name' => 'Hemoglobin A1c',
        'unit' => '%',
        'description' => 'Long-term blood sugar control indicator over 2-3 months',
        'ranges' => array(
            'optimal_min' => 4.5,
            'optimal_max' => 5.7,
            'normal_min' => 4.0,
            'normal_max' => 6.5,
            'critical_min' => 3.5,
            'critical_max' => 10.0,
        ),
        'age_adjustments' => array(
            'young' => array('optimal_min' => 4.3, 'optimal_max' => 5.5),
            'adult' => array('optimal_min' => 4.5, 'optimal_max' => 5.7),
            'senior' => array('optimal_min' => 4.7, 'optimal_max' => 5.9),
        ),
        'gender_adjustments' => array(
            'male' => array('optimal_min' => 4.5, 'optimal_max' => 5.7),
            'female' => array('optimal_min' => 4.3, 'optimal_max' => 5.5),
        ),
        'clinical_significance' => 'HbA1c reflects average blood glucose over 2-3 months and is a key indicator of diabetes control and cardiovascular risk.',
        'risk_factors' => array('Poor diet', 'Obesity', 'Sedentary lifestyle', 'Family history', 'Age', 'Ethnic background'),
        'optimization_recommendations' => array('Low-carb diet', 'Regular exercise', 'Weight management', 'Blood sugar monitoring', 'Medication compliance'),
        'flag_criteria' => array(
            'symptom_triggers' => array('fatigue', 'increased_thirst', 'frequent_urination'),
            'range_triggers' => array('above_6_5_percent' => 'moderate', 'above_8_0_percent' => 'high'),
        ),
        'scoring_algorithm' => array('optimal_score' => 10, 'suboptimal_score' => 7, 'poor_score' => 4, 'critical_score' => 1),
        'target_setting' => array(
            'improvement_targets' => array('Maintain HbA1c <5.7%'),
            'timeframes' => array('immediate' => '1 week', 'short_term' => '1 month', 'long_term' => '3-6 months'),
        ),
        'sources' => array(
            'primary' => 'ADA 2023 Diabetes Guidelines',
            'secondary' => array('https://www.ahealthacademy.com/biomarkers/', 'JACC 2023: HbA1c and Cardiovascular Risk'),
            'evidence_level' => 'A',
        ),
    ),
    'insulin' => array(
        'display_name' => 'Fasting Insulin',
        'unit' => 'μIU/mL',
        'description' => 'Pancreatic hormone indicating insulin resistance and metabolic health',
        'ranges' => array(
            'optimal_min' => 2,
            'optimal_max' => 6,
            'normal_min' => 2,
            'normal_max' => 12,
            'critical_min' => 1,
            'critical_max' => 25,
        ),
        'age_adjustments' => array(
            'young' => array('optimal_min' => 2, 'optimal_max' => 5),
            'adult' => array('optimal_min' => 2, 'optimal_max' => 6),
            'senior' => array('optimal_min' => 3, 'optimal_max' => 8),
        ),
        'gender_adjustments' => array(
            'male' => array('optimal_min' => 2, 'optimal_max' => 6),
            'female' => array('optimal_min' => 2, 'optimal_max' => 7),
        ),
        'clinical_significance' => 'Fasting insulin is a key indicator of insulin resistance and metabolic syndrome. Elevated levels indicate increased cardiovascular risk.',
        'risk_factors' => array('High carbohydrate diet', 'Obesity', 'Sedentary lifestyle', 'Stress', 'Poor sleep', 'Genetic factors'),
        'optimization_recommendations' => array('Low-carb diet', 'Regular exercise', 'Weight management', 'Stress reduction', 'Adequate sleep'),
        'flag_criteria' => array(
            'symptom_triggers' => array('fatigue', 'weight_gain', 'increased_hunger'),
            'range_triggers' => array('above_12_uiu_ml' => 'moderate', 'above_20_uiu_ml' => 'high'),
        ),
        'scoring_algorithm' => array('optimal_score' => 10, 'suboptimal_score' => 7, 'poor_score' => 4, 'critical_score' => 1),
        'target_setting' => array(
            'improvement_targets' => array('Reduce insulin to <6 μIU/mL'),
            'timeframes' => array('immediate' => '1 week', 'short_term' => '1 month', 'long_term' => '3-6 months'),
        ),
        'sources' => array(
            'primary' => 'ADA 2023 Insulin Resistance Guidelines',
            'secondary' => array('https://www.ahealthacademy.com/biomarkers/', 'JACC 2023: Insulin and Cardiovascular Risk'),
            'evidence_level' => 'A',
        ),
    ),
    'uric_acid' => array(
        'display_name' => 'Uric Acid',
        'unit' => 'mg/dL',
        'description' => 'Metabolic byproduct indicating gout risk and cardiovascular health',
        'ranges' => array(
            'optimal_min' => 3.0,
            'optimal_max' => 6.0,
            'normal_min' => 2.5,
            'normal_max' => 7.0,
            'critical_min' => 2.0,
            'critical_max' => 10.0,
        ),
        'age_adjustments' => array(
            'young' => array('optimal_min' => 2.8, 'optimal_max' => 5.8),
            'adult' => array('optimal_min' => 3.0, 'optimal_max' => 6.0),
            'senior' => array('optimal_min' => 3.2, 'optimal_max' => 6.2),
        ),
        'gender_adjustments' => array(
            'male' => array('optimal_min' => 3.0, 'optimal_max' => 6.0),
            'female' => array('optimal_min' => 2.5, 'optimal_max' => 5.5),
        ),
        'clinical_significance' => 'Elevated uric acid is associated with gout, kidney stones, and increased cardiovascular risk through inflammation and oxidative stress.',
        'risk_factors' => array('High purine diet', 'Alcohol consumption', 'Obesity', 'Kidney disease', 'Certain medications', 'Dehydration'),
        'optimization_recommendations' => array('Low purine diet', 'Adequate hydration', 'Limit alcohol', 'Weight management', 'Cherry consumption'),
        'flag_criteria' => array(
            'symptom_triggers' => array('joint_pain', 'kidney_pain', 'fatigue'),
            'range_triggers' => array('above_7_mg_dl' => 'moderate', 'above_10_mg_dl' => 'high'),
        ),
        'scoring_algorithm' => array('optimal_score' => 10, 'suboptimal_score' => 7, 'poor_score' => 4, 'critical_score' => 1),
        'target_setting' => array(
            'improvement_targets' => array('Reduce uric acid to <6.0 mg/dL'),
            'timeframes' => array('immediate' => '1 week', 'short_term' => '1 month', 'long_term' => '3-6 months'),
        ),
        'sources' => array(
            'primary' => 'AHA 2023 Uric Acid Guidelines',
            'secondary' => array('https://www.ahealthacademy.com/biomarkers/', 'JACC 2023: Uric Acid and Cardiovascular Risk'),
            'evidence_level' => 'A',
        ),
    ),
    'one_five_ag' => array(
        'display_name' => '1,5-Anhydroglucitol',
        'unit' => 'μg/mL',
        'description' => 'Glucose control marker indicating postprandial hyperglycemia',
        'ranges' => array(
            'optimal_min' => 10,
            'optimal_max' => 35,
            'normal_min' => 5,
            'normal_max' => 40,
            'critical_min' => 2,
            'critical_max' => 50,
        ),
        'age_adjustments' => array(
            'young' => array('optimal_min' => 12, 'optimal_max' => 33),
            'adult' => array('optimal_min' => 10, 'optimal_max' => 35),
            'senior' => array('optimal_min' => 8, 'optimal_max' => 37),
        ),
        'gender_adjustments' => array(
            'male' => array('optimal_min' => 10, 'optimal_max' => 35),
            'female' => array('optimal_min' => 8, 'optimal_max' => 33),
        ),
        'clinical_significance' => '1,5-AG is a marker of postprandial glucose control and glycemic variability. Lower levels indicate poor glucose control and increased cardiovascular risk.',
        'risk_factors' => array('High carbohydrate diet', 'Diabetes', 'Obesity', 'Sedentary lifestyle', 'Poor glucose control'),
        'optimization_recommendations' => array('Low-glycemic diet', 'Regular exercise', 'Weight management', 'Blood sugar monitoring', 'Medication compliance'),
        'flag_criteria' => array(
            'symptom_triggers' => array('fatigue', 'increased_thirst', 'frequent_urination'),
            'range_triggers' => array('below_5_ug_ml' => 'moderate', 'below_2_ug_ml' => 'high'),
        ),
        'scoring_algorithm' => array('optimal_score' => 10, 'suboptimal_score' => 7, 'poor_score' => 4, 'critical_score' => 1),
        'target_setting' => array(
            'improvement_targets' => array('Increase 1,5-AG to >10 μg/mL'),
            'timeframes' => array('immediate' => '1 week', 'short_term' => '1 month', 'long_term' => '3-6 months'),
        ),
        'sources' => array(
            'primary' => 'ADA 2023 Glucose Control Guidelines',
            'secondary' => array('https://www.ahealthacademy.com/biomarkers/', 'JACC 2023: 1,5-AG and Cardiovascular Risk'),
            'evidence_level' => 'A',
        ),
    ),
    'automated_or_manual_cuff' => array(
        'display_name' => 'Blood Pressure Measurement Method',
        'unit' => 'Method',
        'description' => 'Method of blood pressure measurement affecting accuracy and reliability',
        'ranges' => array(
            'optimal_min' => 1,
            'optimal_max' => 1,
            'normal_min' => 1,
            'normal_max' => 2,
            'critical_min' => 1,
            'critical_max' => 2,
        ),
        'age_adjustments' => array(
            'young' => array('optimal_min' => 1, 'optimal_max' => 1),
            'adult' => array('optimal_min' => 1, 'optimal_max' => 1),
            'senior' => array('optimal_min' => 1, 'optimal_max' => 1),
        ),
        'gender_adjustments' => array(
            'male' => array('optimal_min' => 1, 'optimal_max' => 1),
            'female' => array('optimal_min' => 1, 'optimal_max' => 1),
        ),
        'clinical_significance' => 'Automated BP measurement provides more consistent and accurate readings compared to manual methods, reducing measurement variability.',
        'risk_factors' => array('Manual measurement technique', 'Incorrect cuff size', 'Poor measurement timing', 'White coat hypertension'),
        'optimization_recommendations' => array('Use validated automated devices', 'Proper cuff sizing', 'Multiple measurements', 'Home monitoring'),
        'flag_criteria' => array(
            'symptom_triggers' => array('inconsistent_readings', 'white_coat_effect'),
            'range_triggers' => array('manual_method' => 'moderate', 'inconsistent_technique' => 'high'),
        ),
        'scoring_algorithm' => array('optimal_score' => 10, 'suboptimal_score' => 7, 'poor_score' => 4, 'critical_score' => 1),
        'target_setting' => array(
            'improvement_targets' => array('Use automated BP measurement'),
            'timeframes' => array('immediate' => '1 week', 'short_term' => '1 month', 'long_term' => '3-6 months'),
        ),
        'sources' => array(
            'primary' => 'AHA 2023 BP Measurement Guidelines',
            'secondary' => array('https://www.ahealthacademy.com/biomarkers/', 'JACC 2023: BP Measurement Accuracy'),
            'evidence_level' => 'A',
        ),
    ),
    'apoe_genotype' => array(
        'display_name' => 'Apolipoprotein E Genotype',
        'unit' => 'Genotype',
        'description' => 'Genetic variant affecting lipid metabolism and cardiovascular risk',
        'ranges' => array(
            'optimal_min' => 1,
            'optimal_max' => 1,
            'normal_min' => 1,
            'normal_max' => 3,
            'critical_min' => 1,
            'critical_max' => 4,
        ),
        'age_adjustments' => array(
            'young' => array('optimal_min' => 1, 'optimal_max' => 1),
            'adult' => array('optimal_min' => 1, 'optimal_max' => 1),
            'senior' => array('optimal_min' => 1, 'optimal_max' => 1),
        ),
        'gender_adjustments' => array(
            'male' => array('optimal_min' => 1, 'optimal_max' => 1),
            'female' => array('optimal_min' => 1, 'optimal_max' => 1),
        ),
        'clinical_significance' => 'ApoE genotype affects lipid metabolism and cardiovascular risk. E4 allele increases risk while E2 may be protective.',
        'risk_factors' => array('Genetic factors', 'Family history', 'Ethnic background', 'Age', 'Gender'),
        'optimization_recommendations' => array('Lifestyle optimization', 'Regular monitoring', 'Cardiovascular risk assessment', 'Specialist consultation'),
        'flag_criteria' => array(
            'symptom_triggers' => array('family_history', 'elevated_lipids'),
            'range_triggers' => array('e4_allele' => 'moderate', 'e4_homozygous' => 'high'),
        ),
        'scoring_algorithm' => array('optimal_score' => 10, 'suboptimal_score' => 7, 'poor_score' => 4, 'critical_score' => 1),
        'target_setting' => array(
            'improvement_targets' => array('Optimize lifestyle based on genotype'),
            'timeframes' => array('immediate' => '1 week', 'short_term' => '1 month', 'long_term' => '3-6 months'),
        ),
        'sources' => array(
            'primary' => 'AHA 2023 Genetic Risk Guidelines',
            'secondary' => array('https://www.ahealthacademy.com/biomarkers/', 'JACC 2023: ApoE and Cardiovascular Risk'),
            'evidence_level' => 'A',
        ),
    ),
    'hemoglobin' => array(
        'display_name' => 'Hemoglobin',
        'unit' => 'g/dL',
        'description' => 'Oxygen-carrying protein in red blood cells indicating cardiovascular health',
        'ranges' => array(
            'optimal_min' => 13.5,
            'optimal_max' => 17.5,
            'normal_min' => 12.0,
            'normal_max' => 18.0,
            'critical_min' => 10.0,
            'critical_max' => 20.0,
        ),
        'age_adjustments' => array(
            'young' => array('optimal_min' => 13.0, 'optimal_max' => 17.0),
            'adult' => array('optimal_min' => 13.5, 'optimal_max' => 17.5),
            'senior' => array('optimal_min' => 12.5, 'optimal_max' => 16.5),
        ),
        'gender_adjustments' => array(
            'male' => array('optimal_min' => 14.0, 'optimal_max' => 17.5),
            'female' => array('optimal_min' => 12.3, 'optimal_max' => 15.3),
        ),
        'clinical_significance' => 'Hemoglobin is essential for oxygen delivery to tissues. Low levels indicate anemia and reduced cardiovascular capacity.',
        'risk_factors' => array('Iron deficiency', 'B12 deficiency', 'Chronic disease', 'Blood loss', 'Poor diet', 'Genetic factors'),
        'optimization_recommendations' => array('Iron-rich diet', 'B12 supplementation', 'Address underlying causes', 'Regular monitoring'),
        'flag_criteria' => array(
            'symptom_triggers' => array('fatigue', 'shortness_of_breath', 'pale_skin'),
            'range_triggers' => array('below_12_g_dl' => 'moderate', 'below_10_g_dl' => 'high'),
        ),
        'scoring_algorithm' => array('optimal_score' => 10, 'suboptimal_score' => 7, 'poor_score' => 4, 'critical_score' => 1),
        'target_setting' => array(
            'improvement_targets' => array('Maintain hemoglobin >13.5 g/dL'),
            'timeframes' => array('immediate' => '1 week', 'short_term' => '1 month', 'long_term' => '3-6 months'),
        ),
        'sources' => array(
            'primary' => 'AHA 2023 Anemia Guidelines',
            'secondary' => array('https://www.ahealthacademy.com/biomarkers/', 'JACC 2023: Hemoglobin and Cardiovascular Health'),
            'evidence_level' => 'A',
        ),
    ),
    'hematocrit' => array(
        'display_name' => 'Hematocrit',
        'unit' => '%',
        'description' => 'Percentage of blood volume occupied by red blood cells',
        'ranges' => array(
            'optimal_min' => 40,
            'optimal_max' => 50,
            'normal_min' => 36,
            'normal_max' => 52,
            'critical_min' => 30,
            'critical_max' => 60,
        ),
        'age_adjustments' => array(
            'young' => array('optimal_min' => 39, 'optimal_max' => 49),
            'adult' => array('optimal_min' => 40, 'optimal_max' => 50),
            'senior' => array('optimal_min' => 38, 'optimal_max' => 48),
        ),
        'gender_adjustments' => array(
            'male' => array('optimal_min' => 42, 'optimal_max' => 52),
            'female' => array('optimal_min' => 37, 'optimal_max' => 47),
        ),
        'clinical_significance' => 'Hematocrit reflects red blood cell mass and oxygen-carrying capacity. Abnormal levels affect cardiovascular function.',
        'risk_factors' => array('Iron deficiency', 'Dehydration', 'Chronic disease', 'Blood loss', 'Altitude', 'Smoking'),
        'optimization_recommendations' => array('Iron supplementation', 'Adequate hydration', 'Address underlying causes', 'Regular monitoring'),
        'flag_criteria' => array(
            'symptom_triggers' => array('fatigue', 'shortness_of_breath', 'dizziness'),
            'range_triggers' => array('below_36_percent' => 'moderate', 'below_30_percent' => 'high'),
        ),
        'scoring_algorithm' => array('optimal_score' => 10, 'suboptimal_score' => 7, 'poor_score' => 4, 'critical_score' => 1),
        'target_setting' => array(
            'improvement_targets' => array('Maintain hematocrit 40-50%'),
            'timeframes' => array('immediate' => '1 week', 'short_term' => '1 month', 'long_term' => '3-6 months'),
        ),
        'sources' => array(
            'primary' => 'AHA 2023 Blood Cell Guidelines',
            'secondary' => array('https://www.ahealthacademy.com/biomarkers/', 'JACC 2023: Hematocrit and Cardiovascular Health'),
            'evidence_level' => 'A',
        ),
    ),
    'rbc' => array(
        'display_name' => 'Red Blood Cell Count',
        'unit' => 'million/μL',
        'description' => 'Number of red blood cells per microliter of blood',
        'ranges' => array(
            'optimal_min' => 4.5,
            'optimal_max' => 5.9,
            'normal_min' => 4.0,
            'normal_max' => 6.2,
            'critical_min' => 3.5,
            'critical_max' => 7.0,
        ),
        'age_adjustments' => array(
            'young' => array('optimal_min' => 4.3, 'optimal_max' => 5.7),
            'adult' => array('optimal_min' => 4.5, 'optimal_max' => 5.9),
            'senior' => array('optimal_min' => 4.2, 'optimal_max' => 5.6),
        ),
        'gender_adjustments' => array(
            'male' => array('optimal_min' => 4.7, 'optimal_max' => 6.1),
            'female' => array('optimal_min' => 4.2, 'optimal_max' => 5.4),
        ),
        'clinical_significance' => 'RBC count indicates bone marrow function and oxygen-carrying capacity. Abnormal levels affect cardiovascular performance.',
        'risk_factors' => array('Iron deficiency', 'B12 deficiency', 'Chronic disease', 'Blood loss', 'Poor diet'),
        'optimization_recommendations' => array('Iron-rich diet', 'B12 supplementation', 'Address underlying causes', 'Regular monitoring'),
        'flag_criteria' => array(
            'symptom_triggers' => array('fatigue', 'shortness_of_breath', 'pale_skin'),
            'range_triggers' => array('below_4_million_ul' => 'moderate', 'below_3_5_million_ul' => 'high'),
        ),
        'scoring_algorithm' => array('optimal_score' => 10, 'suboptimal_score' => 7, 'poor_score' => 4, 'critical_score' => 1),
        'target_setting' => array(
            'improvement_targets' => array('Maintain RBC count 4.5-5.9 million/μL'),
            'timeframes' => array('immediate' => '1 week', 'short_term' => '1 month', 'long_term' => '3-6 months'),
        ),
        'sources' => array(
            'primary' => 'AHA 2023 Blood Cell Guidelines',
            'secondary' => array('https://www.ahealthacademy.com/biomarkers/', 'JACC 2023: RBC Count and Cardiovascular Health'),
            'evidence_level' => 'A',
        ),
    ),
    'wbc' => array(
        'display_name' => 'White Blood Cell Count',
        'unit' => 'thousand/μL',
        'description' => 'Number of white blood cells indicating immune function and inflammation',
        'ranges' => array(
            'optimal_min' => 4.5,
            'optimal_max' => 11.0,
            'normal_min' => 4.0,
            'normal_max' => 12.0,
            'critical_min' => 3.0,
            'critical_max' => 15.0,
        ),
        'age_adjustments' => array(
            'young' => array('optimal_min' => 4.0, 'optimal_max' => 10.5),
            'adult' => array('optimal_min' => 4.5, 'optimal_max' => 11.0),
            'senior' => array('optimal_min' => 4.0, 'optimal_max' => 11.5),
        ),
        'gender_adjustments' => array(
            'male' => array('optimal_min' => 4.5, 'optimal_max' => 11.0),
            'female' => array('optimal_min' => 4.0, 'optimal_max' => 10.5),
        ),
        'clinical_significance' => 'WBC count reflects immune function and inflammatory status. Elevated levels may indicate infection or inflammation affecting cardiovascular health.',
        'risk_factors' => array('Infection', 'Inflammation', 'Stress', 'Smoking', 'Obesity', 'Autoimmune conditions'),
        'optimization_recommendations' => array('Address underlying causes', 'Anti-inflammatory diet', 'Stress management', 'Regular exercise'),
        'flag_criteria' => array(
            'symptom_triggers' => array('fatigue', 'fever', 'infection'),
            'range_triggers' => array('above_12_thousand_ul' => 'moderate', 'above_15_thousand_ul' => 'high'),
        ),
        'scoring_algorithm' => array('optimal_score' => 10, 'suboptimal_score' => 7, 'poor_score' => 4, 'critical_score' => 1),
        'target_setting' => array(
            'improvement_targets' => array('Maintain WBC count 4.5-11.0 thousand/μL'),
            'timeframes' => array('immediate' => '1 week', 'short_term' => '1 month', 'long_term' => '3-6 months'),
        ),
        'sources' => array(
            'primary' => 'AHA 2023 Inflammation Guidelines',
            'secondary' => array('https://www.ahealthacademy.com/biomarkers/', 'JACC 2023: WBC and Cardiovascular Health'),
            'evidence_level' => 'A',
        ),
    ),
    'platelets' => array(
        'display_name' => 'Platelet Count',
        'unit' => 'thousand/μL',
        'description' => 'Number of platelets involved in blood clotting and cardiovascular health',
        'ranges' => array(
            'optimal_min' => 150,
            'optimal_max' => 400,
            'normal_min' => 130,
            'normal_max' => 450,
            'critical_min' => 100,
            'critical_max' => 600,
        ),
        'age_adjustments' => array(
            'young' => array('optimal_min' => 140, 'optimal_max' => 390),
            'adult' => array('optimal_min' => 150, 'optimal_max' => 400),
            'senior' => array('optimal_min' => 140, 'optimal_max' => 410),
        ),
        'gender_adjustments' => array(
            'male' => array('optimal_min' => 150, 'optimal_max' => 400),
            'female' => array('optimal_min' => 140, 'optimal_max' => 390),
        ),
        'clinical_significance' => 'Platelets are essential for blood clotting and cardiovascular health. Abnormal levels increase risk of bleeding or clotting disorders.',
        'risk_factors' => array('Medications', 'Autoimmune conditions', 'Infection', 'Cancer', 'Liver disease', 'Genetic factors'),
        'optimization_recommendations' => array('Address underlying causes', 'Medication review', 'Regular monitoring', 'Specialist consultation'),
        'flag_criteria' => array(
            'symptom_triggers' => array('bleeding', 'bruising', 'fatigue'),
            'range_triggers' => array('below_130_thousand_ul' => 'moderate', 'below_100_thousand_ul' => 'high'),
        ),
        'scoring_algorithm' => array('optimal_score' => 10, 'suboptimal_score' => 7, 'poor_score' => 4, 'critical_score' => 1),
        'target_setting' => array(
            'improvement_targets' => array('Maintain platelet count 150-400 thousand/μL'),
            'timeframes' => array('immediate' => '1 week', 'short_term' => '1 month', 'long_term' => '3-6 months'),
        ),
        'sources' => array(
            'primary' => 'AHA 2023 Blood Cell Guidelines',
            'secondary' => array('https://www.ahealthacademy.com/biomarkers/', 'JACC 2023: Platelets and Cardiovascular Health'),
            'evidence_level' => 'A',
        ),
    ),
    'mch' => array(
        'display_name' => 'Mean Corpuscular Hemoglobin',
        'unit' => 'pg',
        'description' => 'Average amount of hemoglobin per red blood cell',
        'ranges' => array(
            'optimal_min' => 27,
            'optimal_max' => 33,
            'normal_min' => 26,
            'normal_max' => 34,
            'critical_min' => 24,
            'critical_max' => 36,
        ),
        'age_adjustments' => array(
            'young' => array('optimal_min' => 26, 'optimal_max' => 32),
            'adult' => array('optimal_min' => 27, 'optimal_max' => 33),
            'senior' => array('optimal_min' => 26, 'optimal_max' => 32),
        ),
        'gender_adjustments' => array(
            'male' => array('optimal_min' => 27, 'optimal_max' => 33),
            'female' => array('optimal_min' => 26, 'optimal_max' => 32),
        ),
        'clinical_significance' => 'MCH indicates the quality of hemoglobin in red blood cells. Abnormal levels suggest iron deficiency or other anemias.',
        'risk_factors' => array('Iron deficiency', 'B12 deficiency', 'Chronic disease', 'Poor diet', 'Blood loss'),
        'optimization_recommendations' => array('Iron supplementation', 'B12 supplementation', 'Address underlying causes', 'Regular monitoring'),
        'flag_criteria' => array(
            'symptom_triggers' => array('fatigue', 'pale_skin', 'weakness'),
            'range_triggers' => array('below_26_pg' => 'moderate', 'below_24_pg' => 'high'),
        ),
        'scoring_algorithm' => array('optimal_score' => 10, 'suboptimal_score' => 7, 'poor_score' => 4, 'critical_score' => 1),
        'target_setting' => array(
            'improvement_targets' => array('Maintain MCH 27-33 pg'),
            'timeframes' => array('immediate' => '1 week', 'short_term' => '1 month', 'long_term' => '3-6 months'),
        ),
        'sources' => array(
            'primary' => 'AHA 2023 Anemia Guidelines',
            'secondary' => array('https://www.ahealthacademy.com/biomarkers/', 'JACC 2023: MCH and Cardiovascular Health'),
            'evidence_level' => 'A',
        ),
    ),
    'mchc' => array(
        'display_name' => 'Mean Corpuscular Hemoglobin Concentration',
        'unit' => 'g/dL',
        'description' => 'Concentration of hemoglobin in red blood cells',
        'ranges' => array(
            'optimal_min' => 32,
            'optimal_max' => 36,
            'normal_min' => 31,
            'normal_max' => 37,
            'critical_min' => 30,
            'critical_max' => 38,
        ),
        'age_adjustments' => array(
            'young' => array('optimal_min' => 31, 'optimal_max' => 35),
            'adult' => array('optimal_min' => 32, 'optimal_max' => 36),
            'senior' => array('optimal_min' => 31, 'optimal_max' => 35),
        ),
        'gender_adjustments' => array(
            'male' => array('optimal_min' => 32, 'optimal_max' => 36),
            'female' => array('optimal_min' => 31, 'optimal_max' => 35),
        ),
        'clinical_significance' => 'MCHC reflects the concentration of hemoglobin in red blood cells. Low levels indicate iron deficiency anemia.',
        'risk_factors' => array('Iron deficiency', 'Chronic disease', 'Poor diet', 'Blood loss', 'Genetic factors'),
        'optimization_recommendations' => array('Iron supplementation', 'Iron-rich diet', 'Address underlying causes', 'Regular monitoring'),
        'flag_criteria' => array(
            'symptom_triggers' => array('fatigue', 'pale_skin', 'weakness'),
            'range_triggers' => array('below_31_g_dl' => 'moderate', 'below_30_g_dl' => 'high'),
        ),
        'scoring_algorithm' => array('optimal_score' => 10, 'suboptimal_score' => 7, 'poor_score' => 4, 'critical_score' => 1),
        'target_setting' => array(
            'improvement_targets' => array('Maintain MCHC 32-36 g/dL'),
            'timeframes' => array('immediate' => '1 week', 'short_term' => '1 month', 'long_term' => '3-6 months'),
        ),
        'sources' => array(
            'primary' => 'AHA 2023 Anemia Guidelines',
            'secondary' => array('https://www.ahealthacademy.com/biomarkers/', 'JACC 2023: MCHC and Cardiovascular Health'),
            'evidence_level' => 'A',
        ),
    ),
    'mcv' => array(
        'display_name' => 'Mean Corpuscular Volume',
        'unit' => 'fL',
        'description' => 'Average size of red blood cells indicating anemia type',
        'ranges' => array(
            'optimal_min' => 80,
            'optimal_max' => 100,
            'normal_min' => 75,
            'normal_max' => 105,
            'critical_min' => 70,
            'critical_max' => 110,
        ),
        'age_adjustments' => array(
            'young' => array('optimal_min' => 78, 'optimal_max' => 98),
            'adult' => array('optimal_min' => 80, 'optimal_max' => 100),
            'senior' => array('optimal_min' => 78, 'optimal_max' => 98),
        ),
        'gender_adjustments' => array(
            'male' => array('optimal_min' => 80, 'optimal_max' => 100),
            'female' => array('optimal_min' => 78, 'optimal_max' => 98),
        ),
        'clinical_significance' => 'MCV indicates red blood cell size and helps classify anemia types. Microcytic anemia suggests iron deficiency.',
        'risk_factors' => array('Iron deficiency', 'B12 deficiency', 'Chronic disease', 'Poor diet', 'Genetic factors'),
        'optimization_recommendations' => array('Iron supplementation', 'B12 supplementation', 'Address underlying causes', 'Regular monitoring'),
        'flag_criteria' => array(
            'symptom_triggers' => array('fatigue', 'pale_skin', 'weakness'),
            'range_triggers' => array('below_75_fl' => 'moderate', 'below_70_fl' => 'high'),
        ),
        'scoring_algorithm' => array('optimal_score' => 10, 'suboptimal_score' => 7, 'poor_score' => 4, 'critical_score' => 1),
        'target_setting' => array(
            'improvement_targets' => array('Maintain MCV 80-100 fL'),
            'timeframes' => array('immediate' => '1 week', 'short_term' => '1 month', 'long_term' => '3-6 months'),
        ),
        'sources' => array(
            'primary' => 'AHA 2023 Anemia Guidelines',
            'secondary' => array('https://www.ahealthacademy.com/biomarkers/', 'JACC 2023: MCV and Cardiovascular Health'),
            'evidence_level' => 'A',
        ),
    ),
    'rdw' => array(
        'display_name' => 'Red Cell Distribution Width',
        'unit' => '%',
        'description' => 'Variation in red blood cell size indicating anemia type',
        'ranges' => array(
            'optimal_min' => 11.5,
            'optimal_max' => 14.5,
            'normal_min' => 11.0,
            'normal_max' => 15.0,
            'critical_min' => 10.0,
            'critical_max' => 16.0,
        ),
        'age_adjustments' => array(
            'young' => array('optimal_min' => 11.0, 'optimal_max' => 14.0),
            'adult' => array('optimal_min' => 11.5, 'optimal_max' => 14.5),
            'senior' => array('optimal_min' => 11.0, 'optimal_max' => 14.0),
        ),
        'gender_adjustments' => array(
            'male' => array('optimal_min' => 11.5, 'optimal_max' => 14.5),
            'female' => array('optimal_min' => 11.0, 'optimal_max' => 14.0),
        ),
        'clinical_significance' => 'RDW indicates variation in red blood cell size. Elevated levels suggest iron deficiency or other anemias.',
        'risk_factors' => array('Iron deficiency', 'B12 deficiency', 'Chronic disease', 'Poor diet', 'Blood loss'),
        'optimization_recommendations' => array('Iron supplementation', 'B12 supplementation', 'Address underlying causes', 'Regular monitoring'),
        'flag_criteria' => array(
            'symptom_triggers' => array('fatigue', 'pale_skin', 'weakness'),
            'range_triggers' => array('above_15_percent' => 'moderate', 'above_16_percent' => 'high'),
        ),
        'scoring_algorithm' => array('optimal_score' => 10, 'suboptimal_score' => 7, 'poor_score' => 4, 'critical_score' => 1),
        'target_setting' => array(
            'improvement_targets' => array('Maintain RDW 11.5-14.5%'),
            'timeframes' => array('immediate' => '1 week', 'short_term' => '1 month', 'long_term' => '3-6 months'),
        ),
        'sources' => array(
            'primary' => 'AHA 2023 Anemia Guidelines',
            'secondary' => array('https://www.ahealthacademy.com/biomarkers/', 'JACC 2023: RDW and Cardiovascular Health'),
            'evidence_level' => 'A',
        ),
    ),
); 