<?php
/**
 * Dr. Orion Nexus - General Practice Biomarker Ranges
 * Generated on 2025-07-23 21:30:49
 */

return array(
    'specialist' => array(
        'name' => 'Dr. Orion Nexus',
        'specialty' => 'General Practice',
        'biomarker_count' => 31,
        'last_updated' => '2025-07-23 21:30:49',
    ),
    'biomarkers' => array(
        'glucose' => array(
            'unit' => 'mg/dL',
            'range' => '70-100',
            'optimal' => '75-95',
            'evidence_level' => 'A',
            'sources' => array('Medical AI Research', 'Clinical Guidelines'),
        ),
        'hba1c' => array(
            'unit' => '%',
            'range' => '4.0-5.6',
            'optimal' => '4.5-5.2',
            'evidence_level' => 'A',
            'sources' => array('Medical AI Research', 'Clinical Guidelines'),
        ),
        'cholesterol' => array(
            'unit' => 'mg/dL',
            'range' => '125-200',
            'optimal' => '150-180',
            'evidence_level' => 'A',
            'sources' => array('Medical AI Research', 'Clinical Guidelines'),
        ),
        'hdl' => array(
            'unit' => 'mg/dL',
            'range' => '40-60',
            'optimal' => '50-60',
            'evidence_level' => 'A',
            'sources' => array('Medical AI Research', 'Clinical Guidelines'),
        ),
        'ldl' => array(
            'unit' => 'mg/dL',
            'range' => '70-130',
            'optimal' => '70-100',
            'evidence_level' => 'A',
            'sources' => array('Medical AI Research', 'Clinical Guidelines'),
        ),
        'triglycerides' => array(
            'unit' => 'mg/dL',
            'range' => '50-150',
            'optimal' => '50-100',
            'evidence_level' => 'A',
            'sources' => array('Medical AI Research', 'Clinical Guidelines'),
        ),
        'blood_pressure' => array(
            'unit' => 'mmHg',
            'range' => '120/80',
            'optimal' => '110/70',
            'evidence_level' => 'A',
            'sources' => array('Medical AI Research', 'Clinical Guidelines'),
        ),
        'heart_rate' => array(
            'unit' => 'bpm',
            'range' => '60-100',
            'optimal' => '60-80',
            'evidence_level' => 'A',
            'sources' => array('Medical AI Research', 'Clinical Guidelines'),
        ),
        'temperature' => array(
            'unit' => '°F',
            'range' => '97.8-99.0',
            'optimal' => '98.2-98.8',
            'evidence_level' => 'A',
            'sources' => array('Medical AI Research', 'Clinical Guidelines'),
        ),
        'wbc' => array(
            'unit' => 'K/μL',
            'range' => '4.5-11.0',
            'optimal' => '5.0-10.0',
            'evidence_level' => 'A',
            'sources' => array('Medical AI Research', 'Clinical Guidelines'),
        ),
        'rbc' => array(
            'unit' => 'M/μL',
            'range' => '4.5-5.9',
            'optimal' => '4.8-5.5',
            'evidence_level' => 'A',
            'sources' => array('Medical AI Research', 'Clinical Guidelines'),
        ),
        'hemoglobin' => array(
            'unit' => 'g/dL',
            'range' => '13.5-17.5',
            'optimal' => '14.0-16.0',
            'evidence_level' => 'A',
            'sources' => array('Medical AI Research', 'Clinical Guidelines'),
        ),
        'hematocrit' => array(
            'unit' => '%',
            'range' => '41-50',
            'optimal' => '42-48',
            'evidence_level' => 'A',
            'sources' => array('Medical AI Research', 'Clinical Guidelines'),
        ),
        'platelets' => array(
            'unit' => 'K/μL',
            'range' => '150-450',
            'optimal' => '200-350',
            'evidence_level' => 'A',
            'sources' => array('Medical AI Research', 'Clinical Guidelines'),
        ),
        'sodium' => array(
            'unit' => 'mEq/L',
            'range' => '135-145',
            'optimal' => '137-143',
            'evidence_level' => 'A',
            'sources' => array('Medical AI Research', 'Clinical Guidelines'),
        ),
        'potassium' => array(
            'unit' => 'mEq/L',
            'range' => '3.5-5.0',
            'optimal' => '3.8-4.8',
            'evidence_level' => 'A',
            'sources' => array('Medical AI Research', 'Clinical Guidelines'),
        ),
        'chloride' => array(
            'unit' => 'mEq/L',
            'range' => '96-106',
            'optimal' => '98-104',
            'evidence_level' => 'A',
            'sources' => array('Medical AI Research', 'Clinical Guidelines'),
        ),
        'carbon_dioxide' => array(
            'unit' => 'mEq/L',
            'range' => '22-28',
            'optimal' => '23-27',
            'evidence_level' => 'A',
            'sources' => array('Medical AI Research', 'Clinical Guidelines'),
        ),
        'calcium' => array(
            'unit' => 'mg/dL',
            'range' => '8.5-10.5',
            'optimal' => '9.0-10.0',
            'evidence_level' => 'A',
            'sources' => array('Medical AI Research', 'Clinical Guidelines'),
        ),
        'magnesium' => array(
            'unit' => 'mg/dL',
            'range' => '1.7-2.2',
            'optimal' => '1.8-2.1',
            'evidence_level' => 'A',
            'sources' => array('Medical AI Research', 'Clinical Guidelines'),
        ),
        'protein' => array(
            'unit' => 'g/dL',
            'range' => '6.0-8.3',
            'optimal' => '6.5-8.0',
            'evidence_level' => 'A',
            'sources' => array('Medical AI Research', 'Clinical Guidelines'),
        ),
        'albumin' => array(
            'unit' => 'g/dL',
            'range' => '3.4-5.4',
            'optimal' => '3.8-5.0',
            'evidence_level' => 'A',
            'sources' => array('Medical AI Research', 'Clinical Guidelines'),
        ),
        'bun' => array(
            'unit' => 'mg/dL',
            'range' => '7-20',
            'optimal' => '8-18',
            'evidence_level' => 'A',
            'sources' => array('Medical AI Research', 'Clinical Guidelines'),
        ),
        'creatinine' => array(
            'unit' => 'mg/dL',
            'range' => '0.7-1.3',
            'optimal' => '0.8-1.2',
            'evidence_level' => 'A',
            'sources' => array('Medical AI Research', 'Clinical Guidelines'),
        ),
        'gfr' => array(
            'unit' => 'mL/min/1.73m²',
            'range' => '90-120',
            'optimal' => '90-110',
            'evidence_level' => 'A',
            'sources' => array('Medical AI Research', 'Clinical Guidelines'),
        ),
        'ast' => array(
            'unit' => 'U/L',
            'range' => '10-40',
            'optimal' => '15-35',
            'evidence_level' => 'A',
            'sources' => array('Medical AI Research', 'Clinical Guidelines'),
        ),
        'alt' => array(
            'unit' => 'U/L',
            'range' => '7-56',
            'optimal' => '10-40',
            'evidence_level' => 'A',
            'sources' => array('Medical AI Research', 'Clinical Guidelines'),
        ),
        'alkaline_phosphatase' => array(
            'unit' => 'U/L',
            'range' => '44-147',
            'optimal' => '50-120',
            'evidence_level' => 'A',
            'sources' => array('Medical AI Research', 'Clinical Guidelines'),
        ),
        'vitamin_d' => array(
            'unit' => 'ng/mL',
            'range' => '30-100',
            'optimal' => '40-80',
            'evidence_level' => 'A',
            'sources' => array('Medical AI Research', 'Clinical Guidelines'),
        ),
        'b12' => array(
            'unit' => 'pg/mL',
            'range' => '200-900',
            'optimal' => '400-800',
            'evidence_level' => 'A',
            'sources' => array('Medical AI Research', 'Clinical Guidelines'),
        ),
        'tsh' => array(
            'unit' => 'μIU/mL',
            'range' => '0.4-4.0',
            'optimal' => '1.0-2.5',
            'evidence_level' => 'A',
            'sources' => array('Medical AI Research', 'Clinical Guidelines'),
        ),
    ),
);
