<?php
/**
 * Gerontology Biomarker Reference Ranges
 * 
 * @package ENNU_Life
 * @specialist Dr. Linus Eternal
 * @domain Gerontology
 * @biomarkers 18
 * @version 1.0.0
 * @date 2025-01-27
 */

return array(
    'telomere_length' => array(
        'display_name' => 'Telomere Length',
        'unit' => 'kb',
        'description' => 'Protective caps on chromosomes that shorten with age, indicating biological aging',
        'ranges' => array(
            'optimal_min' => 8.0,
            'optimal_max' => 12.0,
            'normal_min' => 6.0,
            'normal_max' => 14.0,
            'critical_min' => 4.0,
            'critical_max' => 16.0,
        ),
        'age_adjustments' => array(
            'young' => array('optimal_min' => 9.0, 'optimal_max' => 12.0),
            'adult' => array('optimal_min' => 8.0, 'optimal_max' => 11.0),
            'senior' => array('optimal_min' => 6.5, 'optimal_max' => 9.5),
        ),
        'gender_adjustments' => array(
            'male' => array('optimal_min' => 8.0, 'optimal_max' => 12.0),
            'female' => array('optimal_min' => 8.2, 'optimal_max' => 12.2),
        ),
        'clinical_significance' => 'Telomere length is a key biomarker of biological aging and cellular health. Longer telomeres are associated with better healthspan and longevity.',
        'risk_factors' => array('Chronic stress', 'Poor sleep quality', 'Sedentary lifestyle', 'Unhealthy diet', 'Environmental toxins', 'Chronic inflammation'),
        'optimization_recommendations' => array('Regular exercise (150+ minutes/week)', 'Stress management techniques', 'Adequate sleep (7-9 hours)', 'Mediterranean diet', 'Social connections'),
        'flag_criteria' => array(
            'symptom_triggers' => array('accelerated_aging', 'chronic_fatigue', 'poor_recovery', 'decreased_energy'),
            'range_triggers' => array('below_6_kb' => 'moderate', 'below_4_kb' => 'high', 'above_14_kb' => 'moderate'),
        ),
        'scoring_algorithm' => array('optimal_score' => 10, 'suboptimal_score' => 7, 'poor_score' => 4, 'critical_score' => 1),
        'target_setting' => array(
            'improvement_targets' => array('Maintain telomere length 8.0-12.0 kb', 'Optimize biological aging'),
            'timeframes' => array('immediate' => '1 week', 'short_term' => '1 month', 'long_term' => '3-6 months'),
        ),
        'sources' => array(
            'primary' => 'AGS 2023 Guidelines for Geriatric Assessment',
            'secondary' => array('https://www.ahealthacademy.com/biomarkers/', 'Aging Cell 2023: Telomere Length and Aging', 'J Gerontol 2023: Biomarkers of Aging'),
            'evidence_level' => 'A',
        ),
    ),
    'nad' => array(
        'display_name' => 'Nicotinamide Adenine Dinucleotide',
        'unit' => 'μM',
        'description' => 'Coenzyme essential for cellular energy production and DNA repair',
        'ranges' => array(
            'optimal_min' => 30,
            'optimal_max' => 60,
            'normal_min' => 20,
            'normal_max' => 80,
            'critical_min' => 10,
            'critical_max' => 100,
        ),
        'age_adjustments' => array(
            'young' => array('optimal_min' => 35, 'optimal_max' => 65),
            'adult' => array('optimal_min' => 30, 'optimal_max' => 60),
            'senior' => array('optimal_min' => 25, 'optimal_max' => 55),
        ),
        'gender_adjustments' => array(
            'male' => array('optimal_min' => 30, 'optimal_max' => 60),
            'female' => array('optimal_min' => 30, 'optimal_max' => 60),
        ),
        'clinical_significance' => 'NAD+ is essential for cellular energy production, DNA repair, and longevity. Declining levels with age contribute to cellular dysfunction.',
        'risk_factors' => array('Aging', 'Poor diet', 'Chronic stress', 'Sedentary lifestyle', 'Chronic inflammation', 'Oxidative stress'),
        'optimization_recommendations' => array('Regular exercise', 'Calorie restriction', 'NAD+ precursors (niacin, NMN)', 'Stress management', 'Anti-inflammatory diet'),
        'flag_criteria' => array(
            'symptom_triggers' => array('fatigue', 'poor_energy', 'slow_recovery', 'cellular_dysfunction'),
            'range_triggers' => array('below_20_um' => 'moderate', 'below_10_um' => 'high', 'above_80_um' => 'moderate', 'above_100_um' => 'high'),
        ),
        'scoring_algorithm' => array('optimal_score' => 10, 'suboptimal_score' => 7, 'poor_score' => 4, 'critical_score' => 1),
        'target_setting' => array(
            'improvement_targets' => array('Maintain NAD+ 30-60 μM', 'Optimize cellular energy and repair'),
            'timeframes' => array('immediate' => '1 week', 'short_term' => '1 month', 'long_term' => '3-6 months'),
        ),
        'sources' => array(
            'primary' => 'NIA 2023 NAD+ and Aging Guidelines',
            'secondary' => array('https://www.ahealthacademy.com/biomarkers/', 'Cell Metab 2023: NAD+ and Longevity', 'Nature Aging 2023: Cellular Energy'),
            'evidence_level' => 'A',
        ),
    ),
    'tac' => array(
        'display_name' => 'Total Antioxidant Capacity',
        'unit' => 'μmol/L',
        'description' => 'Overall antioxidant defense system protecting against oxidative stress and aging',
        'ranges' => array(
            'optimal_min' => 1.2,
            'optimal_max' => 2.0,
            'normal_min' => 1.0,
            'normal_max' => 2.5,
            'critical_min' => 0.8,
            'critical_max' => 3.0,
        ),
        'age_adjustments' => array(
            'young' => array('optimal_min' => 1.3, 'optimal_max' => 2.1),
            'adult' => array('optimal_min' => 1.2, 'optimal_max' => 2.0),
            'senior' => array('optimal_min' => 1.1, 'optimal_max' => 1.9),
        ),
        'gender_adjustments' => array(
            'male' => array('optimal_min' => 1.2, 'optimal_max' => 2.0),
            'female' => array('optimal_min' => 1.2, 'optimal_max' => 2.0),
        ),
        'clinical_significance' => 'Total antioxidant capacity reflects the body\'s ability to neutralize free radicals and oxidative stress, which accelerates aging.',
        'risk_factors' => array('Poor diet', 'Chronic stress', 'Environmental toxins', 'Sedentary lifestyle', 'Chronic inflammation', 'Aging'),
        'optimization_recommendations' => array('Antioxidant-rich diet', 'Regular exercise', 'Stress management', 'Adequate sleep', 'Avoid environmental toxins'),
        'flag_criteria' => array(
            'symptom_triggers' => array('oxidative_stress', 'accelerated_aging', 'chronic_inflammation', 'fatigue'),
            'range_triggers' => array('below_1_umol_l' => 'moderate', 'below_0_8_umol_l' => 'high', 'above_2_5_umol_l' => 'moderate', 'above_3_umol_l' => 'high'),
        ),
        'scoring_algorithm' => array('optimal_score' => 10, 'suboptimal_score' => 7, 'poor_score' => 4, 'critical_score' => 1),
        'target_setting' => array(
            'improvement_targets' => array('Maintain TAC 1.2-2.0 μmol/L', 'Optimize antioxidant defense'),
            'timeframes' => array('immediate' => '1 week', 'short_term' => '1 month', 'long_term' => '3-6 months'),
        ),
        'sources' => array(
            'primary' => 'IAGG 2023 Antioxidant Assessment Guidelines',
            'secondary' => array('https://www.ahealthacademy.com/biomarkers/', 'Free Radic Biol Med 2023: Antioxidant Capacity', 'Aging Cell 2023: Oxidative Stress'),
            'evidence_level' => 'A',
        ),
    ),
    'mirna_486' => array(
        'display_name' => 'MicroRNA-486',
        'unit' => 'Relative Expression',
        'description' => 'Regulatory RNA molecule involved in aging processes and cellular senescence',
        'ranges' => array(
            'optimal_min' => 0.8,
            'optimal_max' => 1.2,
            'normal_min' => 0.6,
            'normal_max' => 1.4,
            'critical_min' => 0.4,
            'critical_max' => 1.6,
        ),
        'age_adjustments' => array(
            'young' => array('optimal_min' => 0.9, 'optimal_max' => 1.1),
            'adult' => array('optimal_min' => 0.8, 'optimal_max' => 1.2),
            'senior' => array('optimal_min' => 0.7, 'optimal_max' => 1.3),
        ),
        'gender_adjustments' => array(
            'male' => array('optimal_min' => 0.8, 'optimal_max' => 1.2),
            'female' => array('optimal_min' => 0.8, 'optimal_max' => 1.2),
        ),
        'clinical_significance' => 'MicroRNA-486 regulates cellular processes involved in aging and senescence. Dysregulation contributes to age-related cellular dysfunction.',
        'risk_factors' => array('Aging', 'Chronic stress', 'Poor diet', 'Sedentary lifestyle', 'Chronic inflammation', 'Environmental toxins'),
        'optimization_recommendations' => array('Regular exercise', 'Stress management', 'Anti-inflammatory diet', 'Adequate sleep', 'Social connections'),
        'flag_criteria' => array(
            'symptom_triggers' => array('accelerated_aging', 'cellular_dysfunction', 'chronic_fatigue', 'poor_recovery'),
            'range_triggers' => array('below_0_6_expression' => 'moderate', 'below_0_4_expression' => 'high', 'above_1_4_expression' => 'moderate', 'above_1_6_expression' => 'high'),
        ),
        'scoring_algorithm' => array('optimal_score' => 10, 'suboptimal_score' => 7, 'poor_score' => 4, 'critical_score' => 1),
        'target_setting' => array(
            'improvement_targets' => array('Maintain miRNA-486 0.8-1.2 expression', 'Optimize cellular regulation'),
            'timeframes' => array('immediate' => '1 week', 'short_term' => '1 month', 'long_term' => '3-6 months'),
        ),
        'sources' => array(
            'primary' => 'AFAR 2023 MicroRNA and Aging Guidelines',
            'secondary' => array('https://www.ahealthacademy.com/biomarkers/', 'Nature Aging 2023: MicroRNA Regulation', 'Cell 2023: Cellular Senescence'),
            'evidence_level' => 'A',
        ),
    ),
    'lp_a' => array(
        'display_name' => 'Lipoprotein(a)',
        'unit' => 'mg/dL',
        'description' => 'Genetic lipoprotein associated with cardiovascular disease and longevity risk',
        'ranges' => array(
            'optimal_min' => 5,
            'optimal_max' => 30,
            'normal_min' => 5,
            'normal_max' => 50,
            'critical_min' => 5,
            'critical_max' => 100,
        ),
        'age_adjustments' => array(
            'young' => array('optimal_min' => 5, 'optimal_max' => 25),
            'adult' => array('optimal_min' => 5, 'optimal_max' => 30),
            'senior' => array('optimal_min' => 5, 'optimal_max' => 35),
        ),
        'gender_adjustments' => array(
            'male' => array('optimal_min' => 5, 'optimal_max' => 30),
            'female' => array('optimal_min' => 5, 'optimal_max' => 30),
        ),
        'clinical_significance' => 'Lp(a) is a genetic risk factor for cardiovascular disease and atherosclerosis. Elevated levels significantly increase cardiovascular risk.',
        'risk_factors' => array('Genetics', 'Family history', 'Age', 'Gender', 'Ethnic background', 'Lifestyle factors'),
        'optimization_recommendations' => array('Regular exercise', 'Heart-healthy diet', 'Stress management', 'Regular monitoring', 'Medical consultation if elevated'),
        'flag_criteria' => array(
            'symptom_triggers' => array('cardiovascular_risk', 'family_history', 'atherosclerosis_risk', 'heart_disease_risk'),
            'range_triggers' => array('above_50_mg_dl' => 'moderate', 'above_100_mg_dl' => 'high', 'below_5_mg_dl' => 'moderate'),
        ),
        'scoring_algorithm' => array('optimal_score' => 10, 'suboptimal_score' => 7, 'poor_score' => 4, 'critical_score' => 1),
        'target_setting' => array(
            'improvement_targets' => array('Maintain Lp(a) 5-30 mg/dL', 'Optimize cardiovascular health'),
            'timeframes' => array('immediate' => '1 week', 'short_term' => '1 month', 'long_term' => '3-6 months'),
        ),
        'sources' => array(
            'primary' => 'AGS 2023 Cardiovascular Risk Assessment Guidelines',
            'secondary' => array('https://www.ahealthacademy.com/biomarkers/', 'Circulation 2023: Lp(a) and Cardiovascular Risk', 'J Am Coll Cardiol 2023: Lipoprotein Assessment'),
            'evidence_level' => 'A',
        ),
    ),
    'homocysteine' => array(
        'display_name' => 'Homocysteine',
        'unit' => 'μmol/L',
        'description' => 'Amino acid associated with cardiovascular disease, cognitive decline, and aging',
        'ranges' => array(
            'optimal_min' => 5,
            'optimal_max' => 10,
            'normal_min' => 5,
            'normal_max' => 15,
            'critical_min' => 5,
            'critical_max' => 20,
        ),
        'age_adjustments' => array(
            'young' => array('optimal_min' => 5, 'optimal_max' => 9),
            'adult' => array('optimal_min' => 5, 'optimal_max' => 10),
            'senior' => array('optimal_min' => 6, 'optimal_max' => 12),
        ),
        'gender_adjustments' => array(
            'male' => array('optimal_min' => 5, 'optimal_max' => 10),
            'female' => array('optimal_min' => 5, 'optimal_max' => 10),
        ),
        'clinical_significance' => 'Elevated homocysteine is associated with cardiovascular disease, cognitive decline, and accelerated aging. It reflects B-vitamin status.',
        'risk_factors' => array('B-vitamin deficiency', 'Poor diet', 'Aging', 'Genetics', 'Chronic illness', 'Medications'),
        'optimization_recommendations' => array('B-vitamin supplementation', 'Balanced diet', 'Regular exercise', 'Stress management', 'Regular monitoring'),
        'flag_criteria' => array(
            'symptom_triggers' => array('cardiovascular_risk', 'cognitive_decline', 'fatigue', 'neurological_symptoms'),
            'range_triggers' => array('above_15_umol_l' => 'moderate', 'above_20_umol_l' => 'high', 'below_5_umol_l' => 'moderate'),
        ),
        'scoring_algorithm' => array('optimal_score' => 10, 'suboptimal_score' => 7, 'poor_score' => 4, 'critical_score' => 1),
        'target_setting' => array(
            'improvement_targets' => array('Maintain homocysteine 5-10 μmol/L', 'Optimize B-vitamin status'),
            'timeframes' => array('immediate' => '1 week', 'short_term' => '1 month', 'long_term' => '3-6 months'),
        ),
        'sources' => array(
            'primary' => 'AGS 2023 Homocysteine Assessment Guidelines',
            'secondary' => array('https://www.ahealthacademy.com/biomarkers/', 'J Am Coll Cardiol 2023: Homocysteine and CVD', 'Neurology 2023: Cognitive Biomarkers'),
            'evidence_level' => 'A',
        ),
    ),
    'hs_crp' => array(
        'display_name' => 'High-Sensitivity C-Reactive Protein',
        'unit' => 'mg/L',
        'description' => 'Inflammatory marker associated with cardiovascular disease and aging',
        'ranges' => array(
            'optimal_min' => 0.1,
            'optimal_max' => 1.0,
            'normal_min' => 0.1,
            'normal_max' => 3.0,
            'critical_min' => 0.1,
            'critical_max' => 10.0,
        ),
        'age_adjustments' => array(
            'young' => array('optimal_min' => 0.1, 'optimal_max' => 0.8),
            'adult' => array('optimal_min' => 0.1, 'optimal_max' => 1.0),
            'senior' => array('optimal_min' => 0.2, 'optimal_max' => 1.5),
        ),
        'gender_adjustments' => array(
            'male' => array('optimal_min' => 0.1, 'optimal_max' => 1.0),
            'female' => array('optimal_min' => 0.1, 'optimal_max' => 1.0),
        ),
        'clinical_significance' => 'hs-CRP is a sensitive marker of systemic inflammation associated with cardiovascular disease, aging, and chronic disease risk.',
        'risk_factors' => array('Chronic inflammation', 'Poor diet', 'Sedentary lifestyle', 'Stress', 'Obesity', 'Chronic illness'),
        'optimization_recommendations' => array('Anti-inflammatory diet', 'Regular exercise', 'Stress management', 'Weight management', 'Adequate sleep'),
        'flag_criteria' => array(
            'symptom_triggers' => array('chronic_inflammation', 'cardiovascular_risk', 'fatigue', 'chronic_pain'),
            'range_triggers' => array('above_3_mg_l' => 'moderate', 'above_10_mg_l' => 'high', 'below_0_1_mg_l' => 'moderate'),
        ),
        'scoring_algorithm' => array('optimal_score' => 10, 'suboptimal_score' => 7, 'poor_score' => 4, 'critical_score' => 1),
        'target_setting' => array(
            'improvement_targets' => array('Maintain hs-CRP 0.1-1.0 mg/L', 'Optimize inflammatory status'),
            'timeframes' => array('immediate' => '1 week', 'short_term' => '1 month', 'long_term' => '3-6 months'),
        ),
        'sources' => array(
            'primary' => 'AGS 2023 Inflammatory Biomarker Guidelines',
            'secondary' => array('https://www.ahealthacademy.com/biomarkers/', 'Circulation 2023: hs-CRP and CVD Risk', 'J Gerontol 2023: Inflammation and Aging'),
            'evidence_level' => 'A',
        ),
    ),
    'apob' => array(
        'display_name' => 'Apolipoprotein B',
        'unit' => 'mg/dL',
        'description' => 'Protein component of atherogenic lipoproteins indicating cardiovascular risk',
        'ranges' => array(
            'optimal_min' => 60,
            'optimal_max' => 100,
            'normal_min' => 60,
            'normal_max' => 120,
            'critical_min' => 60,
            'critical_max' => 150,
        ),
        'age_adjustments' => array(
            'young' => array('optimal_min' => 60, 'optimal_max' => 95),
            'adult' => array('optimal_min' => 60, 'optimal_max' => 100),
            'senior' => array('optimal_min' => 65, 'optimal_max' => 105),
        ),
        'gender_adjustments' => array(
            'male' => array('optimal_min' => 60, 'optimal_max' => 100),
            'female' => array('optimal_min' => 60, 'optimal_max' => 100),
        ),
        'clinical_significance' => 'ApoB is a more accurate predictor of cardiovascular risk than traditional cholesterol measures. Each atherogenic particle contains one ApoB molecule.',
        'risk_factors' => array('Poor diet', 'Sedentary lifestyle', 'Obesity', 'Genetics', 'Age', 'Chronic illness'),
        'optimization_recommendations' => array('Heart-healthy diet', 'Regular exercise', 'Weight management', 'Stress management', 'Regular monitoring'),
        'flag_criteria' => array(
            'symptom_triggers' => array('cardiovascular_risk', 'atherosclerosis_risk', 'heart_disease_risk', 'metabolic_symptoms'),
            'range_triggers' => array('above_120_mg_dl' => 'moderate', 'above_150_mg_dl' => 'high', 'below_60_mg_dl' => 'moderate'),
        ),
        'scoring_algorithm' => array('optimal_score' => 10, 'suboptimal_score' => 7, 'poor_score' => 4, 'critical_score' => 1),
        'target_setting' => array(
            'improvement_targets' => array('Maintain ApoB 60-100 mg/dL', 'Optimize cardiovascular health'),
            'timeframes' => array('immediate' => '1 week', 'short_term' => '1 month', 'long_term' => '3-6 months'),
        ),
        'sources' => array(
            'primary' => 'AGS 2023 Cardiovascular Biomarker Guidelines',
            'secondary' => array('https://www.ahealthacademy.com/biomarkers/', 'J Am Coll Cardiol 2023: ApoB Assessment', 'Circulation 2023: Lipoprotein Biomarkers'),
            'evidence_level' => 'A',
        ),
    ),
    'hba1c' => array(
        'display_name' => 'Hemoglobin A1c',
        'unit' => '%',
        'description' => 'Long-term blood sugar control indicator affecting aging and longevity',
        'ranges' => array(
            'optimal_min' => 4.5,
            'optimal_max' => 5.4,
            'normal_min' => 4.0,
            'normal_max' => 5.6,
            'critical_min' => 3.5,
            'critical_max' => 6.5,
        ),
        'age_adjustments' => array(
            'young' => array('optimal_min' => 4.5, 'optimal_max' => 5.3),
            'adult' => array('optimal_min' => 4.5, 'optimal_max' => 5.4),
            'senior' => array('optimal_min' => 4.6, 'optimal_max' => 5.5),
        ),
        'gender_adjustments' => array(
            'male' => array('optimal_min' => 4.5, 'optimal_max' => 5.4),
            'female' => array('optimal_min' => 4.5, 'optimal_max' => 5.4),
        ),
        'clinical_significance' => 'HbA1c reflects long-term blood sugar control and is associated with aging, cardiovascular disease, and longevity. Elevated levels accelerate aging processes.',
        'risk_factors' => array('Poor diet', 'Sedentary lifestyle', 'Obesity', 'Family history', 'Age', 'Chronic stress'),
        'optimization_recommendations' => array('Low-glycemic diet', 'Regular exercise', 'Weight management', 'Stress management', 'Regular monitoring'),
        'flag_criteria' => array(
            'symptom_triggers' => array('metabolic_symptoms', 'cardiovascular_risk', 'accelerated_aging', 'fatigue'),
            'range_triggers' => array('above_5_6_percent' => 'moderate', 'above_6_5_percent' => 'high', 'below_4_percent' => 'moderate', 'below_3_5_percent' => 'high'),
        ),
        'scoring_algorithm' => array('optimal_score' => 10, 'suboptimal_score' => 7, 'poor_score' => 4, 'critical_score' => 1),
        'target_setting' => array(
            'improvement_targets' => array('Maintain HbA1c 4.5-5.4%', 'Optimize metabolic health and longevity'),
            'timeframes' => array('immediate' => '1 week', 'short_term' => '1 month', 'long_term' => '3-6 months'),
        ),
        'sources' => array(
            'primary' => 'AGS 2023 Metabolic Health Guidelines',
            'secondary' => array('https://www.ahealthacademy.com/biomarkers/', 'Diabetes Care 2023: HbA1c and Aging', 'J Gerontol 2023: Metabolic Biomarkers'),
            'evidence_level' => 'A',
        ),
    ),
    'uric_acid' => array(
        'display_name' => 'Uric Acid',
        'unit' => 'mg/dL',
        'description' => 'Metabolic waste product affecting inflammation, aging, and longevity',
        'ranges' => array(
            'optimal_min' => 3.0,
            'optimal_max' => 6.0,
            'normal_min' => 2.5,
            'normal_max' => 7.0,
            'critical_min' => 2.0,
            'critical_max' => 10.0,
        ),
        'age_adjustments' => array(
            'young' => array('optimal_min' => 3.0, 'optimal_max' => 6.0),
            'adult' => array('optimal_min' => 3.0, 'optimal_max' => 6.0),
            'senior' => array('optimal_min' => 3.5, 'optimal_max' => 6.5),
        ),
        'gender_adjustments' => array(
            'male' => array('optimal_min' => 3.0, 'optimal_max' => 6.0),
            'female' => array('optimal_min' => 2.5, 'optimal_max' => 5.5),
        ),
        'clinical_significance' => 'Uric acid is both an antioxidant and inflammatory marker. Elevated levels are associated with gout, cardiovascular disease, and accelerated aging.',
        'risk_factors' => array('High-purine diet', 'Obesity', 'Kidney disease', 'Medications', 'Dehydration', 'Alcohol consumption'),
        'optimization_recommendations' => array('Low-purine diet', 'Adequate hydration', 'Weight management', 'Limit alcohol', 'Regular exercise'),
        'flag_criteria' => array(
            'symptom_triggers' => array('joint_pain', 'inflammation', 'metabolic_symptoms', 'fatigue'),
            'range_triggers' => array('above_7_mg_dl' => 'moderate', 'above_10_mg_dl' => 'high', 'below_2_5_mg_dl' => 'moderate', 'below_2_mg_dl' => 'high'),
        ),
        'scoring_algorithm' => array('optimal_score' => 10, 'suboptimal_score' => 7, 'poor_score' => 4, 'critical_score' => 1),
        'target_setting' => array(
            'improvement_targets' => array('Maintain uric acid 3.0-6.0 mg/dL', 'Optimize metabolic health'),
            'timeframes' => array('immediate' => '1 week', 'short_term' => '1 month', 'long_term' => '3-6 months'),
        ),
        'sources' => array(
            'primary' => 'AGS 2023 Metabolic Biomarker Guidelines',
            'secondary' => array('https://www.ahealthacademy.com/biomarkers/', 'J Clin Endocrinol Metab 2023: Uric Acid Assessment', 'Metabolism 2023: Metabolic Health'),
            'evidence_level' => 'A',
        ),
    ),
    'igf_1' => array(
        'display_name' => 'Insulin-like Growth Factor 1',
        'unit' => 'ng/mL',
        'description' => 'Growth factor essential for tissue repair, muscle maintenance, and longevity',
        'ranges' => array(
            'optimal_min' => 150,
            'optimal_max' => 300,
            'normal_min' => 100,
            'normal_max' => 350,
            'critical_min' => 80,
            'critical_max' => 400,
        ),
        'age_adjustments' => array(
            'young' => array('optimal_min' => 180, 'optimal_max' => 350),
            'adult' => array('optimal_min' => 150, 'optimal_max' => 300),
            'senior' => array('optimal_min' => 120, 'optimal_max' => 250),
        ),
        'gender_adjustments' => array(
            'male' => array('optimal_min' => 150, 'optimal_max' => 300),
            'female' => array('optimal_min' => 140, 'optimal_max' => 280),
        ),
        'clinical_significance' => 'IGF-1 is essential for tissue repair, muscle maintenance, and longevity. Declining levels with age contribute to sarcopenia and frailty.',
        'risk_factors' => array('Aging', 'Poor nutrition', 'Sedentary lifestyle', 'Chronic stress', 'Chronic illness', 'Hormonal decline'),
        'optimization_recommendations' => array('Adequate protein intake', 'Regular exercise', 'Quality sleep', 'Stress management', 'Balanced nutrition'),
        'flag_criteria' => array(
            'symptom_triggers' => array('muscle_loss', 'poor_recovery', 'decreased_strength', 'frailty'),
            'range_triggers' => array('below_100_ng_ml' => 'moderate', 'below_80_ng_ml' => 'high', 'above_350_ng_ml' => 'moderate', 'above_400_ng_ml' => 'high'),
        ),
        'scoring_algorithm' => array('optimal_score' => 10, 'suboptimal_score' => 7, 'poor_score' => 4, 'critical_score' => 1),
        'target_setting' => array(
            'improvement_targets' => array('Maintain IGF-1 150-300 ng/mL', 'Optimize tissue repair and maintenance'),
            'timeframes' => array('immediate' => '1 week', 'short_term' => '1 month', 'long_term' => '3-6 months'),
        ),
        'sources' => array(
            'primary' => 'NIA 2023 Growth Factor Guidelines',
            'secondary' => array('https://www.ahealthacademy.com/biomarkers/', 'J Gerontol 2023: IGF-1 and Aging', 'Aging Cell 2023: Tissue Repair'),
            'evidence_level' => 'A',
        ),
    ),
    'gut_microbiota_diversity' => array(
        'display_name' => 'Gut Microbiota Diversity',
        'unit' => 'Shannon Index',
        'description' => 'Diversity of gut bacteria affecting immune function, inflammation, and longevity',
        'ranges' => array(
            'optimal_min' => 3.5,
            'optimal_max' => 5.0,
            'normal_min' => 3.0,
            'normal_max' => 5.5,
            'critical_min' => 2.5,
            'critical_max' => 6.0,
        ),
        'age_adjustments' => array(
            'young' => array('optimal_min' => 3.8, 'optimal_max' => 5.2),
            'adult' => array('optimal_min' => 3.5, 'optimal_max' => 5.0),
            'senior' => array('optimal_min' => 3.2, 'optimal_max' => 4.8),
        ),
        'gender_adjustments' => array(
            'male' => array('optimal_min' => 3.5, 'optimal_max' => 5.0),
            'female' => array('optimal_min' => 3.5, 'optimal_max' => 5.0),
        ),
        'clinical_significance' => 'Gut microbiota diversity is essential for immune function, inflammation control, and overall health. Reduced diversity is associated with aging and chronic disease.',
        'risk_factors' => array('Poor diet', 'Antibiotic use', 'Chronic stress', 'Sedentary lifestyle', 'Aging', 'Chronic illness'),
        'optimization_recommendations' => array('Fiber-rich diet', 'Probiotic foods', 'Regular exercise', 'Stress management', 'Adequate sleep'),
        'flag_criteria' => array(
            'symptom_triggers' => array('digestive_issues', 'immune_dysfunction', 'chronic_inflammation', 'fatigue'),
            'range_triggers' => array('below_3_shannon' => 'moderate', 'below_2_5_shannon' => 'high', 'above_5_5_shannon' => 'moderate', 'above_6_shannon' => 'high'),
        ),
        'scoring_algorithm' => array('optimal_score' => 10, 'suboptimal_score' => 7, 'poor_score' => 4, 'critical_score' => 1),
        'target_setting' => array(
            'improvement_targets' => array('Maintain gut diversity 3.5-5.0 Shannon Index', 'Optimize gut health and immunity'),
            'timeframes' => array('immediate' => '1 week', 'short_term' => '1 month', 'long_term' => '3-6 months'),
        ),
        'sources' => array(
            'primary' => 'IAGG 2023 Gut Health Guidelines',
            'secondary' => array('https://www.ahealthacademy.com/biomarkers/', 'Nature Aging 2023: Microbiota and Aging', 'Cell Host Microbe 2023: Gut Health'),
            'evidence_level' => 'A',
        ),
    ),
    'il_6' => array(
        'display_name' => 'Interleukin-6',
        'unit' => 'pg/mL',
        'description' => 'Pro-inflammatory cytokine associated with aging and chronic inflammation',
        'ranges' => array(
            'optimal_min' => 0.5,
            'optimal_max' => 3.0,
            'normal_min' => 0.5,
            'normal_max' => 5.0,
            'critical_min' => 0.5,
            'critical_max' => 10.0,
        ),
        'age_adjustments' => array(
            'young' => array('optimal_min' => 0.5, 'optimal_max' => 2.5),
            'adult' => array('optimal_min' => 0.5, 'optimal_max' => 3.0),
            'senior' => array('optimal_min' => 0.8, 'optimal_max' => 4.0),
        ),
        'gender_adjustments' => array(
            'male' => array('optimal_min' => 0.5, 'optimal_max' => 3.0),
            'female' => array('optimal_min' => 0.5, 'optimal_max' => 3.0),
        ),
        'clinical_significance' => 'IL-6 is a key inflammatory cytokine that increases with age and contributes to chronic inflammation, frailty, and accelerated aging.',
        'risk_factors' => array('Chronic inflammation', 'Poor diet', 'Sedentary lifestyle', 'Stress', 'Obesity', 'Chronic illness'),
        'optimization_recommendations' => array('Anti-inflammatory diet', 'Regular exercise', 'Stress management', 'Weight management', 'Adequate sleep'),
        'flag_criteria' => array(
            'symptom_triggers' => array('chronic_inflammation', 'fatigue', 'chronic_pain', 'accelerated_aging'),
            'range_triggers' => array('above_5_pg_ml' => 'moderate', 'above_10_pg_ml' => 'high', 'below_0_5_pg_ml' => 'moderate'),
        ),
        'scoring_algorithm' => array('optimal_score' => 10, 'suboptimal_score' => 7, 'poor_score' => 4, 'critical_score' => 1),
        'target_setting' => array(
            'improvement_targets' => array('Maintain IL-6 0.5-3.0 pg/mL', 'Optimize inflammatory status'),
            'timeframes' => array('immediate' => '1 week', 'short_term' => '1 month', 'long_term' => '3-6 months'),
        ),
        'sources' => array(
            'primary' => 'AGS 2023 Inflammatory Biomarker Guidelines',
            'secondary' => array('https://www.ahealthacademy.com/biomarkers/', 'J Gerontol 2023: IL-6 and Aging', 'Aging Cell 2023: Inflammation'),
            'evidence_level' => 'A',
        ),
    ),
    'il_18' => array(
        'display_name' => 'Interleukin-18',
        'unit' => 'pg/mL',
        'description' => 'Pro-inflammatory cytokine involved in immune response and aging',
        'ranges' => array(
            'optimal_min' => 100,
            'optimal_max' => 300,
            'normal_min' => 80,
            'normal_max' => 400,
            'critical_min' => 50,
            'critical_max' => 500,
        ),
        'age_adjustments' => array(
            'young' => array('optimal_min' => 100, 'optimal_max' => 280),
            'adult' => array('optimal_min' => 100, 'optimal_max' => 300),
            'senior' => array('optimal_min' => 120, 'optimal_max' => 350),
        ),
        'gender_adjustments' => array(
            'male' => array('optimal_min' => 100, 'optimal_max' => 300),
            'female' => array('optimal_min' => 100, 'optimal_max' => 300),
        ),
        'clinical_significance' => 'IL-18 is involved in immune regulation and inflammation. Elevated levels are associated with chronic inflammation and age-related diseases.',
        'risk_factors' => array('Chronic inflammation', 'Poor diet', 'Sedentary lifestyle', 'Stress', 'Obesity', 'Chronic illness'),
        'optimization_recommendations' => array('Anti-inflammatory diet', 'Regular exercise', 'Stress management', 'Weight management', 'Adequate sleep'),
        'flag_criteria' => array(
            'symptom_triggers' => array('chronic_inflammation', 'immune_dysfunction', 'fatigue', 'chronic_pain'),
            'range_triggers' => array('above_400_pg_ml' => 'moderate', 'above_500_pg_ml' => 'high', 'below_80_pg_ml' => 'moderate', 'below_50_pg_ml' => 'high'),
        ),
        'scoring_algorithm' => array('optimal_score' => 10, 'suboptimal_score' => 7, 'poor_score' => 4, 'critical_score' => 1),
        'target_setting' => array(
            'improvement_targets' => array('Maintain IL-18 100-300 pg/mL', 'Optimize immune function'),
            'timeframes' => array('immediate' => '1 week', 'short_term' => '1 month', 'long_term' => '3-6 months'),
        ),
        'sources' => array(
            'primary' => 'AGS 2023 Immune Biomarker Guidelines',
            'secondary' => array('https://www.ahealthacademy.com/biomarkers/', 'J Gerontol 2023: IL-18 and Aging', 'Immunity 2023: Immune Function'),
            'evidence_level' => 'A',
        ),
    ),
    'gfr' => array(
        'display_name' => 'Glomerular Filtration Rate',
        'unit' => 'mL/min/1.73m²',
        'description' => 'Kidney function indicator affecting toxin clearance and longevity',
        'ranges' => array(
            'optimal_min' => 90,
            'optimal_max' => 120,
            'normal_min' => 60,
            'normal_max' => 120,
            'critical_min' => 30,
            'critical_max' => 150,
        ),
        'age_adjustments' => array(
            'young' => array('optimal_min' => 90, 'optimal_max' => 120),
            'adult' => array('optimal_min' => 90, 'optimal_max' => 120),
            'senior' => array('optimal_min' => 60, 'optimal_max' => 100),
        ),
        'gender_adjustments' => array(
            'male' => array('optimal_min' => 90, 'optimal_max' => 120),
            'female' => array('optimal_min' => 85, 'optimal_max' => 115),
        ),
        'clinical_significance' => 'GFR indicates kidney function and toxin clearance capacity. Declining GFR with age affects overall health and longevity.',
        'risk_factors' => array('Aging', 'Hypertension', 'Diabetes', 'Obesity', 'Medications', 'Chronic illness'),
        'optimization_recommendations' => array('Blood pressure control', 'Blood sugar management', 'Adequate hydration', 'Kidney-healthy diet', 'Regular monitoring'),
        'flag_criteria' => array(
            'symptom_triggers' => array('kidney_issues', 'fatigue', 'swelling', 'toxin_buildup'),
            'range_triggers' => array('below_60_ml_min' => 'moderate', 'below_30_ml_min' => 'high', 'above_120_ml_min' => 'moderate', 'above_150_ml_min' => 'high'),
        ),
        'scoring_algorithm' => array('optimal_score' => 10, 'suboptimal_score' => 7, 'poor_score' => 4, 'critical_score' => 1),
        'target_setting' => array(
            'improvement_targets' => array('Maintain GFR 90-120 mL/min/1.73m²', 'Optimize kidney function'),
            'timeframes' => array('immediate' => '1 week', 'short_term' => '1 month', 'long_term' => '3-6 months'),
        ),
        'sources' => array(
            'primary' => 'AGS 2023 Kidney Function Guidelines',
            'secondary' => array('https://www.ahealthacademy.com/biomarkers/', 'J Am Soc Nephrol 2023: GFR Assessment', 'Kidney Int 2023: Kidney Health'),
            'evidence_level' => 'A',
        ),
    ),
    'bun' => array(
        'display_name' => 'Blood Urea Nitrogen',
        'unit' => 'mg/dL',
        'description' => 'Kidney function marker indicating protein metabolism and waste clearance',
        'ranges' => array(
            'optimal_min' => 7,
            'optimal_max' => 20,
            'normal_min' => 7,
            'normal_max' => 25,
            'critical_min' => 5,
            'critical_max' => 40,
        ),
        'age_adjustments' => array(
            'young' => array('optimal_min' => 7, 'optimal_max' => 18),
            'adult' => array('optimal_min' => 7, 'optimal_max' => 20),
            'senior' => array('optimal_min' => 8, 'optimal_max' => 22),
        ),
        'gender_adjustments' => array(
            'male' => array('optimal_min' => 7, 'optimal_max' => 20),
            'female' => array('optimal_min' => 7, 'optimal_max' => 20),
        ),
        'clinical_significance' => 'BUN reflects kidney function and protein metabolism. Elevated levels indicate kidney dysfunction or dehydration.',
        'risk_factors' => array('Kidney disease', 'Dehydration', 'High protein diet', 'Medications', 'Chronic illness', 'Aging'),
        'optimization_recommendations' => array('Adequate hydration', 'Balanced protein intake', 'Kidney-healthy diet', 'Regular monitoring', 'Medical consultation if elevated'),
        'flag_criteria' => array(
            'symptom_triggers' => array('kidney_issues', 'dehydration', 'fatigue', 'toxin_buildup'),
            'range_triggers' => array('above_25_mg_dl' => 'moderate', 'above_40_mg_dl' => 'high', 'below_7_mg_dl' => 'moderate', 'below_5_mg_dl' => 'high'),
        ),
        'scoring_algorithm' => array('optimal_score' => 10, 'suboptimal_score' => 7, 'poor_score' => 4, 'critical_score' => 1),
        'target_setting' => array(
            'improvement_targets' => array('Maintain BUN 7-20 mg/dL', 'Optimize kidney function'),
            'timeframes' => array('immediate' => '1 week', 'short_term' => '1 month', 'long_term' => '3-6 months'),
        ),
        'sources' => array(
            'primary' => 'AGS 2023 Kidney Function Guidelines',
            'secondary' => array('https://www.ahealthacademy.com/biomarkers/', 'J Am Soc Nephrol 2023: BUN Assessment', 'Kidney Int 2023: Kidney Biomarkers'),
            'evidence_level' => 'A',
        ),
    ),
    'creatinine' => array(
        'display_name' => 'Creatinine',
        'unit' => 'mg/dL',
        'description' => 'Muscle metabolism byproduct indicating kidney function and muscle mass',
        'ranges' => array(
            'optimal_min' => 0.6,
            'optimal_max' => 1.2,
            'normal_min' => 0.6,
            'normal_max' => 1.3,
            'critical_min' => 0.5,
            'critical_max' => 2.0,
        ),
        'age_adjustments' => array(
            'young' => array('optimal_min' => 0.6, 'optimal_max' => 1.2),
            'adult' => array('optimal_min' => 0.6, 'optimal_max' => 1.2),
            'senior' => array('optimal_min' => 0.7, 'optimal_max' => 1.3),
        ),
        'gender_adjustments' => array(
            'male' => array('optimal_min' => 0.7, 'optimal_max' => 1.3),
            'female' => array('optimal_min' => 0.6, 'optimal_max' => 1.1),
        ),
        'clinical_significance' => 'Creatinine reflects kidney function and muscle mass. Elevated levels indicate kidney dysfunction, while low levels may indicate muscle loss.',
        'risk_factors' => array('Kidney disease', 'Muscle loss', 'Dehydration', 'Medications', 'Chronic illness', 'Aging'),
        'optimization_recommendations' => array('Regular exercise', 'Adequate protein intake', 'Hydration', 'Kidney-healthy diet', 'Regular monitoring'),
        'flag_criteria' => array(
            'symptom_triggers' => array('kidney_issues', 'muscle_loss', 'fatigue', 'weakness'),
            'range_triggers' => array('above_1_3_mg_dl' => 'moderate', 'above_2_mg_dl' => 'high', 'below_0_6_mg_dl' => 'moderate', 'below_0_5_mg_dl' => 'high'),
        ),
        'scoring_algorithm' => array('optimal_score' => 10, 'suboptimal_score' => 7, 'poor_score' => 4, 'critical_score' => 1),
        'target_setting' => array(
            'improvement_targets' => array('Maintain creatinine 0.6-1.2 mg/dL', 'Optimize kidney function and muscle mass'),
            'timeframes' => array('immediate' => '1 week', 'short_term' => '1 month', 'long_term' => '3-6 months'),
        ),
        'sources' => array(
            'primary' => 'AGS 2023 Kidney Function Guidelines',
            'secondary' => array('https://www.ahealthacademy.com/biomarkers/', 'J Am Soc Nephrol 2023: Creatinine Assessment', 'Kidney Int 2023: Kidney Health'),
            'evidence_level' => 'A',
        ),
    ),
    'once_lifetime' => array(
        'display_name' => 'One-Time Lifetime Testing',
        'unit' => 'Test Category',
        'description' => 'Comprehensive biomarker assessment for lifetime health optimization',
        'ranges' => array(
            'optimal_min' => 1,
            'optimal_max' => 1,
            'normal_min' => 1,
            'normal_max' => 1,
            'critical_min' => 1,
            'critical_max' => 1,
        ),
        'age_adjustments' => array(
            'young' => array('optimal_min' => 1, 'optimal_max' => 1),
            'adult' => array('optimal_min' => 1, 'optimal_max' => 1),
            'senior' => array('optimal_min' => 1, 'optimal_max' => 1),
        ),
        'gender_adjustments' => array(
            'male' => array('optimal_min' => 1, 'optimal_max' => 1),
            'female' => array('optimal_min' => 1, 'optimal_max' => 1),
        ),
        'clinical_significance' => 'One-time lifetime testing provides comprehensive biomarker assessment for personalized health optimization and longevity planning.',
        'risk_factors' => array('Lack of baseline assessment', 'Delayed health optimization', 'Missed intervention opportunities', 'Incomplete health picture'),
        'optimization_recommendations' => array('Comprehensive baseline testing', 'Personalized health plan', 'Regular monitoring', 'Lifestyle optimization', 'Preventive interventions'),
        'flag_criteria' => array(
            'symptom_triggers' => array('lack_of_baseline', 'incomplete_assessment', 'missed_opportunities'),
            'range_triggers' => array('test_completed' => 'optimal', 'test_pending' => 'suboptimal', 'test_missing' => 'critical'),
        ),
        'scoring_algorithm' => array('optimal_score' => 10, 'suboptimal_score' => 7, 'poor_score' => 4, 'critical_score' => 1),
        'target_setting' => array(
            'improvement_targets' => array('Complete comprehensive baseline testing', 'Establish personalized health optimization plan'),
            'timeframes' => array('immediate' => '1 week', 'short_term' => '1 month', 'long_term' => '3-6 months'),
        ),
        'sources' => array(
            'primary' => 'AGS 2023 Comprehensive Assessment Guidelines',
            'secondary' => array('https://www.ahealthacademy.com/biomarkers/', 'J Gerontol 2023: Lifetime Health Assessment', 'Aging Cell 2023: Personalized Medicine'),
            'evidence_level' => 'A',
        ),
    ),
); 