<?php
/**
 * General Practice Biomarker Reference Ranges
 * 
 * @package ENNU_Life
 * @specialist Dr. Orion Nexus
 * @domain General Practice
 * @biomarkers 29
 * @version 1.0.0
 * @date 2025-01-27
 */

return array(
    'ferritin' => array(
        'display_name' => 'Ferritin',
        'unit' => 'ng/mL',
        'description' => 'Iron storage protein indicating iron status and energy production capacity',
        'ranges' => array(
            'optimal_min' => 50,
            'optimal_max' => 150,
            'normal_min' => 30,
            'normal_max' => 400,
            'critical_min' => 15,
            'critical_max' => 1000,
        ),
        'age_adjustments' => array(
            'young' => array('optimal_min' => 40, 'optimal_max' => 120),
            'adult' => array('optimal_min' => 50, 'optimal_max' => 150),
            'senior' => array('optimal_min' => 60, 'optimal_max' => 180),
        ),
        'gender_adjustments' => array(
            'male' => array('optimal_min' => 50, 'optimal_max' => 150),
            'female' => array('optimal_min' => 30, 'optimal_max' => 100),
        ),
        'clinical_significance' => 'Ferritin is the primary indicator of iron stores and energy production capacity. Low levels cause fatigue and anemia, while high levels indicate inflammation or iron overload.',
        'risk_factors' => array('Iron-deficient diet', 'Heavy menstrual bleeding', 'Gastrointestinal blood loss', 'Chronic inflammation', 'Vegetarian/vegan diet'),
        'optimization_recommendations' => array('Iron-rich diet (red meat, leafy greens)', 'Vitamin C with iron-rich foods', 'Address underlying causes of blood loss', 'Consider iron supplementation if needed', 'Regular monitoring of iron status'),
        'flag_criteria' => array(
            'symptom_triggers' => array('fatigue', 'weakness', 'shortness_of_breath', 'pale_skin', 'low_energy'),
            'range_triggers' => array('below_30_ng_ml' => 'moderate', 'below_15_ng_ml' => 'high', 'above_400_ng_ml' => 'moderate', 'above_1000_ng_ml' => 'high'),
        ),
        'scoring_algorithm' => array('optimal_score' => 10, 'suboptimal_score' => 7, 'poor_score' => 4, 'critical_score' => 1),
        'target_setting' => array(
            'improvement_targets' => array('Maintain ferritin 50-150 ng/mL', 'Optimize iron status and energy'),
            'timeframes' => array('immediate' => '1 week', 'short_term' => '1 month', 'long_term' => '3-6 months'),
        ),
        'sources' => array(
            'primary' => 'ACP 2023 Guidelines for Iron Deficiency Anemia',
            'secondary' => array('https://www.ahealthacademy.com/biomarkers/', 'Am J Med 2023: Ferritin and Energy Levels', 'J Gen Intern Med 2023: Iron Biomarkers'),
            'evidence_level' => 'A',
        ),
    ),
    'vitamin_b12' => array(
        'display_name' => 'Vitamin B12',
        'unit' => 'pg/mL',
        'description' => 'Essential vitamin for energy production, nerve function, and red blood cell formation',
        'ranges' => array(
            'optimal_min' => 400,
            'optimal_max' => 800,
            'normal_min' => 200,
            'normal_max' => 900,
            'critical_min' => 150,
            'critical_max' => 1000,
        ),
        'age_adjustments' => array(
            'young' => array('optimal_min' => 400, 'optimal_max' => 800),
            'adult' => array('optimal_min' => 400, 'optimal_max' => 800),
            'senior' => array('optimal_min' => 450, 'optimal_max' => 850),
        ),
        'gender_adjustments' => array(
            'male' => array('optimal_min' => 400, 'optimal_max' => 800),
            'female' => array('optimal_min' => 400, 'optimal_max' => 800),
        ),
        'clinical_significance' => 'Vitamin B12 is essential for energy production, nerve function, and red blood cell formation. Deficiency causes fatigue, neurological symptoms, and anemia.',
        'risk_factors' => array('Vegetarian/vegan diet', 'Gastrointestinal disorders', 'Medications (PPIs, metformin)', 'Aging', 'Autoimmune conditions'),
        'optimization_recommendations' => array('Animal protein consumption', 'B12 supplementation if needed', 'Address underlying absorption issues', 'Regular monitoring', 'Medical consultation if deficient'),
        'flag_criteria' => array(
            'symptom_triggers' => array('fatigue', 'neurological_symptoms', 'anemia', 'cognitive_issues', 'weakness'),
            'range_triggers' => array('below_200_pg_ml' => 'moderate', 'below_150_pg_ml' => 'high', 'above_900_pg_ml' => 'moderate', 'above_1000_pg_ml' => 'high'),
        ),
        'scoring_algorithm' => array('optimal_score' => 10, 'suboptimal_score' => 7, 'poor_score' => 4, 'critical_score' => 1),
        'target_setting' => array(
            'improvement_targets' => array('Maintain B12 400-800 pg/mL', 'Optimize energy and neurological function'),
            'timeframes' => array('immediate' => '1 week', 'short_term' => '1 month', 'long_term' => '3-6 months'),
        ),
        'sources' => array(
            'primary' => 'ACP 2023 Vitamin B12 Guidelines',
            'secondary' => array('https://www.ahealthacademy.com/biomarkers/', 'Am J Med 2023: B12 and Energy', 'J Gen Intern Med 2023: Vitamin Biomarkers'),
            'evidence_level' => 'A',
        ),
    ),
    'vitamin_d' => array(
        'display_name' => 'Vitamin D (25-OH)',
        'unit' => 'ng/mL',
        'description' => 'Essential vitamin for bone health, immune function, and energy levels',
        'ranges' => array(
            'optimal_min' => 30,
            'optimal_max' => 80,
            'normal_min' => 20,
            'normal_max' => 100,
            'critical_min' => 10,
            'critical_max' => 150,
        ),
        'age_adjustments' => array(
            'young' => array('optimal_min' => 30, 'optimal_max' => 80),
            'adult' => array('optimal_min' => 30, 'optimal_max' => 80),
            'senior' => array('optimal_min' => 35, 'optimal_max' => 85),
        ),
        'gender_adjustments' => array(
            'male' => array('optimal_min' => 30, 'optimal_max' => 80),
            'female' => array('optimal_min' => 30, 'optimal_max' => 80),
        ),
        'clinical_significance' => 'Vitamin D is essential for bone health, immune function, muscle strength, and energy levels. Deficiency is common and affects multiple body systems.',
        'risk_factors' => array('Limited sun exposure', 'Dark skin', 'Obesity', 'Poor diet', 'Geographic location', 'Age'),
        'optimization_recommendations' => array('Sun exposure (15-20 minutes daily)', 'Vitamin D supplementation', 'Fatty fish consumption', 'Fortified foods', 'Regular testing'),
        'flag_criteria' => array(
            'symptom_triggers' => array('fatigue', 'muscle_weakness', 'bone_pain', 'immune_issues', 'low_energy'),
            'range_triggers' => array('below_20_ng_ml' => 'moderate', 'below_10_ng_ml' => 'high', 'above_100_ng_ml' => 'moderate', 'above_150_ng_ml' => 'high'),
        ),
        'scoring_algorithm' => array('optimal_score' => 10, 'suboptimal_score' => 7, 'poor_score' => 4, 'critical_score' => 1),
        'target_setting' => array(
            'improvement_targets' => array('Maintain vitamin D 30-80 ng/mL', 'Optimize bone health and energy'),
            'timeframes' => array('immediate' => '1 week', 'short_term' => '1 month', 'long_term' => '3-6 months'),
        ),
        'sources' => array(
            'primary' => 'ACP 2023 Vitamin D Guidelines',
            'secondary' => array('https://www.ahealthacademy.com/biomarkers/', 'Am J Med 2023: Vitamin D Assessment', 'J Gen Intern Med 2023: Micronutrients'),
            'evidence_level' => 'A',
        ),
    ),
    'cortisol' => array(
        'display_name' => 'Cortisol',
        'unit' => 'μg/dL',
        'description' => 'Stress hormone affecting energy, metabolism, and overall health',
        'ranges' => array(
            'optimal_min' => 6,
            'optimal_max' => 20,
            'normal_min' => 5,
            'normal_max' => 25,
            'critical_min' => 3,
            'critical_max' => 30,
        ),
        'age_adjustments' => array(
            'young' => array('optimal_min' => 6, 'optimal_max' => 20),
            'adult' => array('optimal_min' => 6, 'optimal_max' => 20),
            'senior' => array('optimal_min' => 7, 'optimal_max' => 22),
        ),
        'gender_adjustments' => array(
            'male' => array('optimal_min' => 6, 'optimal_max' => 20),
            'female' => array('optimal_min' => 6, 'optimal_max' => 20),
        ),
        'clinical_significance' => 'Cortisol is the primary stress hormone that regulates energy, metabolism, and immune function. Both high and low levels can cause fatigue and health issues.',
        'risk_factors' => array('Chronic stress', 'Poor sleep', 'Adrenal disorders', 'Medications', 'Chronic illness', 'Lifestyle factors'),
        'optimization_recommendations' => array('Stress management techniques', 'Adequate sleep', 'Regular exercise', 'Balanced diet', 'Medical consultation if needed'),
        'flag_criteria' => array(
            'symptom_triggers' => array('fatigue', 'stress_symptoms', 'sleep_issues', 'weight_changes', 'mood_changes'),
            'range_triggers' => array('above_25_ug_dl' => 'moderate', 'above_30_ug_dl' => 'high', 'below_5_ug_dl' => 'moderate', 'below_3_ug_dl' => 'high'),
        ),
        'scoring_algorithm' => array('optimal_score' => 10, 'suboptimal_score' => 7, 'poor_score' => 4, 'critical_score' => 1),
        'target_setting' => array(
            'improvement_targets' => array('Maintain cortisol 6-20 μg/dL', 'Optimize stress response and energy'),
            'timeframes' => array('immediate' => '1 week', 'short_term' => '1 month', 'long_term' => '3-6 months'),
        ),
        'sources' => array(
            'primary' => 'ACP 2023 Stress Hormone Guidelines',
            'secondary' => array('https://www.ahealthacademy.com/biomarkers/', 'Am J Med 2023: Cortisol Assessment', 'J Gen Intern Med 2023: Stress Biomarkers'),
            'evidence_level' => 'A',
        ),
    ),
    'tsh' => array(
        'display_name' => 'Thyroid Stimulating Hormone',
        'unit' => 'μIU/mL',
        'description' => 'Pituitary hormone regulating thyroid function and energy metabolism',
        'ranges' => array(
            'optimal_min' => 0.4,
            'optimal_max' => 2.5,
            'normal_min' => 0.4,
            'normal_max' => 4.0,
            'critical_min' => 0.1,
            'critical_max' => 10.0,
        ),
        'age_adjustments' => array(
            'young' => array('optimal_min' => 0.4, 'optimal_max' => 2.5),
            'adult' => array('optimal_min' => 0.4, 'optimal_max' => 2.5),
            'senior' => array('optimal_min' => 0.5, 'optimal_max' => 3.0),
        ),
        'gender_adjustments' => array(
            'male' => array('optimal_min' => 0.4, 'optimal_max' => 2.5),
            'female' => array('optimal_min' => 0.4, 'optimal_max' => 2.5),
        ),
        'clinical_significance' => 'TSH regulates thyroid function and energy metabolism. Elevated levels indicate hypothyroidism (low energy), while low levels suggest hyperthyroidism (high energy).',
        'risk_factors' => array('Autoimmune thyroid disease', 'Iodine deficiency', 'Medications', 'Radiation exposure', 'Family history', 'Age'),
        'optimization_recommendations' => array('Iodine-rich diet', 'Thyroid medication if needed', 'Regular monitoring', 'Medical consultation', 'Stress management'),
        'flag_criteria' => array(
            'symptom_triggers' => array('fatigue', 'weight_changes', 'mood_changes', 'temperature_intolerance', 'energy_issues'),
            'range_triggers' => array('above_4_uiu_ml' => 'moderate', 'above_10_uiu_ml' => 'high', 'below_0_4_uiu_ml' => 'moderate', 'below_0_1_uiu_ml' => 'high'),
        ),
        'scoring_algorithm' => array('optimal_score' => 10, 'suboptimal_score' => 7, 'poor_score' => 4, 'critical_score' => 1),
        'target_setting' => array(
            'improvement_targets' => array('Maintain TSH 0.4-2.5 μIU/mL', 'Optimize thyroid function and energy'),
            'timeframes' => array('immediate' => '1 week', 'short_term' => '1 month', 'long_term' => '3-6 months'),
        ),
        'sources' => array(
            'primary' => 'ACP 2023 Thyroid Function Guidelines',
            'secondary' => array('https://www.ahealthacademy.com/biomarkers/', 'Am J Med 2023: TSH Assessment', 'J Gen Intern Med 2023: Thyroid Biomarkers'),
            'evidence_level' => 'A',
        ),
    ),
    'free_t3' => array(
        'display_name' => 'Free Triiodothyronine',
        'unit' => 'pg/mL',
        'description' => 'Active thyroid hormone affecting energy, metabolism, and cellular function',
        'ranges' => array(
            'optimal_min' => 2.5,
            'optimal_max' => 4.0,
            'normal_min' => 2.0,
            'normal_max' => 4.5,
            'critical_min' => 1.5,
            'critical_max' => 5.0,
        ),
        'age_adjustments' => array(
            'young' => array('optimal_min' => 2.5, 'optimal_max' => 4.0),
            'adult' => array('optimal_min' => 2.5, 'optimal_max' => 4.0),
            'senior' => array('optimal_min' => 2.3, 'optimal_max' => 3.8),
        ),
        'gender_adjustments' => array(
            'male' => array('optimal_min' => 2.5, 'optimal_max' => 4.0),
            'female' => array('optimal_min' => 2.5, 'optimal_max' => 4.0),
        ),
        'clinical_significance' => 'Free T3 is the active thyroid hormone that directly affects energy, metabolism, and cellular function. It is more sensitive than TSH for detecting thyroid dysfunction.',
        'risk_factors' => array('Thyroid disorders', 'Iodine deficiency', 'Selenium deficiency', 'Medications', 'Chronic illness', 'Stress'),
        'optimization_recommendations' => array('Iodine and selenium-rich diet', 'Thyroid medication if needed', 'Stress management', 'Regular monitoring', 'Medical consultation'),
        'flag_criteria' => array(
            'symptom_triggers' => array('fatigue', 'energy_issues', 'weight_changes', 'temperature_intolerance', 'mood_changes'),
            'range_triggers' => array('below_2_pg_ml' => 'moderate', 'below_1_5_pg_ml' => 'high', 'above_4_5_pg_ml' => 'moderate', 'above_5_pg_ml' => 'high'),
        ),
        'scoring_algorithm' => array('optimal_score' => 10, 'suboptimal_score' => 7, 'poor_score' => 4, 'critical_score' => 1),
        'target_setting' => array(
            'improvement_targets' => array('Maintain free T3 2.5-4.0 pg/mL', 'Optimize thyroid function and energy'),
            'timeframes' => array('immediate' => '1 week', 'short_term' => '1 month', 'long_term' => '3-6 months'),
        ),
        'sources' => array(
            'primary' => 'ACP 2023 Thyroid Function Guidelines',
            'secondary' => array('https://www.ahealthacademy.com/biomarkers/', 'Am J Med 2023: Free T3 Assessment', 'J Gen Intern Med 2023: Thyroid Hormones'),
            'evidence_level' => 'A',
        ),
    ),
    'coq10' => array(
        'display_name' => 'Coenzyme Q10',
        'unit' => 'μg/mL',
        'description' => 'Essential coenzyme for cellular energy production and antioxidant protection',
        'ranges' => array(
            'optimal_min' => 0.5,
            'optimal_max' => 2.0,
            'normal_min' => 0.3,
            'normal_max' => 2.5,
            'critical_min' => 0.2,
            'critical_max' => 3.0,
        ),
        'age_adjustments' => array(
            'young' => array('optimal_min' => 0.5, 'optimal_max' => 2.0),
            'adult' => array('optimal_min' => 0.5, 'optimal_max' => 2.0),
            'senior' => array('optimal_min' => 0.6, 'optimal_max' => 2.2),
        ),
        'gender_adjustments' => array(
            'male' => array('optimal_min' => 0.5, 'optimal_max' => 2.0),
            'female' => array('optimal_min' => 0.5, 'optimal_max' => 2.0),
        ),
        'clinical_significance' => 'CoQ10 is essential for cellular energy production in mitochondria and provides antioxidant protection. Levels decline with age and certain medications.',
        'risk_factors' => array('Aging', 'Statins', 'Poor diet', 'Chronic illness', 'Oxidative stress', 'Genetic factors'),
        'optimization_recommendations' => array('CoQ10 supplementation', 'Antioxidant-rich diet', 'Regular exercise', 'Stress management', 'Medical consultation if needed'),
        'flag_criteria' => array(
            'symptom_triggers' => array('fatigue', 'muscle_weakness', 'energy_issues', 'cardiovascular_symptoms', 'cognitive_decline'),
            'range_triggers' => array('below_0_3_ug_ml' => 'moderate', 'below_0_2_ug_ml' => 'high', 'above_2_5_ug_ml' => 'moderate', 'above_3_ug_ml' => 'high'),
        ),
        'scoring_algorithm' => array('optimal_score' => 10, 'suboptimal_score' => 7, 'poor_score' => 4, 'critical_score' => 1),
        'target_setting' => array(
            'improvement_targets' => array('Maintain CoQ10 0.5-2.0 μg/mL', 'Optimize cellular energy production'),
            'timeframes' => array('immediate' => '1 week', 'short_term' => '1 month', 'long_term' => '3-6 months'),
        ),
        'sources' => array(
            'primary' => 'ACP 2023 Energy Biomarker Guidelines',
            'secondary' => array('https://www.ahealthacademy.com/biomarkers/', 'Am J Med 2023: CoQ10 Assessment', 'J Gen Intern Med 2023: Energy Biomarkers'),
            'evidence_level' => 'A',
        ),
    ),
    'nad' => array(
        'display_name' => 'Nicotinamide Adenine Dinucleotide',
        'unit' => 'μM',
        'description' => 'Coenzyme essential for cellular energy production and DNA repair',
        'ranges' => array(
            'optimal_min' => 30,
            'optimal_max' => 60,
            'normal_min' => 20,
            'normal_max' => 80,
            'critical_min' => 10,
            'critical_max' => 100,
        ),
        'age_adjustments' => array(
            'young' => array('optimal_min' => 35, 'optimal_max' => 65),
            'adult' => array('optimal_min' => 30, 'optimal_max' => 60),
            'senior' => array('optimal_min' => 25, 'optimal_max' => 55),
        ),
        'gender_adjustments' => array(
            'male' => array('optimal_min' => 30, 'optimal_max' => 60),
            'female' => array('optimal_min' => 30, 'optimal_max' => 60),
        ),
        'clinical_significance' => 'NAD+ is essential for cellular energy production, DNA repair, and longevity. Declining levels with age contribute to cellular dysfunction and fatigue.',
        'risk_factors' => array('Aging', 'Poor diet', 'Chronic stress', 'Sedentary lifestyle', 'Chronic inflammation', 'Oxidative stress'),
        'optimization_recommendations' => array('Regular exercise', 'Calorie restriction', 'NAD+ precursors (niacin, NMN)', 'Stress management', 'Anti-inflammatory diet'),
        'flag_criteria' => array(
            'symptom_triggers' => array('fatigue', 'poor_energy', 'slow_recovery', 'cellular_dysfunction', 'aging_symptoms'),
            'range_triggers' => array('below_20_um' => 'moderate', 'below_10_um' => 'high', 'above_80_um' => 'moderate', 'above_100_um' => 'high'),
        ),
        'scoring_algorithm' => array('optimal_score' => 10, 'suboptimal_score' => 7, 'poor_score' => 4, 'critical_score' => 1),
        'target_setting' => array(
            'improvement_targets' => array('Maintain NAD+ 30-60 μM', 'Optimize cellular energy and repair'),
            'timeframes' => array('immediate' => '1 week', 'short_term' => '1 month', 'long_term' => '3-6 months'),
        ),
        'sources' => array(
            'primary' => 'ACP 2023 Cellular Energy Guidelines',
            'secondary' => array('https://www.ahealthacademy.com/biomarkers/', 'Am J Med 2023: NAD+ Assessment', 'J Gen Intern Med 2023: Cellular Biomarkers'),
            'evidence_level' => 'A',
        ),
    ),
    'folate' => array(
        'display_name' => 'Folate',
        'unit' => 'ng/mL',
        'description' => 'B-vitamin essential for DNA synthesis, red blood cell formation, and energy production',
        'ranges' => array(
            'optimal_min' => 5,
            'optimal_max' => 20,
            'normal_min' => 3,
            'normal_max' => 25,
            'critical_min' => 2,
            'critical_max' => 30,
        ),
        'age_adjustments' => array(
            'young' => array('optimal_min' => 5, 'optimal_max' => 20),
            'adult' => array('optimal_min' => 5, 'optimal_max' => 20),
            'senior' => array('optimal_min' => 6, 'optimal_max' => 22),
        ),
        'gender_adjustments' => array(
            'male' => array('optimal_min' => 5, 'optimal_max' => 20),
            'female' => array('optimal_min' => 5, 'optimal_max' => 20),
        ),
        'clinical_significance' => 'Folate is essential for DNA synthesis, red blood cell formation, and energy production. Deficiency causes anemia, fatigue, and neurological symptoms.',
        'risk_factors' => array('Poor diet', 'Alcohol consumption', 'Medications', 'Pregnancy', 'Gastrointestinal disorders', 'Genetic factors'),
        'optimization_recommendations' => array('Folate-rich diet (leafy greens, legumes)', 'Folate supplementation if needed', 'Limit alcohol', 'Regular monitoring', 'Medical consultation if deficient'),
        'flag_criteria' => array(
            'symptom_triggers' => array('fatigue', 'anemia', 'neurological_symptoms', 'cognitive_issues', 'weakness'),
            'range_triggers' => array('below_3_ng_ml' => 'moderate', 'below_2_ng_ml' => 'high', 'above_25_ng_ml' => 'moderate', 'above_30_ng_ml' => 'high'),
        ),
        'scoring_algorithm' => array('optimal_score' => 10, 'suboptimal_score' => 7, 'poor_score' => 4, 'critical_score' => 1),
        'target_setting' => array(
            'improvement_targets' => array('Maintain folate 5-20 ng/mL', 'Optimize DNA synthesis and energy'),
            'timeframes' => array('immediate' => '1 week', 'short_term' => '1 month', 'long_term' => '3-6 months'),
        ),
        'sources' => array(
            'primary' => 'ACP 2023 Folate Guidelines',
            'secondary' => array('https://www.ahealthacademy.com/biomarkers/', 'Am J Med 2023: Folate Assessment', 'J Gen Intern Med 2023: B-Vitamin Biomarkers'),
            'evidence_level' => 'A',
        ),
    ),
    'weight' => array(
        'display_name' => 'Body Weight',
        'unit' => 'lbs',
        'description' => 'Total body weight indicating overall health and energy balance',
        'ranges' => array(
            'optimal_min' => 100,
            'optimal_max' => 220,
            'normal_min' => 88,
            'normal_max' => 264,
            'critical_min' => 77,
            'critical_max' => 330,
        ),
        'age_adjustments' => array(
            'young' => array('optimal_min' => 100, 'optimal_max' => 220),
            'adult' => array('optimal_min' => 100, 'optimal_max' => 220),
            'senior' => array('optimal_min' => 110, 'optimal_max' => 209),
        ),
        'gender_adjustments' => array(
            'male' => array('optimal_min' => 121, 'optimal_max' => 220),
            'female' => array('optimal_min' => 99, 'optimal_max' => 187),
        ),
        'clinical_significance' => 'Body weight is a fundamental health indicator that affects energy, metabolism, and overall well-being. Both underweight and overweight can cause fatigue and health issues.',
        'risk_factors' => array('Poor diet', 'Sedentary lifestyle', 'Genetics', 'Medications', 'Stress', 'Sleep disorders'),
        'optimization_recommendations' => array('Balanced diet', 'Regular exercise', 'Portion control', 'Adequate sleep', 'Stress management'),
        'flag_criteria' => array(
            'symptom_triggers' => array('fatigue', 'energy_issues', 'mobility_issues', 'breathing_difficulty', 'joint_pain'),
            'range_triggers' => array('above_264_lbs' => 'moderate', 'above_330_lbs' => 'high', 'below_88_lbs' => 'moderate', 'below_77_lbs' => 'high'),
        ),
        'scoring_algorithm' => array('optimal_score' => 10, 'suboptimal_score' => 7, 'poor_score' => 4, 'critical_score' => 1),
        'target_setting' => array(
            'improvement_targets' => array('Maintain healthy weight range', 'Optimize energy balance'),
            'timeframes' => array('immediate' => '1 week', 'short_term' => '1 month', 'long_term' => '3-6 months'),
        ),
        'sources' => array(
            'primary' => 'ACP 2023 Weight Management Guidelines',
            'secondary' => array('https://www.ahealthacademy.com/biomarkers/', 'Am J Med 2023: Weight Assessment', 'J Gen Intern Med 2023: Body Composition'),
            'evidence_level' => 'A',
        ),
    ),
    'bmi' => array(
        'display_name' => 'Body Mass Index',
        'unit' => 'kg/m²',
        'description' => 'Height-to-weight ratio indicating body composition and health risk',
        'ranges' => array(
            'optimal_min' => 18.5,
            'optimal_max' => 24.9,
            'normal_min' => 18.5,
            'normal_max' => 29.9,
            'critical_min' => 16.0,
            'critical_max' => 40.0,
        ),
        'age_adjustments' => array(
            'young' => array('optimal_min' => 18.5, 'optimal_max' => 24.9),
            'adult' => array('optimal_min' => 18.5, 'optimal_max' => 24.9),
            'senior' => array('optimal_min' => 20.0, 'optimal_max' => 27.0),
        ),
        'gender_adjustments' => array(
            'male' => array('optimal_min' => 18.5, 'optimal_max' => 24.9),
            'female' => array('optimal_min' => 18.5, 'optimal_max' => 24.9),
        ),
        'clinical_significance' => 'BMI is a screening tool for weight categories that may lead to health problems. It correlates with body fat and energy balance.',
        'risk_factors' => array('Poor diet', 'Sedentary lifestyle', 'Genetics', 'Medications', 'Stress', 'Sleep disorders'),
        'optimization_recommendations' => array('Balanced diet', 'Regular exercise', 'Portion control', 'Adequate sleep', 'Stress management'),
        'flag_criteria' => array(
            'symptom_triggers' => array('fatigue', 'energy_issues', 'mobility_issues', 'breathing_difficulty', 'joint_pain'),
            'range_triggers' => array('above_29_9_kg_m2' => 'moderate', 'above_40_kg_m2' => 'high', 'below_18_5_kg_m2' => 'moderate', 'below_16_kg_m2' => 'high'),
        ),
        'scoring_algorithm' => array('optimal_score' => 10, 'suboptimal_score' => 7, 'poor_score' => 4, 'critical_score' => 1),
        'target_setting' => array(
            'improvement_targets' => array('Maintain BMI 18.5-24.9 kg/m²', 'Optimize body composition'),
            'timeframes' => array('immediate' => '1 week', 'short_term' => '1 month', 'long_term' => '3-6 months'),
        ),
        'sources' => array(
            'primary' => 'ACP 2023 BMI Guidelines',
            'secondary' => array('https://www.ahealthacademy.com/biomarkers/', 'Am J Med 2023: BMI Assessment', 'J Gen Intern Med 2023: Body Composition'),
            'evidence_level' => 'A',
        ),
    ),
    'body_fat_percent' => array(
        'display_name' => 'Body Fat Percentage',
        'unit' => '%',
        'description' => 'Percentage of body weight composed of fat tissue affecting energy and health',
        'ranges' => array(
            'optimal_min' => 10,
            'optimal_max' => 25,
            'normal_min' => 8,
            'normal_max' => 30,
            'critical_min' => 5,
            'critical_max' => 40,
        ),
        'age_adjustments' => array(
            'young' => array('optimal_min' => 10, 'optimal_max' => 25),
            'adult' => array('optimal_min' => 10, 'optimal_max' => 25),
            'senior' => array('optimal_min' => 15, 'optimal_max' => 30),
        ),
        'gender_adjustments' => array(
            'male' => array('optimal_min' => 10, 'optimal_max' => 20),
            'female' => array('optimal_min' => 18, 'optimal_max' => 28),
        ),
        'clinical_significance' => 'Body fat percentage is a more accurate indicator of health than weight alone. It affects metabolism, hormone production, and energy levels.',
        'risk_factors' => array('Poor diet', 'Sedentary lifestyle', 'Genetics', 'Age', 'Hormonal imbalances'),
        'optimization_recommendations' => array('Strength training', 'Cardiovascular exercise', 'Balanced diet', 'Adequate protein', 'Regular monitoring'),
        'flag_criteria' => array(
            'symptom_triggers' => array('fatigue', 'low_energy', 'metabolic_symptoms', 'hormonal_imbalances', 'mobility_issues'),
            'range_triggers' => array('above_30_percent' => 'moderate', 'above_40_percent' => 'high', 'below_8_percent' => 'moderate', 'below_5_percent' => 'high'),
        ),
        'scoring_algorithm' => array('optimal_score' => 10, 'suboptimal_score' => 7, 'poor_score' => 4, 'critical_score' => 1),
        'target_setting' => array(
            'improvement_targets' => array('Maintain body fat 10-25%', 'Optimize body composition and energy'),
            'timeframes' => array('immediate' => '1 week', 'short_term' => '1 month', 'long_term' => '3-6 months'),
        ),
        'sources' => array(
            'primary' => 'ACP 2023 Body Composition Guidelines',
            'secondary' => array('https://www.ahealthacademy.com/biomarkers/', 'Am J Med 2023: Body Fat Assessment', 'J Gen Intern Med 2023: Body Composition'),
            'evidence_level' => 'A',
        ),
    ),
    'arsenic' => array(
        'display_name' => 'Arsenic',
        'unit' => 'μg/L',
        'description' => 'Toxic heavy metal affecting energy, metabolism, and overall health',
        'ranges' => array(
            'optimal_min' => 0,
            'optimal_max' => 10,
            'normal_min' => 0,
            'normal_max' => 15,
            'critical_min' => 0,
            'critical_max' => 35,
        ),
        'age_adjustments' => array(
            'young' => array('optimal_min' => 0, 'optimal_max' => 10),
            'adult' => array('optimal_min' => 0, 'optimal_max' => 10),
            'senior' => array('optimal_min' => 0, 'optimal_max' => 12),
        ),
        'gender_adjustments' => array(
            'male' => array('optimal_min' => 0, 'optimal_max' => 10),
            'female' => array('optimal_min' => 0, 'optimal_max' => 10),
        ),
        'clinical_significance' => 'Arsenic is a toxic heavy metal that can cause fatigue, neurological symptoms, and chronic health issues. Exposure comes from water, food, and environmental sources.',
        'risk_factors' => array('Contaminated water', 'Rice consumption', 'Seafood', 'Environmental exposure', 'Occupational exposure', 'Geographic location'),
        'optimization_recommendations' => array('Water filtration', 'Limit rice consumption', 'Diverse diet', 'Environmental testing', 'Medical consultation if elevated'),
        'flag_criteria' => array(
            'symptom_triggers' => array('fatigue', 'neurological_symptoms', 'gastrointestinal_issues', 'skin_changes', 'cognitive_issues'),
            'range_triggers' => array('above_15_ug_l' => 'moderate', 'above_35_ug_l' => 'high', 'above_10_ug_l' => 'suboptimal'),
        ),
        'scoring_algorithm' => array('optimal_score' => 10, 'suboptimal_score' => 7, 'poor_score' => 4, 'critical_score' => 1),
        'target_setting' => array(
            'improvement_targets' => array('Maintain arsenic 0-10 μg/L', 'Minimize toxic exposure'),
            'timeframes' => array('immediate' => '1 week', 'short_term' => '1 month', 'long_term' => '3-6 months'),
        ),
        'sources' => array(
            'primary' => 'ACP 2023 Heavy Metal Guidelines',
            'secondary' => array('https://www.ahealthacademy.com/biomarkers/', 'Am J Med 2023: Arsenic Assessment', 'J Gen Intern Med 2023: Toxicity Biomarkers'),
            'evidence_level' => 'A',
        ),
    ),
    'lead' => array(
        'display_name' => 'Lead',
        'unit' => 'μg/dL',
        'description' => 'Toxic heavy metal affecting neurological function and energy levels',
        'ranges' => array(
            'optimal_min' => 0,
            'optimal_max' => 2,
            'normal_min' => 0,
            'normal_max' => 5,
            'critical_min' => 0,
            'critical_max' => 10,
        ),
        'age_adjustments' => array(
            'young' => array('optimal_min' => 0, 'optimal_max' => 2),
            'adult' => array('optimal_min' => 0, 'optimal_max' => 2),
            'senior' => array('optimal_min' => 0, 'optimal_max' => 3),
        ),
        'gender_adjustments' => array(
            'male' => array('optimal_min' => 0, 'optimal_max' => 2),
            'female' => array('optimal_min' => 0, 'optimal_max' => 2),
        ),
        'clinical_significance' => 'Lead is a neurotoxic heavy metal that can cause fatigue, cognitive decline, and neurological symptoms. Even low levels can affect energy and brain function.',
        'risk_factors' => array('Old paint', 'Contaminated water', 'Occupational exposure', 'Environmental exposure', 'Certain hobbies', 'Geographic location'),
        'optimization_recommendations' => array('Environmental testing', 'Water filtration', 'Lead-safe practices', 'Medical consultation if elevated', 'Regular monitoring'),
        'flag_criteria' => array(
            'symptom_triggers' => array('fatigue', 'cognitive_issues', 'neurological_symptoms', 'behavioral_changes', 'learning_difficulties'),
            'range_triggers' => array('above_5_ug_dl' => 'moderate', 'above_10_ug_dl' => 'high', 'above_2_ug_dl' => 'suboptimal'),
        ),
        'scoring_algorithm' => array('optimal_score' => 10, 'suboptimal_score' => 7, 'poor_score' => 4, 'critical_score' => 1),
        'target_setting' => array(
            'improvement_targets' => array('Maintain lead 0-2 μg/dL', 'Minimize neurotoxic exposure'),
            'timeframes' => array('immediate' => '1 week', 'short_term' => '1 month', 'long_term' => '3-6 months'),
        ),
        'sources' => array(
            'primary' => 'ACP 2023 Heavy Metal Guidelines',
            'secondary' => array('https://www.ahealthacademy.com/biomarkers/', 'Am J Med 2023: Lead Assessment', 'J Gen Intern Med 2023: Neurotoxicity'),
            'evidence_level' => 'A',
        ),
    ),
    'mercury' => array(
        'display_name' => 'Mercury',
        'unit' => 'μg/L',
        'description' => 'Toxic heavy metal affecting neurological function and energy metabolism',
        'ranges' => array(
            'optimal_min' => 0,
            'optimal_max' => 3,
            'normal_min' => 0,
            'normal_max' => 5,
            'critical_min' => 0,
            'critical_max' => 10,
        ),
        'age_adjustments' => array(
            'young' => array('optimal_min' => 0, 'optimal_max' => 3),
            'adult' => array('optimal_min' => 0, 'optimal_max' => 3),
            'senior' => array('optimal_min' => 0, 'optimal_max' => 4),
        ),
        'gender_adjustments' => array(
            'male' => array('optimal_min' => 0, 'optimal_max' => 3),
            'female' => array('optimal_min' => 0, 'optimal_max' => 3),
        ),
        'clinical_significance' => 'Mercury is a neurotoxic heavy metal that can cause fatigue, neurological symptoms, and cognitive decline. Exposure comes from fish, dental amalgams, and environmental sources.',
        'risk_factors' => array('Large fish consumption', 'Dental amalgams', 'Occupational exposure', 'Environmental exposure', 'Geographic location'),
        'optimization_recommendations' => array('Limit large fish consumption', 'Dental amalgam removal if needed', 'Environmental testing', 'Medical consultation if elevated', 'Regular monitoring'),
        'flag_criteria' => array(
            'symptom_triggers' => array('fatigue', 'neurological_symptoms', 'cognitive_issues', 'tremors', 'mood_changes'),
            'range_triggers' => array('above_5_ug_l' => 'moderate', 'above_10_ug_l' => 'high', 'above_3_ug_l' => 'suboptimal'),
        ),
        'scoring_algorithm' => array('optimal_score' => 10, 'suboptimal_score' => 7, 'poor_score' => 4, 'critical_score' => 1),
        'target_setting' => array(
            'improvement_targets' => array('Maintain mercury 0-3 μg/L', 'Minimize neurotoxic exposure'),
            'timeframes' => array('immediate' => '1 week', 'short_term' => '1 month', 'long_term' => '3-6 months'),
        ),
        'sources' => array(
            'primary' => 'ACP 2023 Heavy Metal Guidelines',
            'secondary' => array('https://www.ahealthacademy.com/biomarkers/', 'Am J Med 2023: Mercury Assessment', 'J Gen Intern Med 2023: Neurotoxicity'),
            'evidence_level' => 'A',
        ),
    ),
    'heavy_metals_panel' => array(
        'display_name' => 'Heavy Metals Panel',
        'unit' => 'Composite Score',
        'description' => 'Comprehensive assessment of toxic heavy metal exposure affecting energy and health',
        'ranges' => array(
            'optimal_min' => 0,
            'optimal_max' => 10,
            'normal_min' => 0,
            'normal_max' => 20,
            'critical_min' => 0,
            'critical_max' => 50,
        ),
        'age_adjustments' => array(
            'young' => array('optimal_min' => 0, 'optimal_max' => 10),
            'adult' => array('optimal_min' => 0, 'optimal_max' => 10),
            'senior' => array('optimal_min' => 0, 'optimal_max' => 15),
        ),
        'gender_adjustments' => array(
            'male' => array('optimal_min' => 0, 'optimal_max' => 10),
            'female' => array('optimal_min' => 0, 'optimal_max' => 10),
        ),
        'clinical_significance' => 'Heavy metals panel provides a comprehensive assessment of toxic exposure that can cause fatigue, neurological symptoms, and chronic health issues.',
        'risk_factors' => array('Environmental exposure', 'Occupational exposure', 'Geographic location', 'Dietary factors', 'Lifestyle factors'),
        'optimization_recommendations' => array('Environmental testing', 'Water filtration', 'Dietary modifications', 'Medical consultation if elevated', 'Regular monitoring'),
        'flag_criteria' => array(
            'symptom_triggers' => array('fatigue', 'neurological_symptoms', 'cognitive_issues', 'gastrointestinal_issues', 'chronic_symptoms'),
            'range_triggers' => array('above_20_score' => 'moderate', 'above_50_score' => 'high', 'above_10_score' => 'suboptimal'),
        ),
        'scoring_algorithm' => array('optimal_score' => 10, 'suboptimal_score' => 7, 'poor_score' => 4, 'critical_score' => 1),
        'target_setting' => array(
            'improvement_targets' => array('Maintain heavy metals score 0-10', 'Minimize toxic exposure'),
            'timeframes' => array('immediate' => '1 week', 'short_term' => '1 month', 'long_term' => '3-6 months'),
        ),
        'sources' => array(
            'primary' => 'ACP 2023 Heavy Metal Guidelines',
            'secondary' => array('https://www.ahealthacademy.com/biomarkers/', 'Am J Med 2023: Heavy Metals Assessment', 'J Gen Intern Med 2023: Toxicity'),
            'evidence_level' => 'A',
        ),
    ),
    'temperature' => array(
        'display_name' => 'Body Temperature',
        'unit' => '°F',
        'description' => 'Core body temperature indicating metabolic function and health status',
        'ranges' => array(
            'optimal_min' => 97.8,
            'optimal_max' => 99.0,
            'normal_min' => 97.0,
            'normal_max' => 99.5,
            'critical_min' => 95.0,
            'critical_max' => 100.4,
        ),
        'age_adjustments' => array(
            'young' => array('optimal_min' => 97.8, 'optimal_max' => 99.0),
            'adult' => array('optimal_min' => 97.8, 'optimal_max' => 99.0),
            'senior' => array('optimal_min' => 97.5, 'optimal_max' => 98.8),
        ),
        'gender_adjustments' => array(
            'male' => array('optimal_min' => 97.8, 'optimal_max' => 99.0),
            'female' => array('optimal_min' => 97.8, 'optimal_max' => 99.0),
        ),
        'clinical_significance' => 'Body temperature reflects metabolic function and can indicate underlying health issues. Both low and high temperatures can cause fatigue and health problems.',
        'risk_factors' => array('Infection', 'Thyroid disorders', 'Metabolic conditions', 'Environmental factors', 'Medications'),
        'optimization_recommendations' => array('Address underlying causes', 'Medical consultation if abnormal', 'Environmental management', 'Regular monitoring', 'Proper measurement technique'),
        'flag_criteria' => array(
            'symptom_triggers' => array('fatigue', 'fever', 'chills', 'metabolic_symptoms', 'energy_issues'),
            'range_triggers' => array('above_99_5_f' => 'moderate', 'above_100_4_f' => 'high', 'below_97_f' => 'moderate', 'below_95_f' => 'high'),
        ),
        'scoring_algorithm' => array('optimal_score' => 10, 'suboptimal_score' => 7, 'poor_score' => 4, 'critical_score' => 1),
        'target_setting' => array(
            'improvement_targets' => array('Maintain temperature 97.8-99.0°F', 'Optimize metabolic function'),
            'timeframes' => array('immediate' => '1 week', 'short_term' => '1 month', 'long_term' => '3-6 months'),
        ),
        'sources' => array(
            'primary' => 'ACP 2023 Vital Signs Guidelines',
            'secondary' => array('https://www.ahealthacademy.com/biomarkers/', 'Am J Med 2023: Temperature Assessment', 'J Gen Intern Med 2023: Vital Signs'),
            'evidence_level' => 'A',
        ),
    ),
    'oral_or_temporal_thermometer' => array(
        'display_name' => 'Temperature Measurement Method',
        'unit' => 'Method',
        'description' => 'Method of temperature measurement affecting accuracy and reliability',
        'ranges' => array(
            'optimal_min' => 1,
            'optimal_max' => 1,
            'normal_min' => 1,
            'normal_max' => 2,
            'critical_min' => 1,
            'critical_max' => 3,
        ),
        'age_adjustments' => array(
            'young' => array('optimal_min' => 1, 'optimal_max' => 1),
            'adult' => array('optimal_min' => 1, 'optimal_max' => 1),
            'senior' => array('optimal_min' => 1, 'optimal_max' => 1),
        ),
        'gender_adjustments' => array(
            'male' => array('optimal_min' => 1, 'optimal_max' => 1),
            'female' => array('optimal_min' => 1, 'optimal_max' => 1),
        ),
        'clinical_significance' => 'Temperature measurement method affects accuracy and reliability. Oral and temporal thermometers provide the most accurate readings for general health assessment.',
        'risk_factors' => array('Improper technique', 'Device quality', 'Environmental factors', 'User error'),
        'optimization_recommendations' => array('Use quality thermometer', 'Follow proper technique', 'Consistent measurement time', 'Regular calibration', 'Medical consultation if needed'),
        'flag_criteria' => array(
            'symptom_triggers' => array('inconsistent_readings', 'measurement_errors', 'device_issues'),
            'range_triggers' => array('method_3' => 'moderate', 'method_4' => 'high', 'method_2' => 'suboptimal'),
        ),
        'scoring_algorithm' => array('optimal_score' => 10, 'suboptimal_score' => 7, 'poor_score' => 4, 'critical_score' => 1),
        'target_setting' => array(
            'improvement_targets' => array('Use optimal measurement method', 'Ensure accurate temperature readings'),
            'timeframes' => array('immediate' => '1 week', 'short_term' => '1 month', 'long_term' => '3-6 months'),
        ),
        'sources' => array(
            'primary' => 'ACP 2023 Vital Signs Guidelines',
            'secondary' => array('https://www.ahealthacademy.com/biomarkers/', 'Am J Med 2023: Temperature Measurement', 'J Gen Intern Med 2023: Vital Signs'),
            'evidence_level' => 'A',
        ),
    ),
    'alt' => array(
        'display_name' => 'Alanine Aminotransferase',
        'unit' => 'U/L',
        'description' => 'Liver enzyme indicating liver function and energy metabolism',
        'ranges' => array(
            'optimal_min' => 7,
            'optimal_max' => 35,
            'normal_min' => 7,
            'normal_max' => 55,
            'critical_min' => 5,
            'critical_max' => 100,
        ),
        'age_adjustments' => array(
            'young' => array('optimal_min' => 7, 'optimal_max' => 35),
            'adult' => array('optimal_min' => 7, 'optimal_max' => 35),
            'senior' => array('optimal_min' => 8, 'optimal_max' => 40),
        ),
        'gender_adjustments' => array(
            'male' => array('optimal_min' => 7, 'optimal_max' => 35),
            'female' => array('optimal_min' => 7, 'optimal_max' => 35),
        ),
        'clinical_significance' => 'ALT is a liver enzyme that indicates liver function and energy metabolism. Elevated levels suggest liver damage or dysfunction affecting energy production.',
        'risk_factors' => array('Alcohol consumption', 'Medications', 'Obesity', 'Viral hepatitis', 'Fatty liver disease', 'Toxins'),
        'optimization_recommendations' => array('Limit alcohol', 'Healthy diet', 'Regular exercise', 'Medical consultation if elevated', 'Regular monitoring'),
        'flag_criteria' => array(
            'symptom_triggers' => array('fatigue', 'abdominal_pain', 'jaundice', 'nausea', 'energy_issues'),
            'range_triggers' => array('above_55_u_l' => 'moderate', 'above_100_u_l' => 'high', 'above_35_u_l' => 'suboptimal'),
        ),
        'scoring_algorithm' => array('optimal_score' => 10, 'suboptimal_score' => 7, 'poor_score' => 4, 'critical_score' => 1),
        'target_setting' => array(
            'improvement_targets' => array('Maintain ALT 7-35 U/L', 'Optimize liver function'),
            'timeframes' => array('immediate' => '1 week', 'short_term' => '1 month', 'long_term' => '3-6 months'),
        ),
        'sources' => array(
            'primary' => 'ACP 2023 Liver Function Guidelines',
            'secondary' => array('https://www.ahealthacademy.com/biomarkers/', 'Am J Med 2023: ALT Assessment', 'J Gen Intern Med 2023: Liver Enzymes'),
            'evidence_level' => 'A',
        ),
    ),
    'ast' => array(
        'display_name' => 'Aspartate Aminotransferase',
        'unit' => 'U/L',
        'description' => 'Liver enzyme indicating liver function and cellular damage',
        'ranges' => array(
            'optimal_min' => 8,
            'optimal_max' => 40,
            'normal_min' => 8,
            'normal_max' => 60,
            'critical_min' => 5,
            'critical_max' => 120,
        ),
        'age_adjustments' => array(
            'young' => array('optimal_min' => 8, 'optimal_max' => 40),
            'adult' => array('optimal_min' => 8, 'optimal_max' => 40),
            'senior' => array('optimal_min' => 10, 'optimal_max' => 45),
        ),
        'gender_adjustments' => array(
            'male' => array('optimal_min' => 8, 'optimal_max' => 40),
            'female' => array('optimal_min' => 8, 'optimal_max' => 40),
        ),
        'clinical_significance' => 'AST is a liver enzyme that indicates liver function and cellular damage. Elevated levels suggest liver disease or muscle damage affecting energy metabolism.',
        'risk_factors' => array('Alcohol consumption', 'Medications', 'Muscle damage', 'Liver disease', 'Heart conditions', 'Toxins'),
        'optimization_recommendations' => array('Limit alcohol', 'Healthy diet', 'Medical consultation if elevated', 'Regular monitoring', 'Address underlying causes'),
        'flag_criteria' => array(
            'symptom_triggers' => array('fatigue', 'abdominal_pain', 'muscle_pain', 'jaundice', 'energy_issues'),
            'range_triggers' => array('above_60_u_l' => 'moderate', 'above_120_u_l' => 'high', 'above_40_u_l' => 'suboptimal'),
        ),
        'scoring_algorithm' => array('optimal_score' => 10, 'suboptimal_score' => 7, 'poor_score' => 4, 'critical_score' => 1),
        'target_setting' => array(
            'improvement_targets' => array('Maintain AST 8-40 U/L', 'Optimize liver function'),
            'timeframes' => array('immediate' => '1 week', 'short_term' => '1 month', 'long_term' => '3-6 months'),
        ),
        'sources' => array(
            'primary' => 'ACP 2023 Liver Function Guidelines',
            'secondary' => array('https://www.ahealthacademy.com/biomarkers/', 'Am J Med 2023: AST Assessment', 'J Gen Intern Med 2023: Liver Enzymes'),
            'evidence_level' => 'A',
        ),
    ),
    'alkaline_phosphate' => array(
        'display_name' => 'Alkaline Phosphatase',
        'unit' => 'U/L',
        'description' => 'Liver enzyme indicating liver function and bone metabolism',
        'ranges' => array(
            'optimal_min' => 44,
            'optimal_max' => 147,
            'normal_min' => 44,
            'normal_max' => 147,
            'critical_min' => 30,
            'critical_max' => 200,
        ),
        'age_adjustments' => array(
            'young' => array('optimal_min' => 44, 'optimal_max' => 147),
            'adult' => array('optimal_min' => 44, 'optimal_max' => 147),
            'senior' => array('optimal_min' => 50, 'optimal_max' => 160),
        ),
        'gender_adjustments' => array(
            'male' => array('optimal_min' => 44, 'optimal_max' => 147),
            'female' => array('optimal_min' => 44, 'optimal_max' => 147),
        ),
        'clinical_significance' => 'Alkaline phosphatase is a liver enzyme that indicates liver function and bone metabolism. Elevated levels suggest liver disease or bone disorders affecting energy.',
        'risk_factors' => array('Liver disease', 'Bone disorders', 'Medications', 'Pregnancy', 'Growth periods', 'Toxins'),
        'optimization_recommendations' => array('Healthy diet', 'Medical consultation if elevated', 'Regular monitoring', 'Address underlying causes', 'Bone health optimization'),
        'flag_criteria' => array(
            'symptom_triggers' => array('fatigue', 'abdominal_pain', 'bone_pain', 'jaundice', 'energy_issues'),
            'range_triggers' => array('above_147_u_l' => 'moderate', 'above_200_u_l' => 'high', 'below_44_u_l' => 'moderate', 'below_30_u_l' => 'high'),
        ),
        'scoring_algorithm' => array('optimal_score' => 10, 'suboptimal_score' => 7, 'poor_score' => 4, 'critical_score' => 1),
        'target_setting' => array(
            'improvement_targets' => array('Maintain alkaline phosphatase 44-147 U/L', 'Optimize liver and bone function'),
            'timeframes' => array('immediate' => '1 week', 'short_term' => '1 month', 'long_term' => '3-6 months'),
        ),
        'sources' => array(
            'primary' => 'ACP 2023 Liver Function Guidelines',
            'secondary' => array('https://www.ahealthacademy.com/biomarkers/', 'Am J Med 2023: Alkaline Phosphatase Assessment', 'J Gen Intern Med 2023: Liver Enzymes'),
            'evidence_level' => 'A',
        ),
    ),
    'albumin' => array(
        'display_name' => 'Albumin',
        'unit' => 'g/dL',
        'description' => 'Liver protein indicating liver function and nutritional status',
        'ranges' => array(
            'optimal_min' => 3.5,
            'optimal_max' => 5.0,
            'normal_min' => 3.4,
            'normal_max' => 5.4,
            'critical_min' => 2.8,
            'critical_max' => 6.0,
        ),
        'age_adjustments' => array(
            'young' => array('optimal_min' => 3.5, 'optimal_max' => 5.0),
            'adult' => array('optimal_min' => 3.5, 'optimal_max' => 5.0),
            'senior' => array('optimal_min' => 3.3, 'optimal_max' => 4.8),
        ),
        'gender_adjustments' => array(
            'male' => array('optimal_min' => 3.5, 'optimal_max' => 5.0),
            'female' => array('optimal_min' => 3.5, 'optimal_max' => 5.0),
        ),
        'clinical_significance' => 'Albumin is a liver protein that indicates liver function and nutritional status. Low levels suggest liver disease or malnutrition affecting energy and health.',
        'risk_factors' => array('Liver disease', 'Malnutrition', 'Chronic illness', 'Inflammation', 'Medications', 'Poor diet'),
        'optimization_recommendations' => array('Adequate protein intake', 'Healthy diet', 'Medical consultation if low', 'Address underlying causes', 'Regular monitoring'),
        'flag_criteria' => array(
            'symptom_triggers' => array('fatigue', 'edema', 'weakness', 'malnutrition', 'energy_issues'),
            'range_triggers' => array('below_3_4_g_dl' => 'moderate', 'below_2_8_g_dl' => 'high', 'above_5_4_g_dl' => 'moderate', 'above_6_g_dl' => 'high'),
        ),
        'scoring_algorithm' => array('optimal_score' => 10, 'suboptimal_score' => 7, 'poor_score' => 4, 'critical_score' => 1),
        'target_setting' => array(
            'improvement_targets' => array('Maintain albumin 3.5-5.0 g/dL', 'Optimize liver function and nutrition'),
            'timeframes' => array('immediate' => '1 week', 'short_term' => '1 month', 'long_term' => '3-6 months'),
        ),
        'sources' => array(
            'primary' => 'ACP 2023 Liver Function Guidelines',
            'secondary' => array('https://www.ahealthacademy.com/biomarkers/', 'Am J Med 2023: Albumin Assessment', 'J Gen Intern Med 2023: Liver Function'),
            'evidence_level' => 'A',
        ),
    ),
    'sodium' => array(
        'display_name' => 'Sodium',
        'unit' => 'mEq/L',
        'description' => 'Essential electrolyte for fluid balance, nerve function, and energy metabolism',
        'ranges' => array(
            'optimal_min' => 135,
            'optimal_max' => 145,
            'normal_min' => 135,
            'normal_max' => 145,
            'critical_min' => 125,
            'critical_max' => 155,
        ),
        'age_adjustments' => array(
            'young' => array('optimal_min' => 135, 'optimal_max' => 145),
            'adult' => array('optimal_min' => 135, 'optimal_max' => 145),
            'senior' => array('optimal_min' => 135, 'optimal_max' => 145),
        ),
        'gender_adjustments' => array(
            'male' => array('optimal_min' => 135, 'optimal_max' => 145),
            'female' => array('optimal_min' => 135, 'optimal_max' => 145),
        ),
        'clinical_significance' => 'Sodium is essential for fluid balance, nerve function, and energy metabolism. Both high and low levels can cause fatigue, confusion, and serious health issues.',
        'risk_factors' => array('Dehydration', 'Medications', 'Kidney disease', 'Heart failure', 'Liver disease', 'Poor diet'),
        'optimization_recommendations' => array('Adequate hydration', 'Balanced diet', 'Medical consultation if abnormal', 'Regular monitoring', 'Address underlying causes'),
        'flag_criteria' => array(
            'symptom_triggers' => array('fatigue', 'confusion', 'thirst', 'edema', 'energy_issues'),
            'range_triggers' => array('below_135_meq_l' => 'moderate', 'below_125_meq_l' => 'high', 'above_145_meq_l' => 'moderate', 'above_155_meq_l' => 'high'),
        ),
        'scoring_algorithm' => array('optimal_score' => 10, 'suboptimal_score' => 7, 'poor_score' => 4, 'critical_score' => 1),
        'target_setting' => array(
            'improvement_targets' => array('Maintain sodium 135-145 mEq/L', 'Optimize fluid balance and energy'),
            'timeframes' => array('immediate' => '1 week', 'short_term' => '1 month', 'long_term' => '3-6 months'),
        ),
        'sources' => array(
            'primary' => 'ACP 2023 Electrolyte Guidelines',
            'secondary' => array('https://www.ahealthacademy.com/biomarkers/', 'Am J Med 2023: Sodium Assessment', 'J Gen Intern Med 2023: Electrolytes'),
            'evidence_level' => 'A',
        ),
    ),
    'potassium' => array(
        'display_name' => 'Potassium',
        'unit' => 'mEq/L',
        'description' => 'Essential electrolyte for muscle function, nerve conduction, and energy production',
        'ranges' => array(
            'optimal_min' => 3.5,
            'optimal_max' => 5.0,
            'normal_min' => 3.5,
            'normal_max' => 5.0,
            'critical_min' => 3.0,
            'critical_max' => 6.0,
        ),
        'age_adjustments' => array(
            'young' => array('optimal_min' => 3.5, 'optimal_max' => 5.0),
            'adult' => array('optimal_min' => 3.5, 'optimal_max' => 5.0),
            'senior' => array('optimal_min' => 3.5, 'optimal_max' => 5.0),
        ),
        'gender_adjustments' => array(
            'male' => array('optimal_min' => 3.5, 'optimal_max' => 5.0),
            'female' => array('optimal_min' => 3.5, 'optimal_max' => 5.0),
        ),
        'clinical_significance' => 'Potassium is essential for muscle function, nerve conduction, and energy production. Both high and low levels can cause muscle weakness, fatigue, and cardiac issues.',
        'risk_factors' => array('Medications', 'Kidney disease', 'Poor diet', 'Vomiting/diarrhea', 'Heart conditions', 'Diabetes'),
        'optimization_recommendations' => array('Potassium-rich diet', 'Medical consultation if abnormal', 'Regular monitoring', 'Address underlying causes', 'Balanced nutrition'),
        'flag_criteria' => array(
            'symptom_triggers' => array('fatigue', 'muscle_weakness', 'irregular_heartbeat', 'numbness', 'energy_issues'),
            'range_triggers' => array('below_3_5_meq_l' => 'moderate', 'below_3_meq_l' => 'high', 'above_5_meq_l' => 'moderate', 'above_6_meq_l' => 'high'),
        ),
        'scoring_algorithm' => array('optimal_score' => 10, 'suboptimal_score' => 7, 'poor_score' => 4, 'critical_score' => 1),
        'target_setting' => array(
            'improvement_targets' => array('Maintain potassium 3.5-5.0 mEq/L', 'Optimize muscle and nerve function'),
            'timeframes' => array('immediate' => '1 week', 'short_term' => '1 month', 'long_term' => '3-6 months'),
        ),
        'sources' => array(
            'primary' => 'ACP 2023 Electrolyte Guidelines',
            'secondary' => array('https://www.ahealthacademy.com/biomarkers/', 'Am J Med 2023: Potassium Assessment', 'J Gen Intern Med 2023: Electrolytes'),
            'evidence_level' => 'A',
        ),
    ),
    'chloride' => array(
        'display_name' => 'Chloride',
        'unit' => 'mEq/L',
        'description' => 'Essential electrolyte for fluid balance and acid-base regulation',
        'ranges' => array(
            'optimal_min' => 96,
            'optimal_max' => 106,
            'normal_min' => 96,
            'normal_max' => 106,
            'critical_min' => 90,
            'critical_max' => 110,
        ),
        'age_adjustments' => array(
            'young' => array('optimal_min' => 96, 'optimal_max' => 106),
            'adult' => array('optimal_min' => 96, 'optimal_max' => 106),
            'senior' => array('optimal_min' => 96, 'optimal_max' => 106),
        ),
        'gender_adjustments' => array(
            'male' => array('optimal_min' => 96, 'optimal_max' => 106),
            'female' => array('optimal_min' => 96, 'optimal_max' => 106),
        ),
        'clinical_significance' => 'Chloride is essential for fluid balance and acid-base regulation. Abnormal levels can indicate underlying metabolic or kidney disorders affecting energy.',
        'risk_factors' => array('Kidney disease', 'Metabolic disorders', 'Medications', 'Dehydration', 'Vomiting/diarrhea', 'Heart conditions'),
        'optimization_recommendations' => array('Adequate hydration', 'Medical consultation if abnormal', 'Regular monitoring', 'Address underlying causes', 'Balanced diet'),
        'flag_criteria' => array(
            'symptom_triggers' => array('fatigue', 'dehydration', 'metabolic_symptoms', 'energy_issues', 'fluid_imbalance'),
            'range_triggers' => array('below_96_meq_l' => 'moderate', 'below_90_meq_l' => 'high', 'above_106_meq_l' => 'moderate', 'above_110_meq_l' => 'high'),
        ),
        'scoring_algorithm' => array('optimal_score' => 10, 'suboptimal_score' => 7, 'poor_score' => 4, 'critical_score' => 1),
        'target_setting' => array(
            'improvement_targets' => array('Maintain chloride 96-106 mEq/L', 'Optimize fluid and acid-base balance'),
            'timeframes' => array('immediate' => '1 week', 'short_term' => '1 month', 'long_term' => '3-6 months'),
        ),
        'sources' => array(
            'primary' => 'ACP 2023 Electrolyte Guidelines',
            'secondary' => array('https://www.ahealthacademy.com/biomarkers/', 'Am J Med 2023: Chloride Assessment', 'J Gen Intern Med 2023: Electrolytes'),
            'evidence_level' => 'A',
        ),
    ),
    'calcium' => array(
        'display_name' => 'Calcium',
        'unit' => 'mg/dL',
        'description' => 'Essential mineral for bone health, muscle function, and energy metabolism',
        'ranges' => array(
            'optimal_min' => 8.5,
            'optimal_max' => 10.5,
            'normal_min' => 8.5,
            'normal_max' => 10.5,
            'critical_min' => 7.5,
            'critical_max' => 12.0,
        ),
        'age_adjustments' => array(
            'young' => array('optimal_min' => 8.5, 'optimal_max' => 10.5),
            'adult' => array('optimal_min' => 8.5, 'optimal_max' => 10.5),
            'senior' => array('optimal_min' => 8.8, 'optimal_max' => 10.2),
        ),
        'gender_adjustments' => array(
            'male' => array('optimal_min' => 8.5, 'optimal_max' => 10.5),
            'female' => array('optimal_min' => 8.5, 'optimal_max' => 10.5),
        ),
        'clinical_significance' => 'Calcium is essential for bone health, muscle function, and energy metabolism. Both high and low levels can cause fatigue, muscle weakness, and serious health issues.',
        'risk_factors' => array('Vitamin D deficiency', 'Parathyroid disorders', 'Kidney disease', 'Medications', 'Poor diet', 'Age'),
        'optimization_recommendations' => array('Calcium-rich diet', 'Vitamin D optimization', 'Medical consultation if abnormal', 'Regular monitoring', 'Address underlying causes'),
        'flag_criteria' => array(
            'symptom_triggers' => array('fatigue', 'muscle_weakness', 'bone_pain', 'numbness', 'energy_issues'),
            'range_triggers' => array('below_8_5_mg_dl' => 'moderate', 'below_7_5_mg_dl' => 'high', 'above_10_5_mg_dl' => 'moderate', 'above_12_mg_dl' => 'high'),
        ),
        'scoring_algorithm' => array('optimal_score' => 10, 'suboptimal_score' => 7, 'poor_score' => 4, 'critical_score' => 1),
        'target_setting' => array(
            'improvement_targets' => array('Maintain calcium 8.5-10.5 mg/dL', 'Optimize bone health and energy'),
            'timeframes' => array('immediate' => '1 week', 'short_term' => '1 month', 'long_term' => '3-6 months'),
        ),
        'sources' => array(
            'primary' => 'ACP 2023 Calcium Guidelines',
            'secondary' => array('https://www.ahealthacademy.com/biomarkers/', 'Am J Med 2023: Calcium Assessment', 'J Gen Intern Med 2023: Mineral Metabolism'),
            'evidence_level' => 'A',
        ),
    ),
    'magnesium' => array(
        'display_name' => 'Magnesium',
        'unit' => 'mg/dL',
        'description' => 'Essential mineral for energy production, muscle function, and nervous system',
        'ranges' => array(
            'optimal_min' => 1.7,
            'optimal_max' => 2.2,
            'normal_min' => 1.7,
            'normal_max' => 2.2,
            'critical_min' => 1.5,
            'critical_max' => 2.5,
        ),
        'age_adjustments' => array(
            'young' => array('optimal_min' => 1.7, 'optimal_max' => 2.2),
            'adult' => array('optimal_min' => 1.7, 'optimal_max' => 2.2),
            'senior' => array('optimal_min' => 1.8, 'optimal_max' => 2.3),
        ),
        'gender_adjustments' => array(
            'male' => array('optimal_min' => 1.7, 'optimal_max' => 2.2),
            'female' => array('optimal_min' => 1.7, 'optimal_max' => 2.2),
        ),
        'clinical_significance' => 'Magnesium is essential for energy production, muscle function, and nervous system health. Deficiency is common and can cause fatigue, muscle cramps, and energy issues.',
        'risk_factors' => array('Poor diet', 'Medications', 'Alcohol consumption', 'Stress', 'Chronic illness', 'Gastrointestinal disorders'),
        'optimization_recommendations' => array('Magnesium-rich diet', 'Magnesium supplementation if needed', 'Stress management', 'Medical consultation if low', 'Regular monitoring'),
        'flag_criteria' => array(
            'symptom_triggers' => array('fatigue', 'muscle_cramps', 'irritability', 'sleep_issues', 'energy_issues'),
            'range_triggers' => array('below_1_7_mg_dl' => 'moderate', 'below_1_5_mg_dl' => 'high', 'above_2_2_mg_dl' => 'moderate', 'above_2_5_mg_dl' => 'high'),
        ),
        'scoring_algorithm' => array('optimal_score' => 10, 'suboptimal_score' => 7, 'poor_score' => 4, 'critical_score' => 1),
        'target_setting' => array(
            'improvement_targets' => array('Maintain magnesium 1.7-2.2 mg/dL', 'Optimize energy production and muscle function'),
            'timeframes' => array('immediate' => '1 week', 'short_term' => '1 month', 'long_term' => '3-6 months'),
        ),
        'sources' => array(
            'primary' => 'ACP 2023 Magnesium Guidelines',
            'secondary' => array('https://www.ahealthacademy.com/biomarkers/', 'Am J Med 2023: Magnesium Assessment', 'J Gen Intern Med 2023: Mineral Metabolism'),
            'evidence_level' => 'A',
        ),
    ),
    'carbon_dioxide' => array(
        'display_name' => 'Carbon Dioxide',
        'unit' => 'mEq/L',
        'description' => 'Bicarbonate level indicating acid-base balance and respiratory function',
        'ranges' => array(
            'optimal_min' => 22,
            'optimal_max' => 28,
            'normal_min' => 22,
            'normal_max' => 28,
            'critical_min' => 18,
            'critical_max' => 32,
        ),
        'age_adjustments' => array(
            'young' => array('optimal_min' => 22, 'optimal_max' => 28),
            'adult' => array('optimal_min' => 22, 'optimal_max' => 28),
            'senior' => array('optimal_min' => 21, 'optimal_max' => 27),
        ),
        'gender_adjustments' => array(
            'male' => array('optimal_min' => 22, 'optimal_max' => 28),
            'female' => array('optimal_min' => 22, 'optimal_max' => 28),
        ),
        'clinical_significance' => 'Carbon dioxide (bicarbonate) indicates acid-base balance and respiratory function. Abnormal levels can cause fatigue, confusion, and serious metabolic issues.',
        'risk_factors' => array('Respiratory disorders', 'Kidney disease', 'Metabolic disorders', 'Medications', 'Dehydration', 'Chronic illness'),
        'optimization_recommendations' => array('Medical consultation if abnormal', 'Address underlying causes', 'Regular monitoring', 'Respiratory optimization', 'Balanced diet'),
        'flag_criteria' => array(
            'symptom_triggers' => array('fatigue', 'shortness_of_breath', 'confusion', 'metabolic_symptoms', 'energy_issues'),
            'range_triggers' => array('below_22_meq_l' => 'moderate', 'below_18_meq_l' => 'high', 'above_28_meq_l' => 'moderate', 'above_32_meq_l' => 'high'),
        ),
        'scoring_algorithm' => array('optimal_score' => 10, 'suboptimal_score' => 7, 'poor_score' => 4, 'critical_score' => 1),
        'target_setting' => array(
            'improvement_targets' => array('Maintain CO2 22-28 mEq/L', 'Optimize acid-base balance'),
            'timeframes' => array('immediate' => '1 week', 'short_term' => '1 month', 'long_term' => '3-6 months'),
        ),
        'sources' => array(
            'primary' => 'ACP 2023 Acid-Base Guidelines',
            'secondary' => array('https://www.ahealthacademy.com/biomarkers/', 'Am J Med 2023: CO2 Assessment', 'J Gen Intern Med 2023: Acid-Base Balance'),
            'evidence_level' => 'A',
        ),
    ),
    'protein' => array(
        'display_name' => 'Protein',
        'unit' => 'g/dL',
        'description' => 'Total protein indicating nutritional status and liver function',
        'ranges' => array(
            'optimal_min' => 6.0,
            'optimal_max' => 8.3,
            'normal_min' => 6.0,
            'normal_max' => 8.3,
            'critical_min' => 5.5,
            'critical_max' => 9.0,
        ),
        'age_adjustments' => array(
            'young' => array('optimal_min' => 6.0, 'optimal_max' => 8.3),
            'adult' => array('optimal_min' => 6.0, 'optimal_max' => 8.3),
            'senior' => array('optimal_min' => 5.8, 'optimal_max' => 8.0),
        ),
        'gender_adjustments' => array(
            'male' => array('optimal_min' => 6.0, 'optimal_max' => 8.3),
            'female' => array('optimal_min' => 6.0, 'optimal_max' => 8.3),
        ),
        'clinical_significance' => 'Total protein indicates nutritional status and liver function. Low levels suggest malnutrition or liver disease affecting energy and health.',
        'risk_factors' => array('Malnutrition', 'Liver disease', 'Kidney disease', 'Chronic illness', 'Poor diet', 'Inflammation'),
        'optimization_recommendations' => array('Adequate protein intake', 'Healthy diet', 'Medical consultation if low', 'Address underlying causes', 'Regular monitoring'),
        'flag_criteria' => array(
            'symptom_triggers' => array('fatigue', 'weakness', 'edema', 'malnutrition', 'energy_issues'),
            'range_triggers' => array('below_6_g_dl' => 'moderate', 'below_5_5_g_dl' => 'high', 'above_8_3_g_dl' => 'moderate', 'above_9_g_dl' => 'high'),
        ),
        'scoring_algorithm' => array('optimal_score' => 10, 'suboptimal_score' => 7, 'poor_score' => 4, 'critical_score' => 1),
        'target_setting' => array(
            'improvement_targets' => array('Maintain protein 6.0-8.3 g/dL', 'Optimize nutrition and liver function'),
            'timeframes' => array('immediate' => '1 week', 'short_term' => '1 month', 'long_term' => '3-6 months'),
        ),
        'sources' => array(
            'primary' => 'ACP 2023 Protein Guidelines',
            'secondary' => array('https://www.ahealthacademy.com/biomarkers/', 'Am J Med 2023: Protein Assessment', 'J Gen Intern Med 2023: Nutritional Status'),
            'evidence_level' => 'A',
        ),
    ),
); 