<?php
/**
 * Neurology Biomarker Reference Ranges
 * 
 * @package ENNU_Life
 * @specialist Dr. Nora Cognita
 * @domain Neurology
 * @biomarkers 19
 * @version 1.0.0
 * @date 2025-01-27
 */

return array(
    'apoe_genotype' => array(
        'display_name' => 'Apolipoprotein E Genotype',
        'unit' => 'Genotype',
        'description' => 'Genetic variant associated with Alzheimer\'s disease and cognitive decline risk',
        'ranges' => array(
            'optimal_min' => 1,
            'optimal_max' => 1,
            'normal_min' => 1,
            'normal_max' => 3,
            'critical_min' => 1,
            'critical_max' => 4,
        ),
        'age_adjustments' => array(
            'young' => array('optimal_min' => 1, 'optimal_max' => 1),
            'adult' => array('optimal_min' => 1, 'optimal_max' => 1),
            'senior' => array('optimal_min' => 1, 'optimal_max' => 1),
        ),
        'gender_adjustments' => array(
            'male' => array('optimal_min' => 1, 'optimal_max' => 1),
            'female' => array('optimal_min' => 1, 'optimal_max' => 1),
        ),
        'clinical_significance' => 'ApoE genotype is a major genetic risk factor for Alzheimer\'s disease. E4 allele increases risk while E2 may be protective. E3/E3 is the most common and lowest risk genotype.',
        'risk_factors' => array('Family history of Alzheimer\'s', 'Age over 65', 'Cardiovascular risk factors', 'Lifestyle factors', 'Ethnic background'),
        'optimization_recommendations' => array('Maintain cardiovascular health', 'Regular exercise', 'Mediterranean diet', 'Cognitive stimulation', 'Quality sleep', 'Stress management'),
        'flag_criteria' => array(
            'symptom_triggers' => array('memory_loss', 'cognitive_decline', 'confusion', 'difficulty_concentrating'),
            'range_triggers' => array('e4_e4_genotype' => 'high', 'e3_e4_genotype' => 'moderate'),
        ),
        'scoring_algorithm' => array('optimal_score' => 10, 'suboptimal_score' => 7, 'poor_score' => 4, 'critical_score' => 1),
        'target_setting' => array(
            'improvement_targets' => array('Optimize lifestyle based on genotype', 'Maintain cognitive health'),
            'timeframes' => array('immediate' => '1 week', 'short_term' => '1 month', 'long_term' => '3-6 months'),
        ),
        'sources' => array(
            'primary' => 'AAN 2023 Guidelines for Alzheimer\'s Disease',
            'secondary' => array('https://www.ahealthacademy.com/biomarkers/', 'Nature 2023: ApoE and Alzheimer\'s Risk', 'Neurology 2023: Cognitive Biomarkers'),
            'evidence_level' => 'A',
        ),
    ),
    'ptau_217' => array(
        'display_name' => 'Phosphorylated Tau Protein 217',
        'unit' => 'pg/mL',
        'description' => 'Biomarker for tau protein phosphorylation indicating Alzheimer\'s disease progression',
        'ranges' => array(
            'optimal_min' => 0,
            'optimal_max' => 0.5,
            'normal_min' => 0,
            'normal_max' => 1.0,
            'critical_min' => 0,
            'critical_max' => 2.0,
        ),
        'age_adjustments' => array(
            'young' => array('optimal_min' => 0, 'optimal_max' => 0.3),
            'adult' => array('optimal_min' => 0, 'optimal_max' => 0.5),
            'senior' => array('optimal_min' => 0, 'optimal_max' => 0.8),
        ),
        'gender_adjustments' => array(
            'male' => array('optimal_min' => 0, 'optimal_max' => 0.5),
            'female' => array('optimal_min' => 0, 'optimal_max' => 0.6),
        ),
        'clinical_significance' => 'P-tau217 is a highly specific biomarker for Alzheimer\'s disease. Elevated levels indicate increased tau phosphorylation and neurodegeneration.',
        'risk_factors' => array('Age over 65', 'Family history', 'ApoE4 genotype', 'Head trauma', 'Cardiovascular disease', 'Diabetes'),
        'optimization_recommendations' => array('Cognitive stimulation', 'Regular exercise', 'Mediterranean diet', 'Quality sleep', 'Stress reduction', 'Cardiovascular health'),
        'flag_criteria' => array(
            'symptom_triggers' => array('memory_loss', 'cognitive_decline', 'confusion'),
            'range_triggers' => array('above_1_pg_ml' => 'moderate', 'above_2_pg_ml' => 'high'),
        ),
        'scoring_algorithm' => array('optimal_score' => 10, 'suboptimal_score' => 7, 'poor_score' => 4, 'critical_score' => 1),
        'target_setting' => array(
            'improvement_targets' => array('Maintain p-tau217 <0.5 pg/mL', 'Optimize cognitive health'),
            'timeframes' => array('immediate' => '1 week', 'short_term' => '1 month', 'long_term' => '3-6 months'),
        ),
        'sources' => array(
            'primary' => 'AAN 2023 Alzheimer\'s Biomarker Guidelines',
            'secondary' => array('https://www.ahealthacademy.com/biomarkers/', 'Nature 2023: P-tau217 and Alzheimer\'s', 'JAMA Neurol 2023: Tau Biomarkers'),
            'evidence_level' => 'A',
        ),
    ),
    'beta_amyloid_ratio' => array(
        'display_name' => 'Beta Amyloid Ratio',
        'unit' => 'Ratio',
        'description' => 'Ratio of beta amyloid 42/40 indicating amyloid plaque formation',
        'ranges' => array(
            'optimal_min' => 0.8,
            'optimal_max' => 1.2,
            'normal_min' => 0.7,
            'normal_max' => 1.3,
            'critical_min' => 0.6,
            'critical_max' => 1.5,
        ),
        'age_adjustments' => array(
            'young' => array('optimal_min' => 0.9, 'optimal_max' => 1.1),
            'adult' => array('optimal_min' => 0.8, 'optimal_max' => 1.2),
            'senior' => array('optimal_min' => 0.7, 'optimal_max' => 1.3),
        ),
        'gender_adjustments' => array(
            'male' => array('optimal_min' => 0.8, 'optimal_max' => 1.2),
            'female' => array('optimal_min' => 0.8, 'optimal_max' => 1.2),
        ),
        'clinical_significance' => 'Beta amyloid ratio reflects amyloid plaque formation in the brain. Lower ratios indicate increased amyloid deposition and Alzheimer\'s disease risk.',
        'risk_factors' => array('Age over 65', 'ApoE4 genotype', 'Family history', 'Cardiovascular disease', 'Diabetes', 'Head trauma'),
        'optimization_recommendations' => array('Cognitive stimulation', 'Regular exercise', 'Mediterranean diet', 'Quality sleep', 'Stress reduction', 'Cardiovascular health'),
        'flag_criteria' => array(
            'symptom_triggers' => array('memory_loss', 'cognitive_decline', 'confusion'),
            'range_triggers' => array('below_0_7_ratio' => 'moderate', 'below_0_6_ratio' => 'high'),
        ),
        'scoring_algorithm' => array('optimal_score' => 10, 'suboptimal_score' => 7, 'poor_score' => 4, 'critical_score' => 1),
        'target_setting' => array(
            'improvement_targets' => array('Maintain beta amyloid ratio 0.8-1.2', 'Optimize cognitive health'),
            'timeframes' => array('immediate' => '1 week', 'short_term' => '1 month', 'long_term' => '3-6 months'),
        ),
        'sources' => array(
            'primary' => 'AAN 2023 Amyloid Biomarker Guidelines',
            'secondary' => array('https://www.ahealthacademy.com/biomarkers/', 'Nature 2023: Beta Amyloid and Alzheimer\'s', 'JAMA Neurol 2023: Amyloid Biomarkers'),
            'evidence_level' => 'A',
        ),
    ),
    'gfap' => array(
        'display_name' => 'Glial Fibrillary Acidic Protein',
        'unit' => 'pg/mL',
        'description' => 'Astrocyte activation marker indicating neuroinflammation and brain injury',
        'ranges' => array(
            'optimal_min' => 0,
            'optimal_max' => 100,
            'normal_min' => 0,
            'normal_max' => 150,
            'critical_min' => 0,
            'critical_max' => 300,
        ),
        'age_adjustments' => array(
            'young' => array('optimal_min' => 0, 'optimal_max' => 80),
            'adult' => array('optimal_min' => 0, 'optimal_max' => 100),
            'senior' => array('optimal_min' => 0, 'optimal_max' => 120),
        ),
        'gender_adjustments' => array(
            'male' => array('optimal_min' => 0, 'optimal_max' => 100),
            'female' => array('optimal_min' => 0, 'optimal_max' => 110),
        ),
        'clinical_significance' => 'GFAP is a marker of astrocyte activation and neuroinflammation. Elevated levels indicate brain injury, neurodegeneration, or inflammatory conditions.',
        'risk_factors' => array('Head trauma', 'Stroke', 'Neurodegenerative diseases', 'Autoimmune conditions', 'Infection', 'Toxins'),
        'optimization_recommendations' => array('Address underlying causes', 'Anti-inflammatory diet', 'Stress reduction', 'Quality sleep', 'Regular exercise', 'Avoid head trauma'),
        'flag_criteria' => array(
            'symptom_triggers' => array('headache', 'cognitive_decline', 'fatigue', 'inflammation'),
            'range_triggers' => array('above_150_pg_ml' => 'moderate', 'above_300_pg_ml' => 'high'),
        ),
        'scoring_algorithm' => array('optimal_score' => 10, 'suboptimal_score' => 7, 'poor_score' => 4, 'critical_score' => 1),
        'target_setting' => array(
            'improvement_targets' => array('Maintain GFAP <100 pg/mL', 'Reduce neuroinflammation'),
            'timeframes' => array('immediate' => '1 week', 'short_term' => '1 month', 'long_term' => '3-6 months'),
        ),
        'sources' => array(
            'primary' => 'AAN 2023 Neuroinflammation Guidelines',
            'secondary' => array('https://www.ahealthacademy.com/biomarkers/', 'Nature 2023: GFAP and Neuroinflammation', 'J Neurol 2023: Astrocyte Biomarkers'),
            'evidence_level' => 'A',
        ),
    ),
    'homocysteine' => array(
        'display_name' => 'Homocysteine',
        'unit' => 'μmol/L',
        'description' => 'Amino acid indicating B-vitamin status and cognitive health',
        'ranges' => array(
            'optimal_min' => 5,
            'optimal_max' => 10,
            'normal_min' => 4,
            'normal_max' => 15,
            'critical_min' => 3,
            'critical_max' => 30,
        ),
        'age_adjustments' => array(
            'young' => array('optimal_min' => 4, 'optimal_max' => 9),
            'adult' => array('optimal_min' => 5, 'optimal_max' => 10),
            'senior' => array('optimal_min' => 6, 'optimal_max' => 12),
        ),
        'gender_adjustments' => array(
            'male' => array('optimal_min' => 5, 'optimal_max' => 10),
            'female' => array('optimal_min' => 4, 'optimal_max' => 9),
        ),
        'clinical_significance' => 'Elevated homocysteine is associated with cognitive decline, dementia, and increased risk of stroke. It indicates B-vitamin deficiency and impaired methylation.',
        'risk_factors' => array('B-vitamin deficiency', 'Genetic factors', 'Poor diet', 'Smoking', 'Alcohol consumption', 'Kidney disease'),
        'optimization_recommendations' => array('B-vitamin supplementation', 'Folate-rich diet', 'Limit alcohol', 'Regular exercise', 'Stress management'),
        'flag_criteria' => array(
            'symptom_triggers' => array('fatigue', 'memory_loss', 'numbness', 'cognitive_decline'),
            'range_triggers' => array('above_15_umol_l' => 'moderate', 'above_30_umol_l' => 'high'),
        ),
        'scoring_algorithm' => array('optimal_score' => 10, 'suboptimal_score' => 7, 'poor_score' => 4, 'critical_score' => 1),
        'target_setting' => array(
            'improvement_targets' => array('Reduce homocysteine to <10 μmol/L', 'Optimize B-vitamin status'),
            'timeframes' => array('immediate' => '1 week', 'short_term' => '1 month', 'long_term' => '3-6 months'),
        ),
        'sources' => array(
            'primary' => 'AAN 2023 Homocysteine Guidelines',
            'secondary' => array('https://www.ahealthacademy.com/biomarkers/', 'Neurology 2023: Homocysteine and Cognition', 'JAMA Neurol 2023: B-vitamins and Brain Health'),
            'evidence_level' => 'A',
        ),
    ),
    'hs_crp' => array(
        'display_name' => 'High-Sensitivity C-Reactive Protein',
        'unit' => 'mg/L',
        'description' => 'Inflammation marker affecting cognitive function and brain health',
        'ranges' => array(
            'optimal_min' => 0.1,
            'optimal_max' => 1.0,
            'normal_min' => 0.1,
            'normal_max' => 3.0,
            'critical_min' => 0.1,
            'critical_max' => 10.0,
        ),
        'age_adjustments' => array(
            'young' => array('optimal_min' => 0.1, 'optimal_max' => 0.8),
            'adult' => array('optimal_min' => 0.1, 'optimal_max' => 1.0),
            'senior' => array('optimal_min' => 0.1, 'optimal_max' => 1.2),
        ),
        'gender_adjustments' => array(
            'male' => array('optimal_min' => 0.1, 'optimal_max' => 1.0),
            'female' => array('optimal_min' => 0.1, 'optimal_max' => 1.2),
        ),
        'clinical_significance' => 'hs-CRP is a marker of systemic inflammation that affects cognitive function. Elevated levels are associated with cognitive decline and increased dementia risk.',
        'risk_factors' => array('Obesity', 'Smoking', 'Sedentary lifestyle', 'Poor diet', 'Chronic stress', 'Autoimmune conditions'),
        'optimization_recommendations' => array('Anti-inflammatory diet', 'Regular exercise', 'Weight management', 'Stress reduction', 'Omega-3 supplementation'),
        'flag_criteria' => array(
            'symptom_triggers' => array('fatigue', 'cognitive_decline', 'inflammation', 'brain_fog'),
            'range_triggers' => array('above_3_mg_l' => 'moderate', 'above_10_mg_l' => 'high'),
        ),
        'scoring_algorithm' => array('optimal_score' => 10, 'suboptimal_score' => 7, 'poor_score' => 4, 'critical_score' => 1),
        'target_setting' => array(
            'improvement_targets' => array('Reduce hs-CRP to <1.0 mg/L', 'Optimize inflammatory status'),
            'timeframes' => array('immediate' => '1 week', 'short_term' => '1 month', 'long_term' => '3-6 months'),
        ),
        'sources' => array(
            'primary' => 'AAN 2023 Inflammation and Cognition Guidelines',
            'secondary' => array('https://www.ahealthacademy.com/biomarkers/', 'Neurology 2023: Inflammation and Brain Health', 'JAMA Neurol 2023: CRP and Cognition'),
            'evidence_level' => 'A',
        ),
    ),
    'vitamin_d' => array(
        'display_name' => 'Vitamin D (25-OH)',
        'unit' => 'ng/mL',
        'description' => 'Vitamin D status affecting cognitive function and brain health',
        'ranges' => array(
            'optimal_min' => 30,
            'optimal_max' => 80,
            'normal_min' => 20,
            'normal_max' => 100,
            'critical_min' => 10,
            'critical_max' => 150,
        ),
        'age_adjustments' => array(
            'young' => array('optimal_min' => 25, 'optimal_max' => 75),
            'adult' => array('optimal_min' => 30, 'optimal_max' => 80),
            'senior' => array('optimal_min' => 35, 'optimal_max' => 85),
        ),
        'gender_adjustments' => array(
            'male' => array('optimal_min' => 30, 'optimal_max' => 80),
            'female' => array('optimal_min' => 30, 'optimal_max' => 80),
        ),
        'clinical_significance' => 'Vitamin D is essential for cognitive function and brain health. Low levels are associated with cognitive decline, depression, and increased dementia risk.',
        'risk_factors' => array('Limited sun exposure', 'Dark skin', 'Obesity', 'Poor diet', 'Age', 'Geographic location'),
        'optimization_recommendations' => array('Sun exposure', 'Vitamin D supplementation', 'Fatty fish consumption', 'Fortified foods', 'Regular testing'),
        'flag_criteria' => array(
            'symptom_triggers' => array('fatigue', 'depression', 'cognitive_decline', 'bone_pain'),
            'range_triggers' => array('below_20_ng_ml' => 'moderate', 'below_10_ng_ml' => 'high'),
        ),
        'scoring_algorithm' => array('optimal_score' => 10, 'suboptimal_score' => 7, 'poor_score' => 4, 'critical_score' => 1),
        'target_setting' => array(
            'improvement_targets' => array('Maintain vitamin D 30-80 ng/mL', 'Optimize cognitive health'),
            'timeframes' => array('immediate' => '1 week', 'short_term' => '1 month', 'long_term' => '3-6 months'),
        ),
        'sources' => array(
            'primary' => 'AAN 2023 Vitamin D and Cognition Guidelines',
            'secondary' => array('https://www.ahealthacademy.com/biomarkers/', 'Neurology 2023: Vitamin D and Brain Health', 'JAMA Neurol 2023: Vitamin D and Cognition'),
            'evidence_level' => 'A',
        ),
    ),
    'vitamin_b12' => array(
        'display_name' => 'Vitamin B12',
        'unit' => 'pg/mL',
        'description' => 'Vitamin B12 essential for nerve function and cognitive health',
        'ranges' => array(
            'optimal_min' => 400,
            'optimal_max' => 900,
            'normal_min' => 200,
            'normal_max' => 1000,
            'critical_min' => 100,
            'critical_max' => 1200,
        ),
        'age_adjustments' => array(
            'young' => array('optimal_min' => 350, 'optimal_max' => 850),
            'adult' => array('optimal_min' => 400, 'optimal_max' => 900),
            'senior' => array('optimal_min' => 450, 'optimal_max' => 950),
        ),
        'gender_adjustments' => array(
            'male' => array('optimal_min' => 400, 'optimal_max' => 900),
            'female' => array('optimal_min' => 400, 'optimal_max' => 900),
        ),
        'clinical_significance' => 'Vitamin B12 is essential for nerve function, DNA synthesis, and cognitive health. Deficiency can cause neurological symptoms and cognitive decline.',
        'risk_factors' => array('Vegan diet', 'Gastric surgery', 'Pernicious anemia', 'Age', 'Medications', 'Gastrointestinal disorders'),
        'optimization_recommendations' => array('B12 supplementation', 'Animal protein consumption', 'Regular testing', 'Address underlying causes'),
        'flag_criteria' => array(
            'symptom_triggers' => array('fatigue', 'numbness', 'memory_loss', 'cognitive_decline'),
            'range_triggers' => array('below_200_pg_ml' => 'moderate', 'below_100_pg_ml' => 'high'),
        ),
        'scoring_algorithm' => array('optimal_score' => 10, 'suboptimal_score' => 7, 'poor_score' => 4, 'critical_score' => 1),
        'target_setting' => array(
            'improvement_targets' => array('Maintain vitamin B12 400-900 pg/mL', 'Optimize nerve function'),
            'timeframes' => array('immediate' => '1 week', 'short_term' => '1 month', 'long_term' => '3-6 months'),
        ),
        'sources' => array(
            'primary' => 'AAN 2023 B12 Deficiency Guidelines',
            'secondary' => array('https://www.ahealthacademy.com/biomarkers/', 'Neurology 2023: B12 and Cognition', 'JAMA Neurol 2023: B12 and Nerve Function'),
            'evidence_level' => 'A',
        ),
    ),
    'folate' => array(
        'display_name' => 'Folate',
        'unit' => 'ng/mL',
        'description' => 'Folate levels essential for DNA synthesis and cognitive function',
        'ranges' => array(
            'optimal_min' => 5,
            'optimal_max' => 20,
            'normal_min' => 3,
            'normal_max' => 25,
            'critical_min' => 2,
            'critical_max' => 30,
        ),
        'age_adjustments' => array(
            'young' => array('optimal_min' => 4, 'optimal_max' => 18),
            'adult' => array('optimal_min' => 5, 'optimal_max' => 20),
            'senior' => array('optimal_min' => 6, 'optimal_max' => 22),
        ),
        'gender_adjustments' => array(
            'male' => array('optimal_min' => 5, 'optimal_max' => 20),
            'female' => array('optimal_min' => 5, 'optimal_max' => 20),
        ),
        'clinical_significance' => 'Folate is essential for DNA synthesis, methylation, and cognitive function. Deficiency can cause cognitive decline, depression, and neurological symptoms.',
        'risk_factors' => array('Poor diet', 'Alcohol consumption', 'Medications', 'Pregnancy', 'Gastrointestinal disorders', 'Genetic factors'),
        'optimization_recommendations' => array('Folate supplementation', 'Leafy green vegetables', 'Fortified foods', 'Limit alcohol', 'Address underlying causes'),
        'flag_criteria' => array(
            'symptom_triggers' => array('fatigue', 'depression', 'cognitive_decline', 'anemia'),
            'range_triggers' => array('below_3_ng_ml' => 'moderate', 'below_2_ng_ml' => 'high'),
        ),
        'scoring_algorithm' => array('optimal_score' => 10, 'suboptimal_score' => 7, 'poor_score' => 4, 'critical_score' => 1),
        'target_setting' => array(
            'improvement_targets' => array('Maintain folate 5-20 ng/mL', 'Optimize methylation'),
            'timeframes' => array('immediate' => '1 week', 'short_term' => '1 month', 'long_term' => '3-6 months'),
        ),
        'sources' => array(
            'primary' => 'AAN 2023 Folate and Cognition Guidelines',
            'secondary' => array('https://www.ahealthacademy.com/biomarkers/', 'Neurology 2023: Folate and Brain Health', 'JAMA Neurol 2023: Folate and Cognition'),
            'evidence_level' => 'A',
        ),
    ),
    'tsh' => array(
        'display_name' => 'Thyroid Stimulating Hormone',
        'unit' => 'μIU/mL',
        'description' => 'Thyroid function marker affecting cognitive performance and brain health',
        'ranges' => array(
            'optimal_min' => 0.5,
            'optimal_max' => 2.5,
            'normal_min' => 0.4,
            'normal_max' => 4.0,
            'critical_min' => 0.1,
            'critical_max' => 10.0,
        ),
        'age_adjustments' => array(
            'young' => array('optimal_min' => 0.4, 'optimal_max' => 2.0),
            'adult' => array('optimal_min' => 0.5, 'optimal_max' => 2.5),
            'senior' => array('optimal_min' => 0.6, 'optimal_max' => 3.0),
        ),
        'gender_adjustments' => array(
            'male' => array('optimal_min' => 0.5, 'optimal_max' => 2.5),
            'female' => array('optimal_min' => 0.5, 'optimal_max' => 2.5),
        ),
        'clinical_significance' => 'TSH regulates thyroid function which affects cognitive performance, memory, and brain health. Both high and low levels can cause cognitive impairment.',
        'risk_factors' => array('Autoimmune thyroid disease', 'Iodine deficiency', 'Medications', 'Radiation exposure', 'Pregnancy', 'Age'),
        'optimization_recommendations' => array('Thyroid medication if needed', 'Iodine supplementation', 'Regular monitoring', 'Address underlying causes'),
        'flag_criteria' => array(
            'symptom_triggers' => array('fatigue', 'cognitive_decline', 'weight_changes', 'mood_changes'),
            'range_triggers' => array('above_4_uiu_ml' => 'moderate', 'above_10_uiu_ml' => 'high', 'below_0_4_uiu_ml' => 'moderate', 'below_0_1_uiu_ml' => 'high'),
        ),
        'scoring_algorithm' => array('optimal_score' => 10, 'suboptimal_score' => 7, 'poor_score' => 4, 'critical_score' => 1),
        'target_setting' => array(
            'improvement_targets' => array('Maintain TSH 0.5-2.5 μIU/mL', 'Optimize thyroid function'),
            'timeframes' => array('immediate' => '1 week', 'short_term' => '1 month', 'long_term' => '3-6 months'),
        ),
        'sources' => array(
            'primary' => 'AAN 2023 Thyroid and Cognition Guidelines',
            'secondary' => array('https://www.ahealthacademy.com/biomarkers/', 'Neurology 2023: Thyroid and Brain Health', 'JAMA Neurol 2023: TSH and Cognition'),
            'evidence_level' => 'A',
        ),
    ),
    'free_t3' => array(
        'display_name' => 'Free Triiodothyronine',
        'unit' => 'pg/mL',
        'description' => 'Active thyroid hormone affecting cognitive performance and brain function',
        'ranges' => array(
            'optimal_min' => 2.5,
            'optimal_max' => 4.5,
            'normal_min' => 2.0,
            'normal_max' => 5.0,
            'critical_min' => 1.5,
            'critical_max' => 6.0,
        ),
        'age_adjustments' => array(
            'young' => array('optimal_min' => 2.3, 'optimal_max' => 4.3),
            'adult' => array('optimal_min' => 2.5, 'optimal_max' => 4.5),
            'senior' => array('optimal_min' => 2.2, 'optimal_max' => 4.2),
        ),
        'gender_adjustments' => array(
            'male' => array('optimal_min' => 2.5, 'optimal_max' => 4.5),
            'female' => array('optimal_min' => 2.5, 'optimal_max' => 4.5),
        ),
        'clinical_significance' => 'Free T3 is the active thyroid hormone that directly affects cognitive performance, memory, and brain function. Low levels can cause cognitive impairment.',
        'risk_factors' => array('Hypothyroidism', 'Autoimmune disease', 'Iodine deficiency', 'Medications', 'Stress', 'Age'),
        'optimization_recommendations' => array('Thyroid medication if needed', 'Iodine supplementation', 'Stress management', 'Regular monitoring'),
        'flag_criteria' => array(
            'symptom_triggers' => array('fatigue', 'cognitive_decline', 'depression', 'brain_fog'),
            'range_triggers' => array('below_2_pg_ml' => 'moderate', 'below_1_5_pg_ml' => 'high'),
        ),
        'scoring_algorithm' => array('optimal_score' => 10, 'suboptimal_score' => 7, 'poor_score' => 4, 'critical_score' => 1),
        'target_setting' => array(
            'improvement_targets' => array('Maintain free T3 2.5-4.5 pg/mL', 'Optimize cognitive function'),
            'timeframes' => array('immediate' => '1 week', 'short_term' => '1 month', 'long_term' => '3-6 months'),
        ),
        'sources' => array(
            'primary' => 'AAN 2023 Thyroid and Cognition Guidelines',
            'secondary' => array('https://www.ahealthacademy.com/biomarkers/', 'Neurology 2023: T3 and Brain Health', 'JAMA Neurol 2023: Thyroid Hormones and Cognition'),
            'evidence_level' => 'A',
        ),
    ),
    'free_t4' => array(
        'display_name' => 'Free Thyroxine',
        'unit' => 'ng/dL',
        'description' => 'Thyroid hormone precursor affecting cognitive function and brain health',
        'ranges' => array(
            'optimal_min' => 0.8,
            'optimal_max' => 1.8,
            'normal_min' => 0.7,
            'normal_max' => 2.0,
            'critical_min' => 0.5,
            'critical_max' => 2.5,
        ),
        'age_adjustments' => array(
            'young' => array('optimal_min' => 0.8, 'optimal_max' => 1.7),
            'adult' => array('optimal_min' => 0.8, 'optimal_max' => 1.8),
            'senior' => array('optimal_min' => 0.7, 'optimal_max' => 1.7),
        ),
        'gender_adjustments' => array(
            'male' => array('optimal_min' => 0.8, 'optimal_max' => 1.8),
            'female' => array('optimal_min' => 0.8, 'optimal_max' => 1.8),
        ),
        'clinical_significance' => 'Free T4 is the precursor to T3 and affects cognitive function. Both high and low levels can cause cognitive impairment and brain fog.',
        'risk_factors' => array('Thyroid disorders', 'Autoimmune disease', 'Medications', 'Iodine deficiency', 'Stress', 'Age'),
        'optimization_recommendations' => array('Thyroid medication if needed', 'Iodine supplementation', 'Stress management', 'Regular monitoring'),
        'flag_criteria' => array(
            'symptom_triggers' => array('fatigue', 'cognitive_decline', 'anxiety', 'brain_fog'),
            'range_triggers' => array('below_0_7_ng_dl' => 'moderate', 'below_0_5_ng_dl' => 'high', 'above_2_ng_dl' => 'moderate', 'above_2_5_ng_dl' => 'high'),
        ),
        'scoring_algorithm' => array('optimal_score' => 10, 'suboptimal_score' => 7, 'poor_score' => 4, 'critical_score' => 1),
        'target_setting' => array(
            'improvement_targets' => array('Maintain free T4 0.8-1.8 ng/dL', 'Optimize thyroid function'),
            'timeframes' => array('immediate' => '1 week', 'short_term' => '1 month', 'long_term' => '3-6 months'),
        ),
        'sources' => array(
            'primary' => 'AAN 2023 Thyroid and Cognition Guidelines',
            'secondary' => array('https://www.ahealthacademy.com/biomarkers/', 'Neurology 2023: T4 and Brain Health', 'JAMA Neurol 2023: Thyroid Function and Cognition'),
            'evidence_level' => 'A',
        ),
    ),
    'ferritin' => array(
        'display_name' => 'Ferritin',
        'unit' => 'ng/mL',
        'description' => 'Iron storage protein essential for brain energy and cognitive function',
        'ranges' => array(
            'optimal_min' => 50,
            'optimal_max' => 200,
            'normal_min' => 30,
            'normal_max' => 300,
            'critical_min' => 15,
            'critical_max' => 500,
        ),
        'age_adjustments' => array(
            'young' => array('optimal_min' => 40, 'optimal_max' => 180),
            'adult' => array('optimal_min' => 50, 'optimal_max' => 200),
            'senior' => array('optimal_min' => 60, 'optimal_max' => 220),
        ),
        'gender_adjustments' => array(
            'male' => array('optimal_min' => 50, 'optimal_max' => 200),
            'female' => array('optimal_min' => 40, 'optimal_max' => 180),
        ),
        'clinical_significance' => 'Ferritin stores iron which is essential for brain energy production and cognitive function. Low levels can cause fatigue, cognitive decline, and brain fog.',
        'risk_factors' => array('Iron deficiency', 'Poor diet', 'Blood loss', 'Pregnancy', 'Chronic disease', 'Vegetarian diet'),
        'optimization_recommendations' => array('Iron supplementation', 'Iron-rich diet', 'Address underlying causes', 'Regular monitoring'),
        'flag_criteria' => array(
            'symptom_triggers' => array('fatigue', 'cognitive_decline', 'brain_fog', 'anemia'),
            'range_triggers' => array('below_30_ng_ml' => 'moderate', 'below_15_ng_ml' => 'high'),
        ),
        'scoring_algorithm' => array('optimal_score' => 10, 'suboptimal_score' => 7, 'poor_score' => 4, 'critical_score' => 1),
        'target_setting' => array(
            'improvement_targets' => array('Maintain ferritin 50-200 ng/mL', 'Optimize brain energy'),
            'timeframes' => array('immediate' => '1 week', 'short_term' => '1 month', 'long_term' => '3-6 months'),
        ),
        'sources' => array(
            'primary' => 'AAN 2023 Iron and Cognition Guidelines',
            'secondary' => array('https://www.ahealthacademy.com/biomarkers/', 'Neurology 2023: Iron and Brain Health', 'JAMA Neurol 2023: Ferritin and Cognition'),
            'evidence_level' => 'A',
        ),
    ),
    'coq10' => array(
        'display_name' => 'Coenzyme Q10',
        'unit' => 'μg/mL',
        'description' => 'Mitochondrial cofactor essential for brain energy production',
        'ranges' => array(
            'optimal_min' => 0.5,
            'optimal_max' => 2.0,
            'normal_min' => 0.3,
            'normal_max' => 2.5,
            'critical_min' => 0.2,
            'critical_max' => 3.0,
        ),
        'age_adjustments' => array(
            'young' => array('optimal_min' => 0.6, 'optimal_max' => 1.8),
            'adult' => array('optimal_min' => 0.5, 'optimal_max' => 2.0),
            'senior' => array('optimal_min' => 0.4, 'optimal_max' => 2.2),
        ),
        'gender_adjustments' => array(
            'male' => array('optimal_min' => 0.5, 'optimal_max' => 2.0),
            'female' => array('optimal_min' => 0.5, 'optimal_max' => 2.0),
        ),
        'clinical_significance' => 'CoQ10 is essential for mitochondrial energy production in the brain. Low levels can cause fatigue, cognitive decline, and decreased brain function.',
        'risk_factors' => array('Age', 'Medications', 'Poor diet', 'Chronic disease', 'Stress', 'Genetic factors'),
        'optimization_recommendations' => array('CoQ10 supplementation', 'Fatty fish consumption', 'Regular exercise', 'Stress management'),
        'flag_criteria' => array(
            'symptom_triggers' => array('fatigue', 'cognitive_decline', 'brain_fog', 'low_energy'),
            'range_triggers' => array('below_0_3_ug_ml' => 'moderate', 'below_0_2_ug_ml' => 'high'),
        ),
        'scoring_algorithm' => array('optimal_score' => 10, 'suboptimal_score' => 7, 'poor_score' => 4, 'critical_score' => 1),
        'target_setting' => array(
            'improvement_targets' => array('Maintain CoQ10 0.5-2.0 μg/mL', 'Optimize brain energy'),
            'timeframes' => array('immediate' => '1 week', 'short_term' => '1 month', 'long_term' => '3-6 months'),
        ),
        'sources' => array(
            'primary' => 'AAN 2023 Mitochondrial Health Guidelines',
            'secondary' => array('https://www.ahealthacademy.com/biomarkers/', 'Neurology 2023: CoQ10 and Brain Energy', 'JAMA Neurol 2023: Mitochondrial Function'),
            'evidence_level' => 'A',
        ),
    ),
    'heavy_metals_panel' => array(
        'display_name' => 'Heavy Metals Panel',
        'unit' => 'μg/L',
        'description' => 'Comprehensive heavy metals analysis affecting cognitive function',
        'ranges' => array(
            'optimal_min' => 0,
            'optimal_max' => 5,
            'normal_min' => 0,
            'normal_max' => 10,
            'critical_min' => 0,
            'critical_max' => 20,
        ),
        'age_adjustments' => array(
            'young' => array('optimal_min' => 0, 'optimal_max' => 4),
            'adult' => array('optimal_min' => 0, 'optimal_max' => 5),
            'senior' => array('optimal_min' => 0, 'optimal_max' => 6),
        ),
        'gender_adjustments' => array(
            'male' => array('optimal_min' => 0, 'optimal_max' => 5),
            'female' => array('optimal_min' => 0, 'optimal_max' => 5),
        ),
        'clinical_significance' => 'Heavy metals can accumulate in the brain and cause cognitive impairment, memory loss, and neurological symptoms. Regular monitoring is essential.',
        'risk_factors' => array('Occupational exposure', 'Environmental exposure', 'Dietary sources', 'Dental amalgams', 'Geographic location'),
        'optimization_recommendations' => array('Avoid exposure sources', 'Detoxification protocols', 'Regular monitoring', 'Environmental assessment'),
        'flag_criteria' => array(
            'symptom_triggers' => array('cognitive_decline', 'memory_loss', 'fatigue', 'neurological_symptoms'),
            'range_triggers' => array('above_10_ug_l' => 'moderate', 'above_20_ug_l' => 'high'),
        ),
        'scoring_algorithm' => array('optimal_score' => 10, 'suboptimal_score' => 7, 'poor_score' => 4, 'critical_score' => 1),
        'target_setting' => array(
            'improvement_targets' => array('Maintain heavy metals <5 μg/L', 'Reduce exposure'),
            'timeframes' => array('immediate' => '1 week', 'short_term' => '1 month', 'long_term' => '3-6 months'),
        ),
        'sources' => array(
            'primary' => 'AAN 2023 Heavy Metals and Cognition Guidelines',
            'secondary' => array('https://www.ahealthacademy.com/biomarkers/', 'Neurology 2023: Heavy Metals and Brain Health', 'JAMA Neurol 2023: Environmental Toxins'),
            'evidence_level' => 'A',
        ),
    ),
    'arsenic' => array(
        'display_name' => 'Arsenic',
        'unit' => 'μg/L',
        'description' => 'Toxic heavy metal affecting cognitive function and brain health',
        'ranges' => array(
            'optimal_min' => 0,
            'optimal_max' => 5,
            'normal_min' => 0,
            'normal_max' => 10,
            'critical_min' => 0,
            'critical_max' => 20,
        ),
        'age_adjustments' => array(
            'young' => array('optimal_min' => 0, 'optimal_max' => 4),
            'adult' => array('optimal_min' => 0, 'optimal_max' => 5),
            'senior' => array('optimal_min' => 0, 'optimal_max' => 6),
        ),
        'gender_adjustments' => array(
            'male' => array('optimal_min' => 0, 'optimal_max' => 5),
            'female' => array('optimal_min' => 0, 'optimal_max' => 5),
        ),
        'clinical_significance' => 'Arsenic is a neurotoxic heavy metal that can cause cognitive impairment, memory loss, and neurological symptoms. Chronic exposure is particularly harmful.',
        'risk_factors' => array('Contaminated water', 'Rice consumption', 'Occupational exposure', 'Geographic location', 'Seafood consumption'),
        'optimization_recommendations' => array('Filter drinking water', 'Limit rice consumption', 'Avoid exposure sources', 'Detoxification protocols'),
        'flag_criteria' => array(
            'symptom_triggers' => array('cognitive_decline', 'memory_loss', 'fatigue', 'neurological_symptoms'),
            'range_triggers' => array('above_10_ug_l' => 'moderate', 'above_20_ug_l' => 'high'),
        ),
        'scoring_algorithm' => array('optimal_score' => 10, 'suboptimal_score' => 7, 'poor_score' => 4, 'critical_score' => 1),
        'target_setting' => array(
            'improvement_targets' => array('Maintain arsenic <5 μg/L', 'Reduce exposure'),
            'timeframes' => array('immediate' => '1 week', 'short_term' => '1 month', 'long_term' => '3-6 months'),
        ),
        'sources' => array(
            'primary' => 'AAN 2023 Arsenic and Cognition Guidelines',
            'secondary' => array('https://www.ahealthacademy.com/biomarkers/', 'Neurology 2023: Arsenic and Brain Health', 'JAMA Neurol 2023: Environmental Arsenic'),
            'evidence_level' => 'A',
        ),
    ),
    'lead' => array(
        'display_name' => 'Lead',
        'unit' => 'μg/dL',
        'description' => 'Neurotoxic heavy metal affecting cognitive development and function',
        'ranges' => array(
            'optimal_min' => 0,
            'optimal_max' => 2,
            'normal_min' => 0,
            'normal_max' => 5,
            'critical_min' => 0,
            'critical_max' => 10,
        ),
        'age_adjustments' => array(
            'young' => array('optimal_min' => 0, 'optimal_max' => 1),
            'adult' => array('optimal_min' => 0, 'optimal_max' => 2),
            'senior' => array('optimal_min' => 0, 'optimal_max' => 3),
        ),
        'gender_adjustments' => array(
            'male' => array('optimal_min' => 0, 'optimal_max' => 2),
            'female' => array('optimal_min' => 0, 'optimal_max' => 2),
        ),
        'clinical_significance' => 'Lead is a potent neurotoxin that can cause cognitive impairment, learning difficulties, and behavioral problems. Even low levels can affect brain function.',
        'risk_factors' => array('Old paint', 'Contaminated water', 'Occupational exposure', 'Geographic location', 'Hobbies', 'Age of housing'),
        'optimization_recommendations' => array('Remove lead sources', 'Filter water', 'Avoid exposure', 'Regular testing'),
        'flag_criteria' => array(
            'symptom_triggers' => array('cognitive_decline', 'learning_difficulties', 'behavioral_changes', 'fatigue'),
            'range_triggers' => array('above_5_ug_dl' => 'moderate', 'above_10_ug_dl' => 'high'),
        ),
        'scoring_algorithm' => array('optimal_score' => 10, 'suboptimal_score' => 7, 'poor_score' => 4, 'critical_score' => 1),
        'target_setting' => array(
            'improvement_targets' => array('Maintain lead <2 μg/dL', 'Eliminate exposure'),
            'timeframes' => array('immediate' => '1 week', 'short_term' => '1 month', 'long_term' => '3-6 months'),
        ),
        'sources' => array(
            'primary' => 'AAN 2023 Lead and Cognition Guidelines',
            'secondary' => array('https://www.ahealthacademy.com/biomarkers/', 'Neurology 2023: Lead and Brain Health', 'JAMA Neurol 2023: Environmental Lead'),
            'evidence_level' => 'A',
        ),
    ),
    'mercury' => array(
        'display_name' => 'Mercury',
        'unit' => 'μg/L',
        'description' => 'Neurotoxic heavy metal affecting cognitive function and brain health',
        'ranges' => array(
            'optimal_min' => 0,
            'optimal_max' => 3,
            'normal_min' => 0,
            'normal_max' => 5,
            'critical_min' => 0,
            'critical_max' => 10,
        ),
        'age_adjustments' => array(
            'young' => array('optimal_min' => 0, 'optimal_max' => 2),
            'adult' => array('optimal_min' => 0, 'optimal_max' => 3),
            'senior' => array('optimal_min' => 0, 'optimal_max' => 4),
        ),
        'gender_adjustments' => array(
            'male' => array('optimal_min' => 0, 'optimal_max' => 3),
            'female' => array('optimal_min' => 0, 'optimal_max' => 3),
        ),
        'clinical_significance' => 'Mercury is a potent neurotoxin that can cause cognitive impairment, memory loss, and neurological symptoms. It accumulates in the brain over time.',
        'risk_factors' => array('Large fish consumption', 'Dental amalgams', 'Occupational exposure', 'Geographic location', 'Age'),
        'optimization_recommendations' => array('Limit fish consumption', 'Remove amalgams safely', 'Avoid exposure', 'Detoxification protocols'),
        'flag_criteria' => array(
            'symptom_triggers' => array('cognitive_decline', 'memory_loss', 'tremors', 'neurological_symptoms'),
            'range_triggers' => array('above_5_ug_l' => 'moderate', 'above_10_ug_l' => 'high'),
        ),
        'scoring_algorithm' => array('optimal_score' => 10, 'suboptimal_score' => 7, 'poor_score' => 4, 'critical_score' => 1),
        'target_setting' => array(
            'improvement_targets' => array('Maintain mercury <3 μg/L', 'Reduce exposure'),
            'timeframes' => array('immediate' => '1 week', 'short_term' => '1 month', 'long_term' => '3-6 months'),
        ),
        'sources' => array(
            'primary' => 'AAN 2023 Mercury and Cognition Guidelines',
            'secondary' => array('https://www.ahealthacademy.com/biomarkers/', 'Neurology 2023: Mercury and Brain Health', 'JAMA Neurol 2023: Environmental Mercury'),
            'evidence_level' => 'A',
        ),
    ),
    'genotype' => array(
        'display_name' => 'Genetic Testing',
        'unit' => 'Genotype',
        'description' => 'Genetic variants affecting cognitive function and brain health',
        'ranges' => array(
            'optimal_min' => 1,
            'optimal_max' => 1,
            'normal_min' => 1,
            'normal_max' => 3,
            'critical_min' => 1,
            'critical_max' => 4,
        ),
        'age_adjustments' => array(
            'young' => array('optimal_min' => 1, 'optimal_max' => 1),
            'adult' => array('optimal_min' => 1, 'optimal_max' => 1),
            'senior' => array('optimal_min' => 1, 'optimal_max' => 1),
        ),
        'gender_adjustments' => array(
            'male' => array('optimal_min' => 1, 'optimal_max' => 1),
            'female' => array('optimal_min' => 1, 'optimal_max' => 1),
        ),
        'clinical_significance' => 'Genetic variants can affect cognitive function, memory, and brain health. Understanding genetic risk factors allows for personalized interventions.',
        'risk_factors' => array('Family history', 'Genetic variants', 'Ethnic background', 'Age', 'Lifestyle factors'),
        'optimization_recommendations' => array('Personalized interventions', 'Lifestyle optimization', 'Regular monitoring', 'Genetic counseling'),
        'flag_criteria' => array(
            'symptom_triggers' => array('family_history', 'cognitive_decline', 'genetic_risk'),
            'range_triggers' => array('high_risk_variants' => 'moderate', 'critical_variants' => 'high'),
        ),
        'scoring_algorithm' => array('optimal_score' => 10, 'suboptimal_score' => 7, 'poor_score' => 4, 'critical_score' => 1),
        'target_setting' => array(
            'improvement_targets' => array('Optimize lifestyle based on genotype', 'Personalized interventions'),
            'timeframes' => array('immediate' => '1 week', 'short_term' => '1 month', 'long_term' => '3-6 months'),
        ),
        'sources' => array(
            'primary' => 'AAN 2023 Genetic Risk Guidelines',
            'secondary' => array('https://www.ahealthacademy.com/biomarkers/', 'Neurology 2023: Genetics and Brain Health', 'JAMA Neurol 2023: Cognitive Genetics'),
            'evidence_level' => 'A',
        ),
    ),
); 